# Generated by Django 3.2.3 on 2021-07-05 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0034_application_sheet_exporting_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMRStudents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('successful_questions_count', models.PositiveSmallIntegerField(default=0, verbose_name='Número de respostas contabilizadas')),
                ('application_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicationstudent', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Aluno do upload de gabarito',
                'verbose_name_plural': 'Alunos do upload de gabarito',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OMRUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Em fila'), (1, 'Processando'), (2, 'Finalizado'), (3, 'Erro'), (4, 'Desconhecido')], default=0, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('processing_log', models.TextField(default='', verbose_name='Resultado da operação')),
                ('error_pages_count', models.PositiveSmallIntegerField(default=0, verbose_name='Folhas com erro')),
                ('total_pages', models.PositiveSmallIntegerField(default=0, verbose_name='Número de folhas')),
                ('application_students', models.ManyToManyField(blank=True, related_name='omr_uploads', through='omr.OMRStudents', to='applications.ApplicationStudent', verbose_name='Alunos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Upload de gabaritos',
                'verbose_name_plural': 'Uploads de gabaritos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='omrstudents',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omr.omrupload', verbose_name='Upload'),
        ),
    ]
