# Generated by Django 3.2.4 on 2021-08-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrupload',
            name='filename',
            field=models.TextField(blank=True, null=True, verbose_name='Arquivo enviado'),
        ),
    ]
