# Generated by Django 3.2.4 on 2021-10-19 20:16

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import fiscallizeon.core.storage_backends
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0002_omrupload_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrstudents',
            name='scan_image',
            field=models.ImageField(blank=True, null=True, storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to='omr/scans/', verbose_name='Imagem do escaneamento'),
        ),
        migrations.CreateModel(
            name='OMRErrors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('error_image', models.ImageField(storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to='omr/scans/', verbose_name='Imagem do escaneamento')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'QRCode não identificado'), (2, 'Marcações não identificadas'), (3, 'Aluno não encontrado'), (0, 'Outro')], default=0, verbose_name='Categoria')),
                ('page_number', models.PositiveSmallIntegerField(default=0, verbose_name='Página no documento')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omr.omrupload', verbose_name='Upload')),
            ],
            options={
                'verbose_name': 'Erro de leitura de gabarito',
                'verbose_name_plural': 'Erros de leitura de gabarito',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
