# Generated by Django 3.2.4 on 2021-10-19 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0003_auto_20211019_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OMRErrors',
            new_name='OMRError',
        ),
    ]
