# Generated by Django 3.2.4 on 2021-10-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0004_rename_omrerrors_omrerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrerror',
            name='is_solved',
            field=models.BooleanField(default=False, verbose_name='Reolvido'),
        ),
    ]
