# Generated by Django 3.2.4 on 2021-10-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0005_omrerror_is_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrupload',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Em fila'), (1, 'Processando'), (2, 'Finalizado'), (3, 'Erro'), (4, 'Desconhecido'), (5, 'Reprocessando')], default=0, verbose_name='Status'),
        ),
    ]
