# Generated by Django 3.2.4 on 2021-10-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0006_alter_omrupload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrupload',
            name='processing_log',
            field=models.TextField(blank=True, null=True, verbose_name='Resultado da operação'),
        ),
    ]
