# Generated by Django 4.0.2 on 2022-04-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0009_alter_omrupload_total_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrerror',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em'),
        ),
        migrations.AlterField(
            model_name='omrerror',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='omrstudents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em'),
        ),
        migrations.AlterField(
            model_name='omrstudents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='omrupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em'),
        ),
        migrations.AlterField(
            model_name='omrupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em'),
        ),
    ]
