# Generated by Django 4.0.2 on 2022-06-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0013_alter_omrerror_id_alter_omrstudents_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrerror',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'QRCode não identificado'), (2, 'Marcações não identificadas'), (3, 'Aluno não encontrado'), (4, 'Versão de randomização não encontrada'), (0, 'Outro')], default=0, verbose_name='Categoria'),
        ),
    ]
