# Generated by Django 4.0.2 on 2022-06-20 21:38

from django.db import migrations, models
import fiscallizeon.core.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0014_alter_omrerror_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrupload',
            name='raw_pdf',
            field=models.FileField(blank=True, null=True, storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to='omr/raw_uploads/', verbose_name='Arquivo original'),
        ),
        migrations.AlterField(
            model_name='omrerror',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'QRCode não identificado'), (2, 'Marcações não identificadas'), (3, 'Aplicação ou aluno não encontrado'), (4, 'Versão de randomização não encontrada'), (0, 'Outro')], default=0, verbose_name='Categoria'),
        ),
    ]
