# Generated by Django 4.0.2 on 2022-08-08 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('omr', '0015_omrupload_raw_pdf_alter_omrerror_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrstudents',
            name='checked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omrstudents',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que checou'),
        ),
    ]
