# Generated by Django 4.0.2 on 2022-08-08 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0065_remove_applicationstudentcompetencesperformance_application_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('omr', '0016_omrstudents_checked_omrstudents_checked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOMRStudents',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('successful_questions_count', models.PositiveSmallIntegerField(default=0, verbose_name='Número de respostas contabilizadas')),
                ('scan_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagem do escaneamento')),
                ('checked', models.BooleanField(blank=True, null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('application_student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.applicationstudent', verbose_name='Aluno')),
                ('checked_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que checou')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='omr.omrupload', verbose_name='Upload')),
            ],
            options={
                'verbose_name': 'historical Aluno do upload de gabarito',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
