# Generated by Django 4.0.6 on 2022-10-06 11:31

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import fiscallizeon.core.storage_backends
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0066_alter_application_answer_sheet'),
        ('omr', '0017_historicalomrstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMRCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('template', models.JSONField(verbose_name='JSON de mapeamento')),
                ('marker_image', models.ImageField(blank=True, null=True, storage=fiscallizeon.core.storage_backends.PublicMediaStorage(), upload_to='omr_static/', verbose_name='Imagem de marcador')),
                ('sequential', models.PositiveSmallIntegerField(default=0, verbose_name='Sequencial interno')),
                ('enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('supports_foreign_language', models.BooleanField(default=False, verbose_name='Tem suporte a lingua estrangeira')),
                ('supports_dettached', models.BooleanField(default=False, verbose_name='Tem suporte a modelo avulso')),
            ],
            options={
                'verbose_name': 'Template de gabarito',
                'verbose_name_plural': 'Templates de gabarito',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='omrerror',
            name='application_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.applicationstudent', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='omrerror',
            name='omr_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='omr.omrcategory', verbose_name='Categoria do OMR'),
        ),
        migrations.AddField(
            model_name='omrupload',
            name='omr_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='omr.omrcategory', verbose_name='Categoria de gabarito do upload'),
        ),
    ]
