# Generated by Django 4.0.6 on 2022-10-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0019_omrcategory_data_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='omrcategory',
            options={'ordering': ('sequential',), 'verbose_name': 'Template de gabarito', 'verbose_name_plural': 'Templates de gabarito'},
        ),
    ]
