# Generated by Django 4.0.6 on 2022-10-25 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_responsible_email'),
        ('omr', '0021_remove_omrerror_application_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrerror',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.student', verbose_name='Aluno'),
        ),
    ]
