# Generated by Django 4.0.6 on 2022-12-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0023_omrcategory_eleva_data_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omrcategory',
            name='supports_dettached',
        ),
        migrations.AddField(
            model_name='omrcategory',
            name='dettached_template',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON de mapeamento de matrícula'),
        ),
    ]
