# Generated by Django 4.0.6 on 2022-12-14 21:31

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import fiscallizeon.core.storage_backends
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0072_alter_application_priority'),
        ('omr', '0025_omrcategory_discursive_data_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMRDiscursiveScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('upload_image', models.ImageField(storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to='omr/scans/', verbose_name='Imagem do escaneamento (discursiva)')),
                ('omr_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omr.omrstudents', verbose_name='OMR Student')),
            ],
            options={
                'verbose_name': 'Escaneamento de questão discursiva',
                'verbose_name_plural': 'Escaneamentos de questões discursivas',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OMRDiscursiveError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Questão não encontrada'), (0, 'Outro')], default=0, verbose_name='Categoria')),
                ('is_solved', models.BooleanField(default=False, verbose_name='Reolvido')),
                ('error_image', models.ImageField(storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to='omr/scans/', verbose_name='Imagem do escaneamento')),
                ('application_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.applicationstudent', verbose_name='Aluno')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omr.omrupload', verbose_name='Upload')),
            ],
            options={
                'verbose_name': 'Erro de leitura de questão discursiva',
                'verbose_name_plural': 'Erros de leitura de questões discursivas',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
