# Generated by Django 4.0.6 on 2022-12-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0026_omrdiscursivescan_omrdiscursiveerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrcategory',
            name='discursive_grade_setps',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Número de possibilidades de nota'),
        ),
    ]
