# Generated by Django 4.0.6 on 2022-12-15 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0027_omrcategory_discursive_grade_setps'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrcategory',
            name='is_discursive',
            field=models.BooleanField(default=False, verbose_name='É modelo discursivo?'),
        ),
        migrations.AddField(
            model_name='omrdiscursiveerror',
            name='omr_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='omr.omrcategory', verbose_name='Categoria do OMR'),
        ),
    ]
