# Generated by Django 4.0.6 on 2022-12-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0028_omrcategory_is_discursive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrdiscursiveerror',
            name='version_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Versão da randomização'),
        ),
        migrations.AlterField(
            model_name='omrdiscursiveerror',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Questão não identificada'), (0, 'Outro')], default=0, verbose_name='Categoria'),
        ),
    ]
