# Generated by Django 4.0.6 on 2023-01-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0029_omrdiscursiveerror_version_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrcategory',
            name='is_native',
            field=models.BooleanField(default=True, verbose_name='Modelo fiscallize?'),
        ),
    ]
