# Generated by Django 4.0.6 on 2023-02-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0032_omrcategory_is_native'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrcategory',
            name='column_discursives_count',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Número máximo de questões discussivas por coluna'),
        ),
        migrations.AddField(
            model_name='omrcategory',
            name='column_objectives_count',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Número máximo de questões objetivas por coluna'),
        ),
        migrations.AddField(
            model_name='omrcategory',
            name='is_hybrid',
            field=models.BooleanField(default=False, help_text='Marque se for modelo de objetivas e notas de discursivas', verbose_name='É modelo híbrido?'),
        ),
        migrations.AddField(
            model_name='omrcategory',
            name='max_discursives_count',
            field=models.PositiveSmallIntegerField(default=36, verbose_name='Número máximo de questões discursivas (modelo híbrido)'),
        ),
        migrations.AddField(
            model_name='omrcategory',
            name='max_objectives_count',
            field=models.PositiveSmallIntegerField(default=150, verbose_name='Número máximo de questões objetivas'),
        ),
    ]
