# Generated by Django 4.0.6 on 2023-02-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0035_omrcategory_data_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrcategory',
            name='sequential',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Outro'), (1, 'Fiscallize (objetivas)'), (2, 'ENEM'), (3, 'Rio - 15 questões'), (4, 'Rio - 18 questões'), (5, 'Rio - Mirim'), (6, 'Híbrido - 0.25'), (7, 'Simulado Eleva'), (8, 'Discussiva - 0.25')], default=0, verbose_name='Sequencial interno'),
        ),
    ]
