# Generated by Django 4.0.6 on 2023-02-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0036_alter_omrcategory_sequential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrcategory',
            name='column_discursives_count',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Número máximo de questões discursivas por coluna'),
        ),
        migrations.AlterField(
            model_name='omrcategory',
            name='discursive_grade_setps',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Número de possibilidades de nota discursiva'),
        ),
        migrations.AlterField(
            model_name='omrcategory',
            name='is_discursive',
            field=models.BooleanField(default=False, verbose_name='É modelo discursivo?'),
        ),
    ]
