# Generated by Django 4.0.6 on 2023-04-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0038_alter_omrcategory_sequential'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrupload',
            name='corrected',
            field=models.BooleanField(blank=True, default=False, verbose_name='Marcado como já corrigido'),
        ),
    ]
