# Generated by Django 4.0.6 on 2023-04-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0039_omrupload_corrected'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrupload',
            name='seen',
            field=models.BooleanField(blank=True, default=False, verbose_name='Marcado como já visto'),
        ),
    ]
