# Generated by Django 4.0.6 on 2024-01-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0045_alter_omrcategory_sequential'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalomrstudents',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Aluno do upload de gabarito', 'verbose_name_plural': 'historical Alunos do upload de gabarito'},
        ),
        migrations.AlterField(
            model_name='historicalomrstudents',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
