# Generated by Django 4.0.6 on 2024-02-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0047_alter_historicalomrstudents_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrcategory',
            name='sequential',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Outro'), (1, 'Fiscallize (objetivas)'), (2, 'ENEM'), (3, 'Rio - 15 questões'), (4, 'Rio - 18 questões'), (5, 'Rio - Mirim'), (6, 'Híbrido - 0.25'), (7, 'Simulado Eleva'), (8, 'Discursiva - 0.25'), (9, 'Salta Padrão - 100 Questões'), (10, 'ELIT'), (11, 'Somatório')], default=0, verbose_name='Sequencial interno'),
        ),
    ]
