# Generated by Django 4.0.6 on 2024-03-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0047_alter_omrcategory_sequential'),
        ('omr', '0048_alter_historicalomrstudents_options_and_more'),
    ]

    operations = [
    ]
