# Generated by Django 4.0.6 on 2024-03-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0048_alter_omrcategory_sequential'),
        ('omr', '0049_merge_20240327_1802'),
    ]

    operations = [
    ]
