# Generated by Django 4.0.6 on 2024-03-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0049_merge_20240327_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalomrstudents',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Aluno do upload de gabarito'},
        ),
        migrations.AlterField(
            model_name='historicalomrstudents',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
