# Generated by Django 4.0.6 on 2024-04-05 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0051_alter_historicalomrstudents_options_and_more'),
        ('omr', '0051_alter_omrcategory_sequential'),
    ]

    operations = [
    ]
