# Generated by Django 4.0.6 on 2024-04-05 02:30
import os, json, tempfile, shutil
from django.conf import settings
from django.db import migrations
from fiscallizeon.omr.models import OMRCategory

def create_omr_categories(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0052_merge_20240404_2320'),
    ]

    operations = [
        migrations.RunPython(create_omr_categories, migrations.RunPython.noop),
    ]
