# Generated by Django 4.0.6 on 2024-04-05 02:37
import os, json, tempfile, shutil
from django.conf import settings
from django.db import migrations
from django.core.files.uploadedfile import UploadedFile
from fiscallizeon.omr.models import OMRCategory

def create_hybrid_category(apps, schema_editor):
    #Gabarito híbrido
    omr_marker_path = os.path.join(settings.BASE_DIR, 'fiscallizeon', 'core', 'static', 'omr_marker.jpg')

    template_json = {
        "Options":{
            "Marker":{
                "SheetToMarkerWidthRatio":15
            }
        },
        "QBlocks":{
            "Roll":{
                "gaps":[
                    32,
                    34
                ],
                "orig":[
                    1107,
                    73
                ],
                "qNos":[
                    [
                    [
                        "roll0",
                        "roll1",
                        "roll2",
                        "roll3",
                        "roll4",
                        "roll5",
                        "roll6",
                        "roll7",
                        "roll8",
                        "roll9"
                    ]
                    ]
                ],
                "qType":"QTYPE_ROLL",
                "bigGaps":[
                    0,
                    0
                ]
            },
            "Language":{
                "gaps":[
                    59,
                    35
                ],
                "orig":[
                    1151,
                    511
                ],
                "qNos":[
                    [
                    [
                        "Language"
                    ]
                    ]
                ],
                "qType":"QTYPE_MED",
                "bigGaps":[
                    0,
                    0
                ]
            },
            "MCDBlock1":{
                "gaps":[
                    32,
                    34
                ],
                "orig":[
                    80,
                    1338
                ],
                "qNos":[
                    
                ],
                "qType":"QTYPE_MCQ5",
                "bigGaps":[
                    0,
                    0
                ]
            },
            "MCDBlock2":{
                "gaps":[
                    32,
                    36
                ],
                "orig":[
                    320,
                    1338
                ],
                "qNos":[
                    
                ],
                "qType":"QTYPE_MCQ5",
                "bigGaps":[
                    0,
                    0
                ]
            },
            "MCDBlock3":{
                "gaps":[
                    32,
                    36
                ],
                "orig":[
                    558,
                    1338
                ],
                "qNos":[
                    
                ],
                "qType":"QTYPE_MCQ5",
                "bigGaps":[
                    0,
                    0
                ]
            },
            "MCDBlock4":{
                "gaps":[
                    32,
                    36
                ],
                "orig":[
                    794,
                    1338
                ],
                "qNos":[
                    
                ],
                "qType":"QTYPE_MCQ5",
                "bigGaps":[
                    0,
                    0
                ]
            },
            "MCDBlock5":{
                "gaps":[
                    32,
                    36
                ],
                "orig":[
                    1030,
                    1338
                ],
                "qNos":[
                    
                ],
                "qType":"QTYPE_MCQ5",
                "bigGaps":[
                    0,
                    0
                ]
            },
            "MCDBlock6":{
                "gaps":[
                    32,
                    36
                ],
                "orig":[
                    1268,
                    1338
                ],
                "qNos":[
                    
                ],
                "qType":"QTYPE_MCQ5",
                "bigGaps":[
                    0,
                    0
                ]
            },
            "MCQBlock1":{
                "gaps":[
                    32,
                    34
                ],
                "orig":[
                    80,
                    657
                ],
                "qNos":[
                    
                ],
                "qType":"QTYPE_MCQ5",
                "bigGaps":[
                    0,
                    0
                ]
            },
            "MCQBlock2":{
                "gaps":[
                    32,
                    34
                ],
                "orig":[
                    320,
                    657
                ],
                "qNos":[
                    
                ],
                "qType":"QTYPE_MCQ5",
                "bigGaps":[
                    0,
                    0
                ]
            },
            "MCQBlock3":{
                "gaps":[
                    32,
                    34
                ],
                "orig":[
                    558,
                    657
                ],
                "qNos":[
                    
                ],
                "qType":"QTYPE_MCQ5",
                "bigGaps":[
                    0,
                    0
                ]
            },
            "MCQBlock4":{
                "gaps":[
                    32,
                    34
                ],
                "orig":[
                    794,
                    657
                ],
                "qNos":[
                    
                ],
                "qType":"QTYPE_MCQ5",
                "bigGaps":[
                    0,
                    0
                ]
            },
            "MCQBlock5":{
                "gaps":[
                    32,
                    34
                ],
                "orig":[
                    1030,
                    657
                ],
                "qNos":[
                    
                ],
                "qType":"QTYPE_MCQ5",
                "bigGaps":[
                    0,
                    0
                ]
            },
            "MCQBlock6":{
                "gaps":[
                    32,
                    34
                ],
                "orig":[
                    1268,
                    657
                ],
                "qNos":[
                    
                ],
                "qType":"QTYPE_MCQ5",
                "bigGaps":[
                    0,
                    0
                ]
            }
        },
        "Singles":[
            "Language"
        ],
        "Dimensions":[
            1431,
            1806
        ],
        "Concatenations":{
            "Roll":[
                "roll0",
                "roll1",
                "roll2",
                "roll3",
                "roll4",
                "roll5",
                "roll6",
                "roll7",
                "roll8",
                "roll9"
            ]
        },
        "BubbleDimensions":[
            21,
            21
        ]
    }

    enrollment_json = {
        "Options":{
            "Marker":{
                "SheetToMarkerWidthRatio":15
            }
        },
        "QBlocks":{
            "Roll":{
                "gaps":[
                    55,
                    54
                ],
                "orig":[
                    1862,
                    120
                ],
                "qNos":[
                    [
                    [
                        "roll0",
                        "roll1",
                        "roll2",
                        "roll3",
                        "roll4",
                        "roll5",
                        "roll6",
                        "roll7",
                        "roll8",
                        "roll9"
                    ]
                    ]
                ],
                "qType":"QTYPE_ROLL",
                "bigGaps":[
                    0,
                    0
                ]
            }
        },
        "Singles":[
            
        ],
        "Dimensions":[
            2431,
            2806
        ],
        "Concatenations":{
            "Roll":[
                "roll0",
                "roll1",
                "roll2",
                "roll3",
                "roll4",
                "roll5",
                "roll6",
                "roll7",
                "roll8",
                "roll9"
            ]
        },
        "BubbleDimensions":[
            31,
            31
        ]
    }

    with open(omr_marker_path, 'rb') as marker_file:
        marker_tmp = tempfile.NamedTemporaryFile(delete=False)
        shutil.copyfileobj(marker_file, marker_tmp)
        marker_tmp.flush()

    OMRCategory.objects.update_or_create(
        sequential=OMRCategory.HYBRID_025,
        defaults={
            'name': 'Híbrido (0.25)',
            "template": template_json,
            "dettached_template": enrollment_json,
            "marker_image": marker_tmp.name,
            "is_hybrid": True,
            "discursive_grade_setps": 5,
            "max_objectives_count": 96,
            "column_objectives_count": 16,
            "max_discursives_count": 72,
            "column_discursives_count": 12,
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0053_create_omrcategory_data'),
    ]

    operations = [
        migrations.RunPython(create_hybrid_category, migrations.RunPython.noop),
    ]
