# Generated by Django 4.0.6 on 2024-04-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0052_alter_omrcategory_options_and_more'),
        ('omr', '0054_create_hybrid_category'),
    ]

    operations = [
    ]
