# Generated by Django 4.0.6 on 2024-04-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0055_merge_20240405_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrerror',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'QRCode não identificado'), (2, 'Marcações não identificadas'), (3, 'Aplicação ou aluno não encontrado'), (4, 'Versão de randomização não encontrada'), (5, 'Aplicação ou caderno não encontrado(s)'), (0, 'Outro')], default=0, verbose_name='Categoria'),
        ),
    ]
