# Generated by Django 4.0.6 on 2024-04-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0056_omrdiscursivescan_image_hash_alter_omrerror_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrdiscursivescan',
            name='image_hash',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Hash MD5 do arquivo'),
        ),
    ]
