# Generated by Django 4.0.6 on 2024-05-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0056_alter_omrerror_category'),
        ('omr', '0058_omrerror_randomization_version'),
    ]

    operations = [
    ]
