# Generated by Django 4.0.6 on 2024-07-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0060_alter_omrcategory_sequential'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrupload',
            name='gamma_option',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Gamma aplicado'),
        ),
        migrations.AddField(
            model_name='omrupload',
            name='ignore_qr_codes',
            field=models.BooleanField(default=False, verbose_name='Ignorar QR codes'),
        ),
    ]
