# Generated by Django 4.0.6 on 2024-07-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0061_omrupload_gamma_option_omrupload_ignore_qr_codes'),
        ('omr', '0063_alter_omrcategory_sequential'),
    ]

    operations = [
    ]
