# Generated by Django 4.0.6 on 2024-08-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0065_alter_omrcategory_sequential'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrdiscursivescan',
            name='is_essay',
            field=models.BooleanField(default=False, verbose_name='É redação'),
        ),
    ]
