# Generated by Django 4.0.6 on 2024-12-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0104_alter_application_student_stats_permission_date_and_more'),
        ('omr', '0067_alter_omrcategory_sequential'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrupload',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.application', verbose_name='Aplicação associada'),
        ),
    ]
