# Generated by Django 4.0.6 on 2025-01-11 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0104_alter_application_student_stats_permission_date_and_more'),
        ('omr', '0068_omrupload_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrerror',
            name='application',
            field=models.ForeignKey(blank=True, help_text='Considera essa aplicação na hora de ler os gabaritos (a aplicação do aluno será atualizada após o upload)', null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.application', verbose_name='Aplicação'),
        ),
    ]
