# Generated by Django 4.2.19 on 2025-03-31 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0069_alter_omrerror_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='omrcategory',
            options={'ordering': ('sequential',), 'permissions': (('export_offset_answer_sheet', 'Pode exportar folha de respostas offset'), ('export_offset_answer_sheet_schoolclass', 'Pode exportar folha de respostas offset de turma')), 'verbose_name': 'Template de gabarito', 'verbose_name_plural': 'Templates de gabarito'},
        ),
    ]
