# Generated by Django 4.2.19 on 2025-04-01 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0031_schoolclass_integration_token'),
        ('omr', '0070_alter_omrcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='omrcategory',
            options={'ordering': ('sequential',), 'permissions': (('export_offset_answer_sheet', 'Pode exportar folha de respostas offset'), ('export_offset_answer_sheet_schoolclass', 'Pode exportar folha de respostas offset não identificaa')), 'verbose_name': 'Template de gabarito', 'verbose_name_plural': 'Templates de gabarito'},
        ),
        migrations.AddField(
            model_name='omrupload',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.schoolclass', verbose_name='Turma associada'),
        ),
    ]
