# Generated by Django 4.2.19 on 2025-04-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0071_alter_omrcategory_options_omrupload_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrcategory',
            name='sequential',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Outro'), (1, 'Fiscallize (objetivas)'), (2, 'ENEM'), (3, 'Rio - 15 questões'), (4, 'Rio - 18 questões'), (5, 'Rio - Mirim'), (6, 'Híbrido - 0.25'), (7, 'Simulado Eleva'), (8, 'Discursiva - 0.25'), (9, 'Salta Padrão - 100 Questões'), (10, 'ELIT'), (11, 'Somatório'), (12, 'Offset'), (13, 'EFAI'), (14, 'Modelo reduzido'), (15, 'Modelo redação'), (16, 'SESI'), (17, 'Offset não identificado')], default=0, verbose_name='Sequencial interno'),
        ),
    ]
