# Generated by Django 4.2.19 on 2025-06-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0072_alter_omrcategory_sequential'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrerror',
            name='is_associated_file',
            field=models.BooleanField(default=False, verbose_name='É um arquivo associado ao upload'),
        ),
    ]
