# Generated by Django 4.2.19 on 2025-06-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0072_alter_omrcategory_sequential'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrupload',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Marcado como deletado'),
        ),
    ]
