# Generated by Django 4.2.19 on 2025-07-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0073_omrerror_is_associated_file'),
        ('omr', '0074_remove_omrupload_is_deleted_omrupload_deleted_at_and_more'),
    ]

    operations = [
    ]
