# Generated by Django 3.0.7 on 2020-06-13 17:48

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('grade', models.CharField(max_length=50, verbose_name='Série')),
                ('coordination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_classes', to='clients.SchoolCoordination', verbose_name='Coordenação responsável')),
                ('students', models.ManyToManyField(help_text='Selecione acima os alunos que fazem parte dessa turma', related_name='classes', to='students.Student', verbose_name='Alunos dessa turma')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
