# Generated by Django 3.0.7 on 2021-01-08 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20210108_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Grade', verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='grade_old',
            field=models.CharField(max_length=50, verbose_name='Série antiga'),
        ),
    ]
