# Generated by Django 3.0.7 on 2021-01-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20210108_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='class_type',
            field=models.PositiveSmallIntegerField(choices=[('Turma Regular', 0), ('Turma de Sondagem', 1)], default=0, verbose_name='Tipo de Turma'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da aplicação'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='end',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim previsto da aplicação'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='Início previsto da aplicação'),
        ),
    ]
