# Generated by Django 3.0.7 on 2021-01-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20210126_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='class_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Turma Regular'), (1, 'Turma de Sondagem')], default=0, verbose_name='Tipo de Turma'),
        ),
    ]
