# Generated by Django 3.2.3 on 2021-09-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20210126_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='school_year',
            field=models.SmallIntegerField(default='2021', blank=True, verbose_name='Ano letivo da turma'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='temporary_class',
            field=models.BooleanField(default=False, verbose_name='Turma temporária ou rotativa'),
        ),
    ]
