# Generated by Django 3.2.4 on 2021-10-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20210929_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='temporary_class',
            field=models.BooleanField(default=False, help_text='Marque esta opção caso essa turma não seja regular.', verbose_name='Turma temporária ou rotativa'),
        ),
    ]
