# Generated by Django 3.2.4 on 2022-01-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_schoolclass_temporary_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='school_year',
            field=models.SmallIntegerField(blank=True, default='2022', verbose_name='Ano letivo da turma'),
        ),
    ]
