# Generated by Django 4.0.2 on 2022-04-23 15:44

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_client_id_erp'),
        ('classes', '0010_schoolclass_id_erp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('id_erp', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID ERP')),
                ('stage_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'N')], default=1, null=True, verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Etapas',
                'verbose_name_plural': 'Etapas',
                'ordering': ['created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='turn',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Manhã'), (1, 'Tarde'), (2, 'Noite')], null=True, verbose_name='Turno'),
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('id_erp', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID ERP')),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Tipo de Curso',
                'verbose_name_plural': 'Tipo de Curso',
                'ordering': ['created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.coursetype', verbose_name='Tipo de Curso'),
        ),
    ]
