# Generated by Django 4.0.2 on 2022-04-26 23:08

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_client_id_erp'),
        ('classes', '0011_stage_schoolclass_turn_coursetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='course_type',
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Cliente'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('id_erp', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID ERP')),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Cliente')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.coursetype', verbose_name='Tipo de Curso')),
            ],
            options={
                'verbose_name': 'Cursos',
                'verbose_name_plural': 'Cursos',
                'ordering': ['created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.course', verbose_name='Curso'),
        ),
    ]
