# Generated by Django 4.0.4 on 2022-04-28 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_remove_schoolclass_course_type_and_more'),
        ('classes', '0014_alter_grade_id_alter_schoolclass_id'),
    ]

    operations = [
    ]
