# Generated by Django 4.0.6 on 2022-10-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_alter_course_created_at_alter_coursetype_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='level',
            field=models.PositiveIntegerField(choices=[(1, 'Ensino Fundamental 1'), (2, 'Ensino Fundamental 2'), (0, 'Ensino Médio')], db_index=True, verbose_name='Ensino'),
        ),
    ]
