# Generated by Django 4.0.6 on 2023-01-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_alter_schoolclass_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='school_year',
            field=models.SmallIntegerField(blank=True, db_index=True, default='2023', verbose_name='Ano letivo da turma'),
        ),
    ]
