# Generated by Django 4.0.6 on 2023-04-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0019_alter_schoolclass_school_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['level']},
        ),
    ]
