# Generated by Django 4.0.6 on 2023-09-10 14:34

from django.db import migrations, models
import fiscallizeon.core.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0020_alter_grade_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=fiscallizeon.core.storage_backends.PublicMediaStorage(), upload_to='classes/clients/logos/', verbose_name='Logo da escola'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
    ]
