# Generated by Django 4.0.6 on 2024-01-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0022_alter_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='school_year',
            field=models.SmallIntegerField(blank=True, db_index=True, default='2024', verbose_name='Ano letivo da turma'),
        ),
    ]
