# Generated by Django 4.0.6 on 2024-01-20 02:23
from django.db import migrations, models

from fiscallizeon.classes.models import SchoolClass
from django.db.models import Q, Subquery, Count, OuterRef

def remove_duplicate_classes(apps, schema_editor):
    pass
    # classes = SchoolClass.objects.annotate(
    #     count=Subquery(SchoolClass.objects.filter(
    #             name=OuterRef('name'),
    #             school_year=OuterRef('school_year'),
    #             coordination=OuterRef('coordination')
    #         ).exclude(id=OuterRef('id')).values('name', 'school_year', 'coordination').annotate(
    #             count=Count('id')
    #         ).values('count'))
    # ).filter(
    #     count__gt=0
    # )
    # for index, c in enumerate(classes):
    #     c.name = f'{c.name} {index}'
    #     c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0023_alter_schoolclass_school_year'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_classes, reverse_code=migrations.RunPython.noop),
    ]
