# Generated by Django 4.0.6 on 2024-01-20 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0024_remove_duplicate_classes_name_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('name', 'school_year', 'coordination')},
        ),
    ]
