# Generated by Django 4.0.6 on 2024-03-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0025_alter_schoolclass_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetype',
            options={'ordering': ['created_at'], 'verbose_name': 'Tipo de Curso', 'verbose_name_plural': 'Tipos de Cursos'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='grade',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Index da grade para listagem'),
        ),
    ]
