# Generated by Django 4.0.6 on 2024-03-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0026_alter_coursetype_options_alter_grade_options_and_more'),
        ('classes', '0026_alter_schoolclass_name'),
    ]

    operations = [
    ]
