# Generated by Django 4.0.6 on 2024-07-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0027_merge_20240325_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='is_itinerary',
            field=models.BooleanField(default=False, verbose_name='É turma itinerária'),
        ),
    ]
