# Generated by Django 4.0.6 on 2024-08-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0028_schoolclass_is_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='is_itinerary',
            field=models.BooleanField(default=False, help_text='Marque esta opção caso essa turma seja uma turma itinerária.', verbose_name='É turma itinerária'),
        ),
    ]
