# Generated by Django 4.0.6 on 2025-01-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0029_alter_schoolclass_is_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='school_year',
            field=models.SmallIntegerField(blank=True, db_index=True, default='2025', verbose_name='Ano letivo da turma'),
        ),
    ]
