# Generated by Django 4.0.6 on 2025-02-07 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0022_alter_integrationtoken_options'),
        ('classes', '0030_alter_schoolclass_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='integration_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_classes', to='integrations.integrationtoken', verbose_name='Token utilizado para integração'),
        ),
    ]
