# Generated by Django 3.2.4 on 2022-01-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integration',
            options={'verbose_name': 'Integração', 'verbose_name_plural': 'Integrações'},
        ),
        migrations.AlterField(
            model_name='integration',
            name='erp',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'TOTVS'), (1, 'Active Soft')], default=0, verbose_name='ERP'),
        ),
    ]
