# Generated by Django 3.2.4 on 2022-01-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20220105_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='erp',
            field=models.PositiveSmallIntegerField(choices=[(0, 'TOTVS'), (1, 'Active Soft')], default=0, verbose_name='ERP'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='token',
            field=models.TextField(blank=True, verbose_name='Token de acesso'),
        ),
    ]
