# Generated by Django 3.2.4 on 2022-01-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20220105_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='erp',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Activesoft'), (0, 'Totvs')], default=1, verbose_name='ERP'),
        ),
    ]
