# Generated by Django 3.2.4 on 2022-01-20 14:44

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_alter_subject_options'),
        ('clients', '0029_client_has_integration'),
        ('integrations', '0004_alter_integration_erp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='erp',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Activesoft')], default=1, verbose_name='ERP'),
        ),
        migrations.CreateModel(
            name='SubjectCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Cliente')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Código de disciplina',
                'verbose_name_plural': 'Códigos das disciplinas',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
