# Generated by Django 3.2.4 on 2022-02-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_integration_erp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='erp',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Activesoft')], default=1, verbose_name='ERP'),
        ),
    ]
