# Generated by Django 3.2.4 on 2022-01-20 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_client_has_integration'),
        ('subjects', '0010_alter_subject_options'),
        ('integrations', '0006_subjectcode_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcode',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='subjectcode',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Disciplina'),
        ),
    ]
