# Generated by Django 3.2.4 on 2022-01-20 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_alter_subject_options'),
        ('integrations', '0007_auto_20220120_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcode',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='subjects.subject', verbose_name='Disciplina'),
        ),
    ]
