# Generated by Django 4.0.2 on 2022-04-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_alter_integration_erp'),
        ('integrations', '0008_alter_subjectcode_subject'),
    ]

    operations = [
    ]
