# Generated by Django 4.0.4 on 2022-04-28 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_alter_integration_id'),
        ('integrations', '0009_merge_20220424_1846'),
    ]

    operations = [
    ]
