# Generated by Django 4.0.4 on 2022-04-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_merge_20220428_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em'),
        ),
    ]
