# Generated by Django 4.0.6 on 2022-11-12 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0011_alter_subjectcode_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperProfIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('login', models.CharField(max_length=255, verbose_name='Usuário do super professor')),
                ('password', models.CharField(max_length=50, verbose_name='Senha do super professor')),
                ('authorization_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ultimo código de autorização')),
                ('authorization_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Data em que o a autorização expira')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='Ultimo token de acesso')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Data em que o token expira')),
                ('sso_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ultimo SSO token')),
                ('sso_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Data em que o SSO token expira')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
