# Generated by Django 4.0.6 on 2023-12-11 17:31

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_student_school_name_student_state'),
        ('exams', '0140_merge_20231203_1704'),
        ('integrations', '0012_superprofintegration'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesMigrationProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(max_length=8, verbose_name='Código do comprovante de migração')),
                ('migration_json', models.JSONField(verbose_name='Dados aidiconais da migração')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes_migration_proofs', to='exams.exam', verbose_name='Prova')),
                ('students', models.ManyToManyField(to='students.student', verbose_name='Alunos')),
            ],
            options={
                'verbose_name': 'Comprovante de migração de notas',
                'verbose_name_plural': 'Comprovantes de migração de notas',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
