# Generated by Django 4.0.6 on 2023-12-21 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0013_notesmigrationproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesmigrationproof',
            name='created_by',
            field=models.ForeignKey(default='14b6d16c-5e36-49f0-99cf-8cf7e058a847', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
            preserve_default=False,
        ),
    ]
