# Generated by Django 4.0.6 on 2024-03-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_notesmigrationproof_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='erp',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Activesoft'), (2, 'Ischolar')], default=1, verbose_name='ERP'),
        ),
    ]
