# Generated by Django 4.0.6 on 2024-03-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_alter_integration_erp'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='school_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código da escola'),
        ),
    ]
