# Generated by Django 4.0.6 on 2024-09-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_integration_school_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='erp',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Activesoft'), (2, 'Ischolar'), (3, 'AthenaWeb')], default=1, verbose_name='ERP'),
        ),
    ]
