# Generated by Django 4.0.6 on 2024-11-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0017_alter_integration_erp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='erp',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Activesoft'), (2, 'Ischolar'), (3, 'AthenaWeb'), (4, 'Sophia')], default=1, verbose_name='ERP'),
        ),
    ]
