# Generated by Django 4.2.18 on 2025-02-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0017_alter_integration_erp'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='token_expires_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de expiração'),
        ),
    ]
