# Generated by Django 4.0.6 on 2025-01-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_integrationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='token',
            field=models.TextField(blank=True, default='', verbose_name='Token de acesso'),
        ),
    ]
