# Generated by Django 4.0.6 on 2025-01-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_alter_integration_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='token',
            field=models.TextField(blank=True, null=True, verbose_name='Token de acesso'),
        ),
    ]
