# Generated by Django 4.0.6 on 2025-02-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0020_alter_integration_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationtoken',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data em que expira'),
        ),
        migrations.AddField(
            model_name='integrationtoken',
            name='name',
            field=models.CharField(blank=True, default='Token padrão', max_length=70, verbose_name='Identificador'),
        ),
    ]
