# Generated by Django 4.0.6 on 2025-02-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0021_integrationtoken_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationtoken',
            options={'ordering': ('created_at',), 'verbose_name': 'Tokens de integração', 'verbose_name_plural': 'Tokens de integraçãos'},
        ),
    ]
