# Generated by Django 4.0.6 on 2025-02-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_alter_integration_erp'),
        ('integrations', '0022_alter_integrationtoken_options'),
    ]

    operations = [
    ]
