# Generated by Django 4.2.18 on 2025-02-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_alter_integration_erp_topiccode_competencecode_and_more'),
        ('integrations', '0023_merge_20250218_1058'),
    ]

    operations = [
    ]
