# Generated by Django 4.2.18 on 2025-02-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_integration_token_expires_date'),
        ('integrations', '0023_merge_20250218_1058'),
    ]

    operations = [
    ]
