# Generated by Django 4.2.18 on 2025-02-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0025_alter_integration_erp'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário de autenticação'),
        ),
    ]
