# Generated by Django 4.2.19 on 2025-03-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0024_merge_20250220_1538'),
        ('integrations', '0026_integration_username'),
    ]

    operations = [
    ]
