# Generated by Django 4.2.19 on 2025-03-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0027_merge_20250315_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='token_expires_date',
        ),
    ]
