# Generated by Django 4.0.6 on 2023-05-15 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0016_auto_20230327_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do responsável')),
                ('hash', models.CharField(blank=True, max_length=200, verbose_name='Hash para criação do usuário')),
                ('hash_validate', models.DateTimeField(blank=True, verbose_name='Validade do hash')),
                ('students', models.ManyToManyField(blank=True, to='students.student', verbose_name='Filhos')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
