# Generated by Django 4.0.6 on 2023-05-31 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_alter_parent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Responsál', 'verbose_name_plural': 'Responsáveis'},
        ),
    ]
