# Generated by Django 3.0.7 on 2020-06-13 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do cliente')),
                ('social_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social')),
                ('type_client', models.SmallIntegerField(choices=[(1, 'Escola'), (2, 'Outro')], verbose_name='Tipo de cliente')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ (somente números)')),
                ('status', models.SmallIntegerField(choices=[(1, 'Ativado'), (2, 'Desativado')], default=1, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SchoolCoordination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da coordenação')),
                ('responsible_name', models.CharField(max_length=255, verbose_name='Nome do responsável')),
                ('responsible_email', models.EmailField(max_length=255, verbose_name='Email do responsável')),
                ('responsible_phone', models.CharField(max_length=15, verbose_name='Telefone do responsável')),
                ('high_school', models.BooleanField(default=True, verbose_name='Responsável pelo ensino médio?')),
                ('elementary_school', models.BooleanField(default=True, verbose_name='Responsável pelo ensino fundamental?')),
                ('can_see_all', models.BooleanField(default=True, verbose_name='Pode ver tudo?')),
                ('can_see_finances', models.BooleanField(default=False, verbose_name='Pode ver o financeiro?')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinations', to='clients.Client', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Coordenação',
                'verbose_name_plural': 'Coordenações',
                'ordering': ['created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CoordinationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('coordination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='clients.SchoolCoordination', verbose_name='Membro da coordenação')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coordination_member', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do membro da coordenação')),
            ],
            options={
                'verbose_name': 'Membro da coordenação',
                'verbose_name_plural': 'Membros da coordenação',
                'ordering': ['created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
