# Generated by Django 3.0.7 on 2020-12-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/logos/', verbose_name='Logo da escola'),
        ),
    ]
