# Generated by Django 3.0.7 on 2021-02-12 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import fiscallizeon.core.storage_backends
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_client_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=fiscallizeon.core.storage_backends.PublicMediaStorage(), upload_to='clients/logos/', verbose_name='Logo da escola'),
        ),
        migrations.AlterField(
            model_name='coordinationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordination_member', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do membro da coordenação'),
        ),
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Unidade')),
                ('unity_type', models.SmallIntegerField(choices=[(0, 'Matriz'), (1, 'Filial'), (2, 'Outro')], default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unities', to='clients.Client', verbose_name='Escola')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='schoolcoordination',
            name='unity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Unity', verbose_name='Unidade Escolar'),
        ),
    ]
