# Generated by Django 3.0.7 on 2021-01-12 17:57

from django.db import migrations

def create_unities(apps, schema_editor):
    pass
    # Client = apps.get_model('clients', 'Client')
    # Unity = apps.get_model('clients', 'Unity')

    # for client in Client.objects.all():
    #     unity, _ = Unity.objects.get_or_create(
    #         client=client,
    #         name="Unidade Principal",
    #     )

    #     client.coordinations.update(
    #         unity=unity
    #     )

class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210212_1437'),
    ]

    operations = [
        migrations.RunPython(create_unities, reverse_code=migrations.RunPython.noop),
    ]