# Generated by Django 3.0.7 on 2021-02-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_data_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolcoordination',
            name='client',
        ),
    ]
