# Generated by Django 3.0.7 on 2021-02-12 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_schoolcoordination_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcoordination',
            name='unity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinations', to='clients.Unity', verbose_name='Unidade Escolar'),
        ),
    ]
