# Generated by Django 3.0.7 on 2021-02-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_merge_20210221_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unity',
            options={'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
    ]
