# Generated by Django 3.0.7 on 2021-03-11 18:06
from datetime import timedelta

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20210225_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='unity',
            name='diff_time',
            field=models.DurationField(default=timedelta(seconds=0), verbose_name='Diferença de timezone'),
        ),
    ]
