# Generated by Django 3.0.7 on 2021-03-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_unity_diff_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unity',
            name='diff_time',
        ),
        migrations.AddField(
            model_name='unity',
            name='timezone',
            field=models.CharField(default='America/Recife', max_length=255, verbose_name='Qual timezone?'),
        ),
    ]
