# Generated by Django 3.0.7 on 2021-04-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20210311_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinationmember',
            name='is_coordinator',
            field=models.BooleanField(default=False, verbose_name='É coordenador'),
        ),
        migrations.AddField(
            model_name='coordinationmember',
            name='is_pedagogic_reviewer',
            field=models.BooleanField(default=False, verbose_name='É revisor pedagógico'),
        ),
        migrations.AddField(
            model_name='coordinationmember',
            name='is_reviewer',
            field=models.BooleanField(default=False, verbose_name='É revisor'),
        ),
    ]
