# Generated by Django 3.0.7 on 2021-01-12 17:57

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20210401_1719'),
    ]

    operations = [

    ]
