# Generated by Django 3.0.7 on 2021-04-03 19:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0012_update_members'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coordinationmember',
            unique_together={('coordination', 'user')},
        ),
    ]
