# Generated by Django 3.0.7 on 2021-04-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20210403_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='correction_by_subject',
            field=models.BooleanField(default=False, verbose_name='Correção de provas por disciplina'),
        ),
    ]
