# Generated by Django 3.0.7 on 2021-04-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_client_correction_by_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='correction_by_subject',
        ),
    ]
