# Generated by Django 3.0.7 on 2021-05-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_remove_client_correction_by_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='can_audio_receive',
            field=models.BooleanField(default=False, verbose_name='Pode ouvir o audio do aluno'),
        ),
    ]
