# Generated by Django 3.2.3 on 2021-07-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_client_can_audio_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_omr',
            field=models.BooleanField(default=False, verbose_name='Tem gabarito'),
        ),
    ]
