# Generated by Django 3.2.3 on 2021-07-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_client_has_omr'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_dashboard',
            field=models.BooleanField(default=False, verbose_name='Tem acesso aos dashboards'),
        ),
    ]
