# Generated by Django 3.2.4 on 2021-08-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_client_has_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_public_questions',
            field=models.BooleanField(default=False, verbose_name='Tem acesso as questões públicas'),
        ),
    ]
