# Generated by Django 3.2.4 on 2021-08-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_client_has_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_diagramation',
            field=models.BooleanField(default=False, verbose_name='Tem acesso ao sistema de solicitação de diagramação'),
        ),
    ]
