# Generated by Django 3.2.4 on 2021-08-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_client_has_diagramation'),
        ('clients', '0019_client_has_public_questions'),
    ]

    operations = [
    ]
