# Generated by Django 3.2.4 on 2021-11-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_merge_20210821_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_template',
            field=models.BooleanField(default=False, verbose_name='Tem acesso a criação de gabarito avulso'),
        ),
    ]
