# Generated by Django 3.2.4 on 2021-12-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_merge_20210821_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='show_previews_template_student',
            field=models.BooleanField(default=False, verbose_name='Tem acesso ao gabarito prévio'),
        ),
    ]
