# Generated by Django 3.2.4 on 2021-12-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_merge_20210821_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_backend',
            field=models.UUIDField(blank=True, null=True, verbose_name='Identificador no fiscallize presenial'),
        ),
    ]
