# Generated by Django 3.2.4 on 2021-12-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_client_has_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='has_distribution',
            field=models.BooleanField(default=False, verbose_name='Tem acesso ao sistema de ensalamento'),
        ),
    ]
