# Generated by Django 3.2.4 on 2021-12-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_client_show_previews_template_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='show_previews_template_student',
            field=models.BooleanField(default=True, verbose_name='Tem acesso ao gabarito prévio'),
        ),
    ]
