# Generated by Django 3.2.4 on 2021-12-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_client_has_template'),
        ('clients', '0023_alter_client_show_previews_template_student'),
    ]

    operations = [
    ]
