# Generated by Django 3.2.4 on 2021-12-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_merge_20211222_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_exam_elaboration',
            field=models.BooleanField(default=True, verbose_name='Tem acesso a elaboração de prova'),
        ),
    ]
