# Generated by Django 3.2.4 on 2021-12-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_client_has_exam_elaboration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='has_exam_elaboration',
            field=models.BooleanField(default=False, verbose_name='Tem acesso a elaboração de prova'),
        ),
    ]
