# Generated by Django 3.2.4 on 2021-12-29 20:26

from django.db import migrations, models
import fiscallizeon.core.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_client_has_exam_elaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='orientations_candidates_file',
            field=models.FileField(blank=True, null=True, storage=fiscallizeon.core.storage_backends.PublicMediaStorage(), upload_to='clients/orientations/', verbose_name='Arquivo de orientações para candidatos'),
        ),
        migrations.AlterField(
            model_name='client',
            name='has_exam_elaboration',
            field=models.BooleanField(default=False, verbose_name='Tem acesso a elaboração de prova'),
        ),
    ]
