# Generated by Django 3.2.4 on 2022-01-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_alter_client_has_distribution'),
        ('clients', '0026_auto_20211229_1726'),
    ]

    operations = [
    ]
