# Generated by Django 3.2.4 on 2022-01-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_auto_20211229_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_erp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID ERP'),
        ),
    ]
