# Generated by Django 3.2.4 on 2022-01-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_client_id_backend'),
        ('clients', '0028_merge_20220106_1847'),
    ]

    operations = [
    ]
