# Generated by Django 3.2.4 on 2022-01-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_auto_20220106_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_integration',
            field=models.BooleanField(default=False, verbose_name='Tem acesso a integrações'),
        ),
    ]
