# Generated by Django 3.2.4 on 2022-01-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_merge_0021_client_id_backend_0028_merge_20220106_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_study_meterial',
            field=models.BooleanField(default=False, verbose_name='Tem acesso a material de estudos'),
        ),
    ]
