# Generated by Django 3.2.4 on 2022-01-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_client_has_study_meterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='has_study_meterial',
            new_name='has_study_material',
        ),
    ]
