# Generated by Django 3.2.4 on 2022-02-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_rename_has_study_meterial_client_has_study_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_wrongs',
            field=models.BooleanField(default=False, verbose_name='Tem acesso ao sistema de erratas'),
        ),
    ]
