# Generated by Django 3.2.4 on 2022-02-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_client_has_integration'),
        ('clients', '0031_rename_has_study_meterial_client_has_study_material'),
    ]

    operations = [
    ]
