# Generated by Django 3.2.4 on 2022-02-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0032_client_has_wrongs'),
        ('clients', '0032_merge_20220202_1532'),
    ]

    operations = [
    ]
