# Generated by Django 4.0.2 on 2022-03-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_merge_0032_client_has_wrongs_0032_merge_20220202_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, help_text='Código que será inserido no início do usuário do aluno no momento do cadastro', max_length=255, null=True, verbose_name='Código do cliente'),
        ),
    ]
