# Generated by Django 4.0.2 on 2022-03-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0034_client_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, help_text='Código que será inserido no início do usuário do aluno no momento do cadastro', max_length=255, null=True, unique=True, verbose_name='Código do cliente'),
        ),
    ]
