# Generated by Django 4.0.2 on 2022-03-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_alter_client_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='teachers_can_elaborate_exam',
            field=models.BooleanField(default=False, verbose_name='Os professores podem elaborar atividade de casa'),
        ),
    ]
