# Generated by Django 4.0.2 on 2022-04-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_alter_client_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_erp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID ERP'),
        ),
    ]
