# Generated by Django 4.0.4 on 2022-04-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_client_teachers_can_elaborate_exam'),
        ('clients', '0038_alter_client_id_alter_coordinationmember_id_and_more'),
    ]

    operations = [
    ]
