# Generated by Django 4.0.4 on 2022-04-28 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_client_id_erp'),
        ('clients', '0040_alter_client_id_alter_coordinationmember_id_and_more'),
    ]

    operations = [
    ]
