# Generated by Django 4.0.2 on 2022-06-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0041_merge_20220428_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='allow_student_notifications',
            field=models.BooleanField(default=False, verbose_name='Permitir notificações para alunos'),
        ),
    ]
