# Generated by Django 4.0.2 on 2022-06-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0042_client_allow_student_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='disable_stripped_answer_sheet',
            field=models.BooleanField(default=False, help_text='Marque esta opção se o cliente se declarar INCAPAZ de ajustar o contraste de uma impressora comum.', verbose_name='Desativar tabela zebrada na folha de respostas'),
        ),
    ]
