# Generated by Django 4.0.2 on 2022-07-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0043_client_disable_stripped_answer_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='use_only_own_subjects',
            field=models.BooleanField(default=False, verbose_name='Utilizar apenas disciplinas próprias cadastradas no sistema'),
        ),
    ]
