# Generated by Django 4.0.2 on 2022-08-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0045_examprintconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examprintconfig',
            name='header_format',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Completo'), (0, 'Apenas o nome do aluno')], default=1, verbose_name='formato do cabeçalho'),
        ),
    ]
