# Generated by Django 4.0.2 on 2022-08-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0046_alter_examprintconfig_header_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examprintconfig',
            name='print_alternatives_indicator',
        ),
        migrations.RemoveField(
            model_name='examprintconfig',
            name='print_knowledge_areas_name',
        ),
        migrations.AddField(
            model_name='examprintconfig',
            name='hide_alternatives_indicator',
            field=models.BooleanField(default=False, help_text='Designa se o caderno deve ocultar o indicador das alternativas.', verbose_name='ocultar indicador das alternativas?'),
        ),
        migrations.AddField(
            model_name='examprintconfig',
            name='hide_knowledge_areas_name',
            field=models.BooleanField(default=False, help_text='Designa se o caderno deve ocultar o nome das áreas de conhecimento.', verbose_name='ocultar nome das áreas de conhecimento?'),
        ),
    ]
