# Generated by Django 4.0.2 on 2022-08-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0048_clientteacherobligationconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientteacherobligationconfiguration',
            name='pedagogical_data',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, o professor será obrigado a selecionar pelo menos um dos dados pedagógicos.', verbose_name='Dados pedagógicos'),
        ),
    ]
