# Generated by Django 4.0.2 on 2022-08-11 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0049_alter_clientteacherobligationconfiguration_pedagogical_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examprintconfig',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_print_configs', to='clients.client', verbose_name='cliente'),
        ),
    ]
