# Generated by Django 4.0.6 on 2022-10-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0050_alter_examprintconfig_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.SmallIntegerField(choices=[(1, 'Escola'), (2, 'Outro'), (3, 'Mentorizze')], verbose_name='Tipo de cliente'),
        ),
    ]
