# Generated by Django 4.0.6 on 2022-10-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0018_omrcategory_omrerror_application_student_and_more'),
        ('clients', '0050_alter_examprintconfig_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='omr_categories',
            field=models.ManyToManyField(related_name='clients', to='omr.omrcategory', verbose_name='Formatos de gabarito habilitados'),
        ),
    ]
