# Generated by Django 4.0.6 on 2022-10-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0051_alter_client_type_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_automatic_creation',
            field=models.BooleanField(default=False, verbose_name='Tem acesso a criação automática de listas'),
        ),
    ]
