# Generated by Django 4.0.6 on 2022-10-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0052_client_omr_categories_create_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='allow_add_same_teacher_subject_in_exam',
            field=models.BooleanField(default=False, verbose_name='Permitir cadastrar várias soclitações para o mesmo professor/disciplina no mesmo caderno'),
        ),
    ]
