# Generated by Django 4.0.6 on 2022-10-27 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_alter_schoolclass_turn'),
        ('clients', '0053_client_allow_add_same_teacher_subject_in_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolcoordination',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.grade', verbose_name='Grade'),
        ),
    ]
