# Generated by Django 4.0.6 on 2022-10-26 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0052_client_has_automatic_creation'),
        ('clients', '0053_client_allow_add_same_teacher_subject_in_exam'),
    ]

    operations = [
    ]
