# Generated by Django 4.0.6 on 2022-10-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0053_client_allow_add_same_teacher_subject_in_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='enable_omr_ocr',
            field=models.BooleanField(default=False, verbose_name='Ativar OCR na leitura de cartões resposta'),
        ),
        migrations.AlterField(
            model_name='client',
            name='disable_stripped_answer_sheet',
            field=models.BooleanField(default=False, verbose_name='Desativar tabela zebrada na folha de respostas'),
        ),
    ]
