# Generated by Django 4.0.6 on 2022-10-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0054_schoolcoordination_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolcoordination',
            name='grade',
        ),
        migrations.AddField(
            model_name='schoolcoordination',
            name='elementary_school2',
            field=models.BooleanField(default=False, verbose_name='Responsável pelo ensino fundamental 2?'),
        ),
        migrations.AlterField(
            model_name='schoolcoordination',
            name='elementary_school',
            field=models.BooleanField(default=True, verbose_name='Responsável pelo ensino fundamental 1?'),
        ),
    ]
