# Generated by Django 4.0.6 on 2022-10-31 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0054_client_enable_omr_ocr_and_more'),
        ('clients', '0055_remove_schoolcoordination_grade_and_more'),
    ]

    operations = [
    ]
