# Generated by Django 4.0.6 on 2022-11-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0054_merge_20221026_1937'),
        ('clients', '0056_merge_20221031_1417'),
    ]

    operations = [
    ]
