# Generated by Django 4.0.6 on 2022-11-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0057_merge_20221112_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='disable_stripped_answer_sheet',
            field=models.BooleanField(default=False, help_text='Marque esta opção se o cliente se declarar INCAPAZ de ajustar o contraste de uma impressora comum.', verbose_name='Desativar tabela zebrada na folha de respostas'),
        ),
    ]
