# Generated by Django 4.0.6 on 2022-11-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0058_alter_client_disable_stripped_answer_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcoordination',
            name='can_see_all',
            field=models.BooleanField(default=False, verbose_name='Pode ver tudo?'),
        ),
    ]
