# Generated by Django 4.0.6 on 2022-11-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0059_alter_schoolcoordination_can_see_all'),
        ('clients', '0059_examprintconfig_discursive_line_height_and_more'),
    ]

    operations = [
    ]
