# Generated by Django 4.0.6 on 2023-01-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0060_merge_20221127_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examprintconfig',
            name='text_question_format',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Imprimir espaços'), (1, 'Não imprimir')], default=0, verbose_name='estilo das questões discursivas'),
        ),
    ]
