# Generated by Django 4.0.6 on 2022-12-06 17:29

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0060_merge_20221127_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQuestionsConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('can_edit_question_aproveds', models.BooleanField(default=False, help_text='Ao marcar esta opção, o professor poderá alterar a questão mesmo após ela ser aprovada para uso.', verbose_name='O professor pode editar questões aṕos aprovação')),
                ('can_delete_question_aproveds', models.BooleanField(default=False, help_text='Ao marcar esta opção, o professor poderá deletar a questão mesmo após ela ser aprovada para uso.', verbose_name='O professor pode deletar questões aṕos aprovação')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='questions_configuration', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Configuração de questões',
                'verbose_name_plural': 'Configurações de questões',
                'ordering': ['created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
