# Generated by Django 4.0.6 on 2023-01-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0060_merge_20221127_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_discursive_answers',
            field=models.BooleanField(default=False, verbose_name='Tem acesso a correção de discursivas'),
        ),
    ]
