# Generated by Django 4.0.6 on 2022-12-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0061_clientquestionsconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientquestionsconfiguration',
            name='can_delete_question_aproveds',
        ),
    ]
