# Generated by Django 4.0.6 on 2022-12-08 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0063_clientcustomfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomfilter',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_filters', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
