# Generated by Django 4.0.6 on 2022-12-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0063_remove_clientquestionsconfiguration_can_edit_question_aproveds_and_more'),
        ('clients', '0064_alter_clientcustomfilter_user'),
    ]

    operations = [
    ]
