# Generated by Django 4.0.6 on 2022-12-16 13:12

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0065_merge_20221215_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='nome da etapa')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Etapa do ensino',
                'verbose_name_plural': 'Etapas do ensino',
                'ordering': ['created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EducationSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='nome do sistema de ensino')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='cliente')),
                ('unities', models.ManyToManyField(to='clients.unity', verbose_name='Unidades')),
            ],
            options={
                'verbose_name': 'Sistema de ensino',
                'verbose_name_plural': 'Sistemas de ensino',
                'ordering': ['created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
