# Generated by Django 4.0.6 on 2022-12-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0066_teachingstage_educationsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquestionsconfiguration',
            name='can_edit_and_change_position',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, os coordenadores ou coordenadores de disciplina poderão alterar a ordem ou as questões', verbose_name='Permitir edição e ordenação por coordenador e coordenador de área'),
        ),
    ]
