# Generated by Django 4.0.6 on 2022-12-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0067_clientquestionsconfiguration_can_edit_and_change_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientquestionsconfiguration',
            name='can_edit_and_change_position',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, os coordenadores ou coordenadores de disciplina poderão alterar a ordem e editar as questões enquanto às analisa', verbose_name='Permitir edição e ordenação por coordenador e coordenador de área'),
        ),
    ]
