# Generated by Django 4.0.6 on 2023-01-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0061_client_has_discursive_answers'),
        ('clients', '0068_alter_clientquestionsconfiguration_can_edit_and_change_position'),
    ]

    operations = [
    ]
