# Generated by Django 4.0.6 on 2023-01-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0061_alter_examprintconfig_text_question_format'),
        ('clients', '0069_merge_20230102_0922'),
    ]

    operations = [
    ]
