# Generated by Django 4.0.6 on 2023-02-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0070_merge_20230118_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingstage',
            name='code_export',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='código para exportação'),
        ),
    ]
