# Generated by Django 4.0.6 on 2023-02-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0070_merge_20230118_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_hybrid_omr',
            field=models.BooleanField(default=False, help_text='Modelo de gabarito onde, na parte inferior, existem campos para correção manual do professor', verbose_name='Tem acesso ao modelo de gabarito híbrido'),
        ),
    ]
