# Generated by Django 4.0.6 on 2023-02-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0071_client_has_hybrid_omr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='disable_stripped_answer_sheet',
            field=models.BooleanField(default=False, help_text='Marque esta opção se o cliente tiver problemas com o contraste da impressora', verbose_name='Desativar tabela zebrada na folha de respostas'),
        ),
    ]
