# Generated by Django 4.0.6 on 2023-02-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0072_alter_client_disable_stripped_answer_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_superpro_integration',
            field=models.BooleanField(default=False, verbose_name='Tem acesso a integrações com super professor'),
        ),
    ]
