# Generated by Django 4.0.6 on 2023-02-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0071_teachingstage_code_export'),
        ('clients', '0073_client_has_superpro_integration'),
    ]

    operations = [
    ]
