# Generated by Django 4.0.6 on 2023-02-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0074_merge_20230223_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientteacherobligationconfiguration',
            name='commented_response',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, o professor será obrigado a adicionar a resposta comentada da questão.', verbose_name='Resposta comentada'),
        ),
    ]
