# Generated by Django 4.0.6 on 2023-03-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0075_clientteacherobligationconfiguration_commented_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='show_id_erp_in_exam',
            field=models.BooleanField(default=False, verbose_name='mostrar código de exportação no caderno?'),
        ),
    ]
