# Generated by Django 4.0.6 on 2023-03-06 20:16

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0075_clientteacherobligationconfiguration_commented_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('send_notification', models.BooleanField(default=False, help_text='Ao marcar esta opção, o professor será notificado alguns dias antes da data de entrega do caderno.', verbose_name='Notificar professor')),
                ('first_notification', models.SmallIntegerField(choices=[(1, '1 dia'), (2, '2 dias'), (3, '3 dias')], default=1, help_text='Quantos dias antes da data de entrega a primeira notificação será enviada.', verbose_name='Primeira notificação')),
                ('second_notification', models.SmallIntegerField(choices=[(1, '1 dia'), (2, '2 dias'), (3, '3 dias')], default=1, help_text='Quantos dias antes da data de entrega a segunda notificação será enviada.', verbose_name='Segunda notificação')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='config_notification', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Configuração de notificação',
                'verbose_name_plural': 'Configurações de notificação',
                'ordering': ['created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
