# Generated by Django 4.0.6 on 2023-03-14 14:05

from django.db import migrations
from django.db.models import Q

def update_configs(apps, schema_editor):
    ExamPrintConfig = apps.get_model('clients', 'ExamPrintConfig')
    
    ExamPrintConfig.objects.filter(
        Q(name__icontains='Configuração CÓPIA') | 
        Q(exams__source_exam__isnull=False)
    ).distinct().update(is_default=False)
    

class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0076_client_show_id_erp_in_exam'),
    ]

    operations = [
        migrations.RunPython(update_configs, migrations.RunPython.noop),
    ]
