# Generated by Django 4.0.6 on 2023-03-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0076_client_show_id_erp_in_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='allow_online_abstract_application',
            field=models.BooleanField(default=False, verbose_name='permitir aplicação online de gabarito avulso?'),
        ),
    ]
