# Generated by Django 4.0.6 on 2023-03-16 23:27

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0077_update_exam_print_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_application_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da última aplicação realizada'),
        ),
        migrations.AddField(
            model_name='client',
            name='monthly_ticket',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ticket mensal'),
        ),
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Correção'), (2, 'Gestão'), (3, 'Streaming'), (4, 'Cursinho'), (5, 'Plano avulso')], null=True, verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Ativado'), (2, 'Desativado'), (3, 'Pausado'), (4, 'Em POC')], default=1, verbose_name='Situação'),
        ),
        migrations.CreateModel(
            name='Mensality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('billing_date', models.DateField(blank=True, null=True, verbose_name='data de cobrança')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ativa'), (2, 'Inativa'), (3, 'Cancelada')], default=1, verbose_name='status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'mensalidade',
                'verbose_name_plural': 'mensalidades',
                'ordering': ['created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
