# Generated by Django 4.0.6 on 2023-03-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0077_update_exam_print_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_question_formatter',
            field=models.BooleanField(default=False, verbose_name='Tem acesso ao formatador de questões'),
        ),
    ]
