# Generated by Django 4.1.7 on 2023-03-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0077_client_allow_online_abstract_application"),
        ("clients", "0077_update_exam_print_configs"),
    ]

    operations = []
