# Generated by Django 4.0.6 on 2023-03-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0078_alter_confignotification_first_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confignotification',
            name='first_notification',
            field=models.SmallIntegerField(choices=[(0, '1 dia'), (1, '2 dias'), (2, '3 dias'), (3, '4 dias'), (4, '5 dias')], default=0, help_text='Quantos dias antes da data de entrega a primeira notificação será enviada.', verbose_name='Primeira notificação'),
        ),
        migrations.AlterField(
            model_name='confignotification',
            name='second_notification',
            field=models.SmallIntegerField(choices=[(0, '1 dia'), (1, '2 dias'), (2, '3 dias'), (3, '4 dias')], help_text='Quantos dias antes da data de entrega a segunda notificação será enviada.', verbose_name='Segunda notificação'),
        ),
    ]
