# Generated by Django 4.0.6 on 2023-03-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0078_client_last_application_date_client_monthly_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last_application_date',
        ),
        migrations.AlterField(
            model_name='client',
            name='monthly_ticket',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ticket mensal'),
        ),
        migrations.AlterField(
            model_name='mensality',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Em aberto'), (2, 'Pago'), (3, 'Cancelada')], default=1, verbose_name='status'),
        ),
    ]
