# Generated by Django 4.0.6 on 2023-03-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0079_alter_confignotification_first_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confignotification',
            name='second_notification',
            field=models.SmallIntegerField(blank=True, choices=[(0, '1 dia'), (1, '2 dias'), (2, '3 dias'), (3, '4 dias')], help_text='Quantos dias antes da data de entrega a segunda notificação será enviada.', null=True, verbose_name='Segunda notificação'),
        ),
    ]
