# Generated by Django 4.0.6 on 2023-03-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0076_client_show_id_erp_in_exam'),
        ('clients', '0080_alter_confignotification_second_notification'),
    ]

    operations = [
    ]
