# Generated by Django 4.0.6 on 2023-03-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0077_update_exam_print_configs'),
        ('clients', '0081_merge_20230313_1528'),
    ]

    operations = [
    ]
