# Generated by Django 4.0.6 on 2023-03-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0077_client_allow_online_abstract_application'),
        ('clients', '0079_remove_client_last_application_date_and_more'),
        ('clients', '0082_merge_20230320_1154'),
    ]

    operations = [
    ]
