# Generated by Django 4.1.7 on 2023-03-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0078_merge_20230322_1628"),
        ("clients", "0083_merge_20230322_1559"),
    ]

    operations = []
