# Generated by Django 4.0.6 on 2023-03-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0078_client_has_question_formatter'),
        ('clients', '0084_merge_20230322_1651'),
    ]

    operations = [
    ]
