# Generated by Django 4.0.6 on 2023-03-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0086_rename_bncc_clientteacherobligationconfiguration_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientteacherobligationconfiguration',
            name='competencies',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, o professor será obrigado a marcar pelo menos uma competência', verbose_name='Competências'),
        ),
        migrations.AlterField(
            model_name='clientteacherobligationconfiguration',
            name='abilities',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, o professor será obrigado a marcar pelo menos uma habilidade', verbose_name='Habilidades'),
        ),
    ]
