# Generated by Django 4.0.6 on 2023-03-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0087_clientteacherobligationconfiguration_competencies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientteacherobligationconfiguration',
            old_name='competencies',
            new_name='competences',
        ),
    ]
