# Generated by Django 4.0.6 on 2023-04-24 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0089_clientcustompage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientCustomPage',
        ),
    ]
