# Generated by Django 4.0.6 on 2023-04-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0089_questiontag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiontag',
            options={'ordering': ('name',), 'verbose_name': 'Tag de questão', 'verbose_name_plural': 'Tags de questão'},
        ),
    ]
