# Generated by Django 4.0.6 on 2023-04-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0090_alter_questiontag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontag',
            name='is_question_correction_tag',
            field=models.BooleanField(default=False, help_text='Selecionar essa opção fará com que a tag apareça apenas na edição de questões'),
        ),
    ]
