# Generated by Django 4.0.6 on 2023-04-24 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0117_clientcustompage_name'),
        ('clients', '0090_delete_clientcustompage'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprintconfig',
            name='custom_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.clientcustompage', verbose_name='Página customizada'),
        ),
    ]
