# Generated by Django 4.0.6 on 2023-04-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0117_clientcustompage_name'),
        ('clients', '0091_examprintconfig_custom_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examprintconfig',
            name='custom_page',
        ),
        migrations.AddField(
            model_name='examprintconfig',
            name='custom_page',
            field=models.ManyToManyField(blank=True, to='exams.clientcustompage', verbose_name='Página customizadas'),
        ),
    ]
