# Generated by Django 4.0.6 on 2023-04-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0092_remove_examprintconfig_custom_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examprintconfig',
            old_name='custom_page',
            new_name='custom_pages',
        ),
    ]
