# Generated by Django 4.0.6 on 2023-05-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0092_remove_questiontag_is_question_correction_tag_and_more'),
        ('clients', '0093_rename_custom_page_examprintconfig_custom_pages'),
    ]

    operations = [
    ]
