# Generated by Django 4.0.6 on 2023-05-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0094_merge_20230510_1334'),
        ('clients', '0094_merge_20230523_1822'),
    ]

    operations = [
    ]
