# Generated by Django 4.0.6 on 2023-07-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0095_merge_20230523_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_partners',
            field=models.BooleanField(default=False, verbose_name='Tem acesso ao cadastro de parceiros.'),
        ),
    ]
