# Generated by Django 4.0.6 on 2023-08-07 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0097_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='is_printing_staff',
            field=models.BooleanField(default=False, help_text='É um membro da equipe de impressão', verbose_name='É da equipe de impressão'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='partner', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
