# Generated by Django 4.0.6 on 2023-08-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0098_alter_partner_is_printing_staff_alter_partner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.EmailField(default='temp@email.com', max_length=254, verbose_name='Endereço de email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='name',
            field=models.CharField(default='temp@email.com', max_length=100, verbose_name='Nome do parceiro'),
            preserve_default=False,
        ),
    ]
