# Generated by Django 4.0.6 on 2023-08-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0099_partner_email_partner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='is_printing_staff',
            field=models.BooleanField(default=False, help_text='Tem acesso à tela de impressões de aplicação', verbose_name='É da equipe de impressão'),
        ),
    ]
