# Generated by Django 4.0.6 on 2023-08-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0096_client_has_tri'),
        ('clients', '0100_alter_partner_is_printing_staff'),
    ]

    operations = [
    ]
