# Generated by Django 4.0.6 on 2023-08-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0101_merge_20230821_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='teachers_can_elaborate_exam',
            field=models.BooleanField(default=False, verbose_name='Os professores podem elaborar listas de exercício'),
        ),
    ]
