# Generated by Django 4.0.6 on 2023-09-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0102_client_has_followup_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_update_followup_dashboard',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última atualização do dashboard followup'),
        ),
    ]
