# Generated by Django 4.0.6 on 2023-09-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0102_alter_client_teachers_can_elaborate_exam'),
        ('clients', '0103_client_last_update_followup_dashboard'),
    ]

    operations = [
    ]
