# Generated by Django 4.0.6 on 2023-09-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0104_merge_20230911_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_sisu_simulator',
            field=models.BooleanField(default=False, verbose_name='Os alunos tem acesso ao simulador SISU'),
        ),
    ]
