# Generated by Django 4.0.6 on 2023-10-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0107_alter_confignotification_after_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confignotification',
            name='coordination_send_notification',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, os coordenadores serão notificados alguns dias antes da data de entrega dos cadernos.', verbose_name='Notificar Coordenadores'),
        ),
        migrations.AlterField(
            model_name='confignotification',
            name='send_notification',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, os professores serão notificados alguns dias antes da data de entrega dos cadernos.', verbose_name='Notificar professores'),
        ),
    ]
