# Generated by Django 4.0.6 on 2023-10-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0110_merge_20231021_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examprintconfig',
            name='font_family',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Plex Sans'), (1, 'Verdana'), (2, 'Times'), (3, 'Arial'), (4, 'Nunito Sans')], default=0, verbose_name='tipo da fonte'),
        ),
        migrations.AlterField(
            model_name='examprintconfig',
            name='font_size',
            field=models.PositiveSmallIntegerField(choices=[(0, '12pt'), (1, '14pt'), (2, '18pt'), (3, '22pt'), (4, '32pt'), (5, '8pt'), (6, '10pt'), (7, '11pt')], default=0, verbose_name='tamanho da fonte'),
        ),
    ]
