# Generated by Django 4.0.6 on 2023-10-22 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0106_client_max_students_quantity'),
        ('clients', '0108_confignotification_coordination_send_notification_and_more'),
    ]

    operations = [
    ]
