# Generated by Django 4.0.6 on 2023-11-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0109_alter_examprintconfig_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_ia_creation',
            field=models.BooleanField(default=False, verbose_name='Pode criar questão com IA'),
        ),
    ]
