# Generated by Django 4.0.6 on 2023-11-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0109_alter_examprintconfig_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_late_questions',
            field=models.BooleanField(default=False, verbose_name='Tem acesso a adição de questões atrasadas'),
        ),
    ]
