# Generated by Django 4.0.6 on 2023-12-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0110_client_has_late_questions'),
        ('clients', '0110_client_has_omrnps'),
    ]

    operations = [
    ]
