# Generated by Django 4.0.6 on 2023-11-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0110_client_has_ia_creation'),
        ('clients', '0110_client_has_omrnps'),
    ]

    operations = [
    ]
