# Generated by Django 4.0.6 on 2023-12-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0111_merge_20231124_1556'),
        ('clients', '0111_merge_20231203_1412'),
    ]

    operations = [
    ]
