# Generated by Django 4.0.6 on 2024-02-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0113_client_has_new_teacher_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='allow_login_only_google',
            field=models.BooleanField(default=False, verbose_name='Permitir login apenas com o google'),
        ),
    ]
