# Generated by Django 4.0.6 on 2024-01-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0113_client_has_new_teacher_experience'),
        ('clients', '0113_client_has_sum_question'),
    ]

    operations = [
    ]
