# Generated by Django 4.0.6 on 2024-02-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0114_client_allow_login_only_google'),
        ('clients', '0114_merge_20240131_1421'),
    ]

    operations = [
    ]
