# Generated by Django 4.0.6 on 2024-02-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0114_client_allow_login_only_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='allow_add_exception_deadline_correction_response',
            field=models.BooleanField(default=False, verbose_name='permitir adicionar exceção da data limite para professores corrigirem respostas?'),
        ),
    ]
