# Generated by Django 4.0.6 on 2024-02-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0115_client_allow_add_exception_deadline_correction_response'),
        ('clients', '0115_merge_20240206_1439'),
    ]

    operations = [
    ]
