# Generated by Django 4.0.6 on 2024-03-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0116_merge_20240222_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprintconfig',
            name='show_question_board',
            field=models.BooleanField(default=False, help_text='Designa se o caderno deve mostrar a banca das questões.', verbose_name='mostrar a banca da questão?'),
        ),
        migrations.AddField(
            model_name='examprintconfig',
            name='show_question_score',
            field=models.BooleanField(default=False, help_text='Designa se o caderno deve mostrar a pontuação das questões.', verbose_name='mostrar a pontuação da questão?'),
        ),
    ]
