# Generated by Django 4.0.6 on 2024-03-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0116_merge_20240222_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='omr_print_file_separation',
            field=models.CharField(blank=True, choices=[('default', 'Padrão (Arquivos juntos)'), ('separated', 'Arquivos separados')], default='default', max_length=12, verbose_name='Separação de arquivos na geração de malote'),
        ),
    ]
