# Generated by Django 4.0.6 on 2024-03-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0117_alter_coordinationmember_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinationmember',
            options={'ordering': ['created_at'], 'permissions': (('can_export_coodinator', 'Pode exportar coordenadores'),), 'verbose_name': 'Membro da coordenação', 'verbose_name_plural': 'Membros da coordenação'},
        ),
    ]
