# Generated by Django 4.0.6 on 2024-03-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0117_examprintconfig_show_question_board_and_more'),
        ('clients', '0118_alter_coordinationmember_options'),
    ]

    operations = [
    ]
