# Generated by Django 4.0.6 on 2024-03-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0117_client_omr_print_file_separation'),
        ('clients', '0119_merge_20240329_1046'),
    ]

    operations = [
    ]
