# Generated by Django 4.0.6 on 2024-04-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0121_alter_examprintconfig_show_question_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='send_email_to_student_after_create',
            field=models.BooleanField(default=False, verbose_name='enviar e-mail para aluno após cadastro?'),
        ),
    ]
