# Generated by Django 4.0.6 on 2024-04-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0121_alter_examprintconfig_show_question_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='use_only_own_topics',
            field=models.BooleanField(default=True, verbose_name='Utiliza apenas assuntos próprias cadastradas no sistema'),
        ),
    ]
