# Generated by Django 4.0.6 on 2024-04-05 02:26

from django.db import migrations
from fiscallizeon.classes.models import Grade

def create_grades(apps, schema_editor):
    Grade = apps.get_model('classes', 'Grade')
    
    HIGHT_SCHOOL, ELEMENTARY_SCHOOL, ELEMENTARY_SCHOOL_2 = range(3)
    grades = [
        {'name': '1', 'level': ELEMENTARY_SCHOOL},
        {'name': '2', 'level': ELEMENTARY_SCHOOL},
        {'name': '3', 'level': ELEMENTARY_SCHOOL},
        {'name': '4', 'level': ELEMENTARY_SCHOOL},
        {'name': '5', 'level': ELEMENTARY_SCHOOL},
        {'name': '6', 'level': ELEMENTARY_SCHOOL_2},
        {'name': '7', 'level': ELEMENTARY_SCHOOL_2},
        {'name': '8', 'level': ELEMENTARY_SCHOOL_2},
        {'name': '9', 'level': ELEMENTARY_SCHOOL_2},
        {'name': '1', 'level': HIGHT_SCHOOL},
        {'name': '2', 'level': HIGHT_SCHOOL},
        {'name': '3', 'level': HIGHT_SCHOOL},
    ]

    for grade in grades:
        Grade.objects.get_or_create(
            name=grade['name'],
            level=grade['level']
        )

class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0121_alter_examprintconfig_show_question_board_and_more'),
    ]

    operations = [
        migrations.RunPython(create_grades, migrations.RunPython.noop),
    ]
