# Generated by Django 4.0.6 on 2024-04-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0121_alter_examprintconfig_show_question_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquestionsconfiguration',
            name='can_swap_questions_groups',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, os coordenadores ou coordenadores de disciplina poderão trocar questões entre solicitações de questões para fins de diagramação.', verbose_name='Permitir troca de questões entre solicitações'),
        ),
    ]
