# Generated by Django 4.0.6 on 2024-04-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0121_alter_examprintconfig_show_question_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='can_select_header_in_create_or_update_exam',
            field=models.BooleanField(default=False, verbose_name='Pode selecionar cabeçalho na criação/atualização de caderno'),
        ),
    ]
