# Generated by Django 4.0.6 on 2024-04-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0121_alter_examprintconfig_show_question_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprintconfig',
            name='margin_bottom',
            field=models.FloatField(default=0.6, help_text='Margem inferior em centímetros.', verbose_name='Margem Inferior (cm)'),
        ),
        migrations.AddField(
            model_name='examprintconfig',
            name='margin_left',
            field=models.FloatField(default=0.6, help_text='Margem esquerda em centímetros.', verbose_name='Margem Esquerda (cm)'),
        ),
        migrations.AddField(
            model_name='examprintconfig',
            name='margin_right',
            field=models.FloatField(default=0.6, help_text='Margem direita em centímetros.', verbose_name='Margem Direita (cm)'),
        ),
        migrations.AddField(
            model_name='examprintconfig',
            name='margin_top',
            field=models.FloatField(default=0.6, help_text='Margem superior em centímetros.', verbose_name='Margem Superior (cm)'),
        ),
    ]
