# Generated by Django 4.0.6 on 2024-04-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0122_alter_clientquestionsconfiguration_block_edit_question_aproveds'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_discursive_auto_correction',
            field=models.BooleanField(default=False, help_text='O sistema deve corrigir as questões discursivas com tecnologia OMR?', verbose_name='Tem acesso a correção automática de discursivas'),
        ),
        migrations.AlterField(
            model_name='clientquestionsconfiguration',
            name='block_edit_question_aproveds',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, os professores não poderão alterar a questão após ela ser aprovada para uso.', verbose_name='Bloquar edição após aprovação'),
        ),
    ]
