# Generated by Django 4.0.6 on 2024-04-26 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0122_alter_clientquestionsconfiguration_block_edit_question_aproveds'),
        ('clients', '0122_client_can_select_header_in_create_or_update_exam'),
    ]

    operations = [
    ]
