# Generated by Django 4.0.6 on 2024-04-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0122_client_use_only_own_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='use_only_own_topics',
            field=models.BooleanField(default=False, verbose_name='Utiliza apenas assuntos próprios cadastradas no sistema'),
        ),
    ]
