# Generated by Django 4.0.6 on 2024-04-27 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0122_examprintconfig_margin_bottom_and_more'),
        ('clients', '0123_merge_20240426_2054'),
    ]

    operations = [
    ]
