# Generated by Django 4.0.6 on 2024-04-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0123_client_has_discursive_auto_correction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientquestionsconfiguration',
            name='block_edit_question_aproveds',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, os professores não poderão alterar a questão após ela ser aprovada para uso.', verbose_name='Bloquear edição após aprovação'),
        ),
    ]
