# Generated by Django 4.0.6 on 2024-04-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0122_alter_clientquestionsconfiguration_block_edit_question_aproveds'),
        ('clients', '0123_alter_client_use_only_own_topics'),
    ]

    operations = [
    ]
