# Generated by Django 4.0.6 on 2024-04-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0122_clientquestionsconfiguration_can_swap_questions_groups'),
        ('clients', '0124_merge_20240426_2102'),
    ]

    operations = [
    ]
