# Generated by Django 4.0.6 on 2024-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0124_merge_20240426_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='use_only_own_topics',
            field=models.BooleanField(default=True, verbose_name='Utiliza apenas assuntos próprios cadastradas no sistema'),
        ),
    ]
