# Generated by Django 4.0.6 on 2024-04-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0125_alter_client_use_only_own_topics'),
        ('clients', '0125_merge_20240426_2129'),
    ]

    operations = [
    ]
