# Generated by Django 4.0.6 on 2024-05-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0124_alter_clientquestionsconfiguration_block_edit_question_aproveds'),
        ('clients', '0125_merge_20240426_2129'),
    ]

    operations = [
    ]
