# Generated by Django 4.0.6 on 2024-05-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0122_client_send_email_to_student_after_create'),
        ('clients', '0126_merge_20240503_1004'),
    ]

    operations = [
    ]
