# Generated by Django 4.0.6 on 2024-05-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0126_merge_20240429_1343'),
        ('clients', '0127_merge_20240504_1550'),
    ]

    operations = [
    ]
