# Generated by Django 4.0.6 on 2024-05-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0128_merge_20240504_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquestionsconfiguration',
            name='can_add_support_content_discursive_questions',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, os professores poderão adicionar um conteudo extra no gabarito das questões discursivas.', verbose_name='Permitir adicionar conteúdo de apoio para resposta do aluno em questões discursivas'),
        ),
    ]
