# Generated by Django 4.0.6 on 2024-06-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0129_clientquestionsconfiguration_can_add_support_content_discursive_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprintconfig',
            name='uppercase_letters',
            field=models.BooleanField(default=False, help_text='Designa se o caderno deve ter todas as letras maiúscula.', verbose_name='imprimir tudo maiúsculo?'),
        ),
    ]
