# Generated by Django 4.0.6 on 2024-06-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0129_clientquestionsconfiguration_can_add_support_content_discursive_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientquestionsconfiguration',
            name='can_add_support_content_discursive_questions',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, os professores poderão adicionar um conteudo extra no gabarito das questões discursivas.', verbose_name='Permitir adicionar conteúdo de apoio para resposta do aluno em questões discursivas'),
        ),
    ]
