# Generated by Django 4.0.6 on 2024-06-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0130_alter_clientquestionsconfiguration_can_add_support_content_discursive_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='enabled_new_answer_sheet_experience',
            field=models.BooleanField(default=False, verbose_name='habilitado nova experiência de gabarito?'),
        ),
    ]
