# Generated by Django 4.0.6 on 2024-06-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0130_alter_clientquestionsconfiguration_can_add_support_content_discursive_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Após esse tempo de inatividade o usuário deverá fazer login novamente', verbose_name='Tempo em minutos para expiração de sessão dos usuários'),
        ),
    ]
