# Generated by Django 4.0.6 on 2024-07-08 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0131_client_enabled_new_answer_sheet_experience'),
        ('clients', '0131_client_session_timeout_minutes'),
    ]

    operations = [
    ]
