# Generated by Django 4.0.6 on 2024-07-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0132_merge_20240707_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Após esse tempo de inatividade o usuário deverá fazer login novamente. O valor 0 (zero) impede que a sessão expire.', verbose_name='Tempo em minutos para expiração de sessão dos usuários'),
        ),
    ]
