# Generated by Django 4.0.6 on 2024-07-08 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0130_examprintconfig_uppercase_letters'),
        ('clients', '0133_alter_client_session_timeout_minutes'),
    ]

    operations = [
    ]
