# Generated by Django 4.0.6 on 2024-07-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0134_merge_20240707_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquestionsconfiguration',
            name='can_not_add_multiple_correct_options_question',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, os professores não poderão criar questões objetivas com mais de uma alternativa correta.', verbose_name='Não permitir duas alternativas corretas para questões objetivas'),
        ),
    ]
