# Generated by Django 4.0.6 on 2024-07-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0134_merge_20240707_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='can_request_ai_questions',
            field=models.BooleanField(default=False, verbose_name='Pode solicitar questão à IA'),
        ),
    ]
