# Generated by Django 4.0.6 on 2024-08-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0135_client_has_dashboards'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_review_system',
            field=models.BooleanField(blank=True, default=False, help_text='Essa opção ta relacionada ao campo review_deadline de exam e o card de revisão que fica no novo dash de acompanhamento', verbose_name='Tem acesso ao sistema de revisão'),
        ),
    ]
