# Generated by Django 4.0.6 on 2024-07-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0135_clientquestionsconfiguration_can_not_add_multiple_correct_options_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='can_disable_multiple_correct_options',
            field=models.BooleanField(default=False, verbose_name='Permitir desativar a possibilidade de criar questões objetivas com mais de uma alternativa correta'),
        ),
    ]
