# Generated by Django 4.0.6 on 2024-08-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0135_client_has_dashboards'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquestionsconfiguration',
            name='can_change_subject_with_existing_questions',
            field=models.BooleanField(default=False, verbose_name='Permitir trocar a disciplina da solicitação quando já exitir questões.'),
        ),
    ]
