# Generated by Django 4.0.6 on 2024-07-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0135_client_can_request_ai_questions'),
        ('clients', '0135_client_has_dashboards'),
    ]

    operations = [
    ]
