# Generated by Django 4.0.6 on 2024-07-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0135_client_has_dashboards'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='already_onboarded_coordinators',
            field=models.BooleanField(default=False, verbose_name='coordenadores já integrados?'),
        ),
        migrations.AddField(
            model_name='client',
            name='already_onboarded_students',
            field=models.BooleanField(default=False, verbose_name='alunos já integrados?'),
        ),
        migrations.AddField(
            model_name='client',
            name='already_onboarded_teachers',
            field=models.BooleanField(default=False, verbose_name='professores já integrados?'),
        ),
    ]
