# Generated by Django 4.0.6 on 2024-07-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0122_create_grades_data'),
        ('clients', '0135_client_has_dashboards'),
    ]

    operations = [
    ]
