# Generated by Django 4.0.6 on 2024-08-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0136_client_has_review_system'),
        ('clients', '0136_merge_20240724_1200'),
    ]

    operations = [
    ]
