# Generated by Django 4.0.6 on 2024-08-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0136_client_has_filtered_layout_for_today_student_applications'),
        ('clients', '0136_client_has_review_system'),
    ]

    operations = [
    ]
