# Generated by Django 4.0.6 on 2024-07-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0136_client_can_disable_multiple_correct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='can_disable_multiple_correct_options',
            field=models.BooleanField(default=False, verbose_name='Pode escolher bloquear a criação de questões objetivas com mais de uma alternativa correta'),
        ),
    ]
