# Generated by Django 4.0.6 on 2024-08-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0137_alter_clientquestionsconfiguration_can_change_subject_with_existing_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientquestionsconfiguration',
            name='can_change_subject_with_existing_questions',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, os coordenadores poderão alterar a disciplina da solicitação de questões, mesmo se já houver questões existentes.', verbose_name='Permitir trocar a disciplina da solicitação quando já existir questões.'),
        ),
    ]
