# Generated by Django 4.0.6 on 2024-08-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0137_merge_20240814_1011'),
        ('clients', '0138_alter_clientquestionsconfiguration_can_change_subject_with_existing_questions'),
    ]

    operations = [
    ]
