# Generated by Django 4.0.6 on 2024-08-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0137_alter_client_can_disable_multiple_correct_options'),
        ('clients', '0137_merge_20240816_1508'),
        ('clients', '0138_alter_clientquestionsconfiguration_can_change_subject_with_existing_questions'),
    ]

    operations = [
    ]
