# Generated by Django 4.0.6 on 2024-08-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0139_merge_20240815_1405'),
        ('clients', '0139_merge_20240816_1542'),
    ]

    operations = [
    ]
