# Generated by Django 4.0.6 on 2024-09-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0136_merge_20240724_1458'),
        ('clients', '0140_merge_20240820_1235'),
    ]

    operations = [
    ]
