# Generated by Django 4.0.6 on 2024-09-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0140_merge_20240820_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprintconfig',
            name='show_footer',
            field=models.BooleanField(default=False, help_text='Designa se o caderno deve ter o título no rodapé de todas as páginas.', verbose_name='Imprimir nome do caderno no rodapé.'),
        ),
    ]
