# Generated by Django 4.0.6 on 2024-09-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0141_examprintconfig_show_footer'),
        ('clients', '0141_merge_20240909_1043'),
    ]

    operations = [
    ]
