# Generated by Django 4.0.6 on 2024-09-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0142_merge_20240920_1619'),
        ('clients', '0142_merge_20240920_1630'),
    ]

    operations = [
    ]
