# Generated by Django 4.0.6 on 2024-10-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0136_client_already_onboarded_coordinators_and_more'),
        ('clients', '0143_merge_20240920_1822'),
    ]

    operations = [
    ]
