# Generated by Django 4.0.6 on 2024-10-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0143_merge_20240920_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_essay_system',
            field=models.BooleanField(blank=True, default=False, verbose_name='Tem acesso ao sistema de correção de redação'),
        ),
    ]
