# Generated by Django 4.0.6 on 2024-09-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0143_merge_20240920_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquestionsconfiguration',
            name='can_add_revision_after_closing_exam',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, o elaborador do caderno  poderá revisá-lo após o seu fechamento.', verbose_name='Permitir revisão do elaborador após fechamento do caderno.'),
        ),
    ]
