# Generated by Django 4.0.6 on 2024-10-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0144_clientquestionsconfiguration_can_add_revision_after_closing_exam'),
        ('clients', '0144_merge_20241025_1215'),
    ]

    operations = [
    ]
