# Generated by Django 4.0.6 on 2024-10-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0145_merge_20241025_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientquestionsconfiguration',
            name='can_add_revision_after_closing_exam',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, o elaborador  poderá revisar o PDF após o seu fechamento do caderno.', verbose_name='Permitir revisão do elaborador após fechamento do caderno.'),
        ),
    ]
