# Generated by Django 4.0.6 on 2024-11-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0191_alter_exambackgroundimage_image_and_more'),
        ('clients', '0146_alter_clientquestionsconfiguration_can_add_revision_after_closing_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprintconfig',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exams.exambackgroundimage', verbose_name='Imagem de fundo'),
        ),
    ]
