# Generated by Django 4.0.6 on 2024-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0146_alter_clientquestionsconfiguration_can_add_revision_after_closing_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprintconfig',
            name='break_enunciation',
            field=models.BooleanField(default=False, help_text='Se ativado, quebra o enunciado em partes menores para facilitar a leitura e organização das questões.', verbose_name='Quebra de enunciado'),
        ),
        migrations.AddField(
            model_name='examprintconfig',
            name='discursive_question_space_type',
            field=models.SmallIntegerField(choices=[(0, 'De acordo com a questão'), (1, 'Espaço em branco'), (2, 'Linhas')], default=0, help_text='Define o tipo de espaço disponível para respostas discursivas, como linhas ou caixas de texto.', verbose_name='Tipo de espaço para questão discursiva'),
        ),
        migrations.AddField(
            model_name='examprintconfig',
            name='economy_mode',
            field=models.BooleanField(default=False, help_text='Com ele, os enunciados são quebrados automaticamente e a prova é exibida em duas colunas.', verbose_name='Modo econômico.'),
        ),
        migrations.AddField(
            model_name='examprintconfig',
            name='force_choices_with_statement',
            field=models.BooleanField(default=False, help_text='As alternativas de cada questão serão exibidas imediatamente junto ao enunciado.', verbose_name='Forçar alternativas junto ao enunciado.'),
        ),
        migrations.AddField(
            model_name='examprintconfig',
            name='hide_numbering',
            field=models.BooleanField(default=False, help_text='Remove a numeração das questões, deixando o enunciado e as alternativas sem identificação numérica.', verbose_name='Esconder numerações das questões'),
        ),
    ]
