# Generated by Django 4.0.6 on 2024-10-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0144_client_has_essay_system'),
        ('clients', '0146_alter_clientquestionsconfiguration_can_add_revision_after_closing_exam'),
    ]

    operations = [
    ]
