# Generated by Django 4.0.6 on 2024-11-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0147_examprintconfig_background_image'),
        ('clients', '0147_merge_20241030_1617'),
    ]

    operations = [
    ]
