# Generated by Django 4.0.6 on 2024-11-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0147_examprintconfig_break_enunciation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examprintconfig',
            name='force_choices_with_statement',
            field=models.BooleanField(default=False, help_text='As alternativas de cada questão serão exibidas imediatamente junto ao enunciado. (Quebra de enunciado será desconsiderado.)', verbose_name='Forçar alternativas junto ao enunciado.'),
        ),
    ]
