# Generated by Django 4.0.6 on 2024-11-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0148_alter_examprintconfig_force_choices_with_statement'),
        ('clients', '0148_merge_20241126_1121'),
    ]

    operations = [
    ]
