# Generated by Django 4.0.6 on 2024-12-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0149_merge_20241126_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='Habilitação da autenticação de dois fatores'),
        ),
    ]
