# Generated by Django 4.0.6 on 2024-12-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0149_merge_20241126_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_discursive_ai_correction',
            field=models.BooleanField(blank=True, default=False, verbose_name='Possui correção automática de questões discursivas'),
        ),
    ]
