# Generated by Django 4.0.6 on 2025-01-11 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0150_client_has_discursive_ai_correction'),
        ('clients', '0150_client_two_factor_enabled'),
    ]

    operations = [
    ]
