# Generated by Django 4.0.6 on 2025-02-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0021_integrationtoken_expiration_date_and_more'),
        ('clients', '0152_alter_educationsystem_unities'),
    ]

    operations = [
        migrations.AddField(
            model_name='unity',
            name='integration_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unities', to='integrations.integrationtoken', verbose_name='Token utilizado para integração'),
        ),
    ]
