# Generated by Django 4.0.6 on 2025-01-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0152_alter_educationsystem_unities'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprintconfig',
            name='language',
            field=models.SmallIntegerField(choices=[(0, 'Português'), (1, 'Inglês'), (2, 'Espanhol')], default=0, help_text='Define o idioma padrão do caderno. Termos como "questão", "texto base" dados do cabeçalho padrão serão traduzidos', verbose_name='Idioma dos textos do caderno'),
        ),
    ]
