# Generated by Django 4.2.18 on 2025-02-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0152_alter_educationsystem_unities'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_app_access',
            field=models.BooleanField(default=False, verbose_name='Tem acesso ao APP'),
        ),
    ]
