# Generated by Django 4.2.18 on 2025-02-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0153_client_has_app_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='has_app_access',
            new_name='can_access_app',
        ),
    ]
