# Generated by Django 4.0.6 on 2025-02-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0153_examprintconfig_language'),
        ('clients', '0153_unity_integration_token'),
    ]

    operations = [
    ]
