# Generated by Django 4.0.6 on 2025-02-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0154_merge_20250218_1058'),
        ('clients', '0154_rename_has_app_access_client_can_access_app'),
    ]

    operations = [
    ]
