# Generated by Django 4.2.19 on 2025-02-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0155_merge_20250219_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome simpleficado'),
        ),
    ]
