# Generated by Django 4.2.19 on 2025-02-28 16:08

from django.db import migrations, models
import fiscallizeon.core.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0156_client_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='small_logo',
            field=models.ImageField(blank=True, null=True, storage=fiscallizeon.core.storage_backends.PublicMediaStorage(), upload_to='clients/logos/', verbose_name='Logo pequena'),
        ),
    ]
