# Generated by Django 4.2.19 on 2025-03-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0157_client_small_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientteacherobligationconfiguration',
            name='level',
            field=models.PositiveIntegerField(choices=[(1, 'Anos iniciais'), (2, 'Anos finais'), (0, 'Ensino Médio')], default=1, verbose_name='Sigmento'),
        ),
        migrations.AlterField(
            model_name='clientteacherobligationconfiguration',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_configuration', to='clients.client', verbose_name='Cliente'),
        ),
    ]
