# Generated by Django 4.2.19 on 2025-03-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0157_client_small_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquestionsconfiguration',
            name='teachers_coordinations_can_edit_questions',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, os professores coordenadores poderão editar questões de outros professores.', verbose_name='Professores coordenadores podem editar questões de outros professores.'),
        ),
    ]
