# Generated by Django 4.2.19 on 2025-03-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0158_clientteacherobligationconfiguration_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientteacherobligationconfiguration',
            name='apply_on_homework',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, para aplicar as configurações para lista de exercícios..', verbose_name='Aplicar no caderno de homework'),
        ),
    ]
