# Generated by Django 4.2.19 on 2025-03-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0159_clientteacherobligationconfiguration_apply_on_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientteacherobligationconfiguration',
            name='apply_on_homework',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, as configurações serão aplicas nas listas de exercícios..', verbose_name='Aplicar para lista de exercícios'),
        ),
    ]
