# Generated by Django 4.2.19 on 2025-04-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0159_alter_client_has_new_teacher_experience'),
        ('clients', '0160_alter_clientteacherobligationconfiguration_apply_on_homework'),
    ]

    operations = [
    ]
