# Generated by Django 4.2.19 on 2025-04-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0160_merge_20250412_1124'),
        ('clients', '0161_merge_20250411_1035'),
    ]

    operations = [
    ]
