# Generated by Django 4.2.19 on 2025-05-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0162_merge_20250412_1519"),
    ]

    operations = [
        migrations.AddField(
            model_name="examprintconfig",
            name="break_all_questions",
            field=models.BooleanField(
                default=False,
                help_text="Se ativado, força a quebra de página em todas as questões exceto a primeira.",
                verbose_name="Força quebra de página em todas as questões",
            ),
        ),
    ]
