# Generated by Django 4.2.19 on 2025-04-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0162_merge_20250412_1519"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="has_customize_application",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Essa opção adiciona um novo campo no cadastro de uma aplicação que permite criar novas nomenclaturas para aplicações",
                verbose_name="tem customização de tipo de aplicação",
            ),
        ),
    ]
