# Generated by Django 4.0.6 on 2025-05-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0162_merge_20250412_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='enabled_new_answer_correction',
            field=models.BooleanField(default=False, verbose_name='habilitado novo layout de correção?'),
        ),
    ]
