# Generated by Django 4.2.19 on 2025-04-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0162_merge_20250412_1519"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="notify_teacher_review",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Envia email para professores marcados especificamente como revisores de uma solicitação",
                verbose_name="Notificar professores para revisão",
            ),
        ),
    ]
