# Generated by Django 4.2.19 on 2025-04-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0163_client_notify_teacher_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="notify_teacher_review",
        ),
    ]
