# Generated by Django 4.2.19 on 2025-05-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0163_examprintconfig_add_page_number'),
        ('clients', '0164_remove_client_notify_teacher_review'),
    ]

    operations = [
    ]
