# Generated by Django 4.2.19 on 2025-05-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0163_client_has_customize_application'),
        ('clients', '0163_examprintconfig_break_all_questions'),
        ('clients', '0165_merge_20250519_1533'),
    ]

    operations = [
    ]
