# Generated by Django 4.2.19 on 2025-05-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0165_merge_20250519_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprintconfig',
            name='break_alternatives',
            field=models.BooleanField(default=False, help_text='Se ativado, quebra as alternativas entre páginas', verbose_name='Quebra de alternativas'),
        ),
    ]
