# Generated by Django 4.2.19 on 2025-05-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0166_merge_20250527_0930"),
    ]

    operations = [
        migrations.AddField(
            model_name="confignotification",
            name="candency_send_email",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Diariamente"),
                    (1, "1 dia antes"),
                    (2, "2 dias antes"),
                    (3, "3 dias antes"),
                ],
                default=0,
                help_text="Define a cadência para o envio de e-mails de cobrança aos professores.",
                verbose_name="Cadência de envio de e-mail",
            ),
        ),
        migrations.AddField(
            model_name="confignotification",
            name="response_correction_notification",
            field=models.BooleanField(
                default=False,
                help_text="Ao marcar esta opção, os professores serão notificados alguns dias após a data de entrega dos cadernos.",
                verbose_name="Notificar correção de respostas",
            ),
        ),
        migrations.AlterField(
            model_name="confignotification",
            name="send_notification",
            field=models.BooleanField(
                default=False,
                help_text="Ao marcar esta opção, os professores serão notificados alguns dias antes da data de entrega dos cadernos.",
                verbose_name="Notificações de Elaboração de Itens",
            ),
        ),
    ]
