# Generated by Django 4.2.19 on 2025-05-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0163_client_enabled_new_answer_correction'),
        ('clients', '0166_examprintconfig_break_alternatives'),
        ('clients', '0166_merge_20250527_0930'),
    ]

    operations = [
    ]
