# Generated by Django 4.2.19 on 2025-06-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0167_confignotification_candency_send_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confignotification',
            name='candency_send_email',
        ),
        migrations.AddField(
            model_name='confignotification',
            name='cadence_send_email',
            field=models.SmallIntegerField(choices=[(0, 'Diariamente'), (1, '1 dia antes'), (2, '2 dias antes'), (3, '3 dias antes')], default=0, help_text='Define a cadência para o envio de e-mails de cobrança aos professores a partir da data de expiração.', verbose_name='Cadência de envio de e-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='has_dashboard',
            field=models.BooleanField(default=False, verbose_name='Tem acesso aos dashboards antigos'),
        ),
        migrations.AlterField(
            model_name='client',
            name='has_dashboards',
            field=models.BooleanField(default=False, verbose_name='Tem acesso aos dashboards novos'),
        ),
        migrations.AlterField(
            model_name='confignotification',
            name='response_correction_notification',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, os professores serão notificados sobre as suas correções de respostas pendentes.', verbose_name='Notificar correção de respostas'),
        ),
    ]
