# Generated by Django 4.2.19 on 2025-06-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0167_merge_20250531_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_generation_dashboard',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última geração dos novos dashboards'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_generation_followup_dashboard',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última geração de dashboard de acompanhamento'),
        ),
    ]
