# Generated by Django 4.2.19 on 2025-06-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0167_merge_20250531_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='enabled_new_answer_correction',
            field=models.BooleanField(default=True, verbose_name='habilitado novo layout de correção?'),
        ),
        migrations.AlterField(
            model_name='client',
            name='enabled_new_answer_sheet_experience',
            field=models.BooleanField(default=True, verbose_name='habilitado nova experiência de gabarito?'),
        ),
    ]
