# Generated by Django 4.2.19 on 2025-06-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0167_merge_20250531_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquestionsconfiguration',
            name='can_change_grade_with_existing_questions',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, os coordenadores poderão alterar a série da solicitação de questões, mesmo se já houver questões existentes.', verbose_name='Permitir trocar a série da solicitação quando já existir questoes.'),
        ),
    ]
