# Generated by Django 4.2.19 on 2025-06-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0168_alter_client_enabled_new_answer_correction_and_more'),
        ('clients', '0168_client_last_generation_dashboard_and_more'),
    ]

    operations = [
    ]
