# Generated by Django 4.2.19 on 2025-06-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0168_clientquestionsconfiguration_can_change_grade_with_existing_questions'),
        ('clients', '0169_merge_20250617_1702'),
    ]

    operations = [
    ]
