# Generated by Django 4.2.19 on 2025-06-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0170_merge_20250626_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientquestionsconfiguration',
            name='can_change_grade_with_existing_questions',
            field=models.BooleanField(default=False, help_text='Ao marcar esta opção, os coordenadores poderão alterar a série da solicitação de questões, mesmo se já houver questões existentes.', verbose_name='Permitir trocar a série da solicitação quando já existir questões.'),
        ),
    ]
