# Generated by Django 4.2.19 on 2025-06-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0168_remove_confignotification_candency_send_email_and_more'),
        ('clients', '0171_alter_clientquestionsconfiguration_can_change_grade_with_existing_questions'),
    ]

    operations = [
    ]
