# Generated by Django 4.2.19 on 2025-07-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0172_merge_20250628_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_cloze_question',
            field=models.BooleanField(default=False, verbose_name='Tem acesso a questões de preencher lacunas'),
        ),
    ]
