# Generated by Django 3.2.3 on 2021-07-17 14:09

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspectors', '0009_inspector_is_discipline_coordinator'),
        ('applications', '0028_applicationstudent_empty_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStudentLevelQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('performance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Performance')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Fácil'), (1, 'Médio'), (2, 'Difícil'), (3, 'Indefinido')])),
                ('application_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicationstudent', verbose_name='Aplicação do Aluno')),
                ('teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectors.teachersubject')),
            ],
            options={
                'unique_together': {('application_student', 'teacher_subject', 'level')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
