# Generated by Django 3.2.3 on 2021-07-21 18:26

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20210126_1340'),
        ('inspectors', '0009_inspector_is_discipline_coordinator'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubjectApplicationLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('performance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Performance')),
                ('date', models.DateField(verbose_name='Data da aplicação')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass')),
                ('teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectors.teachersubject')),
            ],
            options={
                'unique_together': {('date', 'teacher_subject', 'school_class')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
