# Generated by Django 3.2.3 on 2021-07-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_classsubjectapplicationlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubjectapplicationlevel',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Fácil'), (1, 'Médio'), (2, 'Difícil'), (3, 'Indefinido')], default=0),
        ),
    ]
