# Generated by Django 3.2.3 on 2021-07-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20210126_1340'),
        ('applications', '0035_merge_20210710_2112'),
        ('inspectors', '0009_inspector_is_discipline_coordinator'),
        ('analytics', '0004_alter_classsubjectapplicationlevel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubjectapplicationlevel',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.application', verbose_name='Aplicação'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubjectapplicationlevel',
            unique_together={('application', 'teacher_subject', 'school_class', 'level')},
        ),
        migrations.RemoveField(
            model_name='classsubjectapplicationlevel',
            name='date',
        ),
    ]
