# Generated by Django 4.0.2 on 2022-06-17 16:24

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0060_merge_20220617_1151'),
        ('exams', '0084_exam_show_ranking_historicalexam_show_ranking'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('analytics', '0011_applicationstudentperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPerformances',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('performance_type', models.SmallIntegerField(choices=[(0, 'Desempenho'), (1, 'Desempenho na turma'), (2, 'Desempenho na bncc'), (3, 'Desempenho na prova')], verbose_name='Tipo de performance')),
                ('performance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('object_id', models.UUIDField()),
                ('application_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.applicationstudent', verbose_name='Aplicação do aluno')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='Prova')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='ApplicationStudentPerformance',
        ),
    ]
