# Generated by Django 4.0.2 on 2022-06-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_genericperformances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericperformances',
            name='performance_type',
        ),
    ]
