# Generated by Django 4.0.2 on 2022-06-17 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_alter_course_created_at_alter_coursetype_created_at_and_more'),
        ('analytics', '0013_remove_genericperformances_performance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericperformances',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass', verbose_name='Turma'),
        ),
    ]
