# Generated by Django 4.0.2 on 2022-06-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_genericperformances_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericperformances',
            name='process_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Tempo de processamento'),
        ),
    ]
