# Generated by Django 4.0.2 on 2022-06-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_genericperformances_process_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericperformances',
            name='process_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Tempo de processamento'),
        ),
    ]
