# Generated by Django 4.0.2 on 2022-06-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('analytics', '0016_alter_genericperformances_process_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericperformances',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='genericperformances',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genericperformances',
            name='performance',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Desempenho'),
        ),
    ]
