# Generated by Django 4.0.2 on 2022-06-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_alter_genericperformances_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericperformances',
            name='students_quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
