# Generated by Django 4.0.2 on 2022-06-20 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_genericperformances_students_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericperformances',
            old_name='students_quantity',
            new_name='weight',
        ),
    ]
