# Generated by Django 4.0.2 on 2022-08-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_rename_students_quantity_genericperformances_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericperformances',
            name='histogram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Histograma'),
        ),
    ]
