# Generated by Django 4.0.2 on 2022-09-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_genericperformances_histogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericperformances',
            name='histogram',
            field=models.JSONField(blank=True, max_length=255, null=True, verbose_name='Histograma'),
        ),
    ]
