# Generated by Django 4.0.6 on 2022-10-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_responsible_email'),
        ('analytics', '0021_alter_genericperformances_histogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericperformances',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Aluno'),
        ),
    ]
