# Generated by Django 4.0.6 on 2022-10-23 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0017_delete_topicexamperformance'),
        ('analytics', '0022_genericperformances_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericperformances',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Disciplina'),
        ),
    ]
