# Generated by Django 4.0.6 on 2023-08-31 21:34

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0130_merge_20230821_1730'),
        ('inspectors', '0035_inspector_has_question_formatter'),
        ('classes', '0020_alter_grade_options'),
        ('clients', '0102_client_has_followup_dashboard'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('analytics', '0023_genericperformances_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPerformancesFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deadline', models.DateField(verbose_name='Data final para correção de respostas')),
                ('quantity', models.IntegerField(default=0, verbose_name='Pendencias')),
                ('total', models.IntegerField(default=0, verbose_name='Total')),
                ('process_time', models.DurationField(blank=True, null=True, verbose_name='Tempo de processamento')),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('coordination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.schoolcoordination', verbose_name='Coordenação')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='Caderno')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspectors.inspector', verbose_name='Professor')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass', verbose_name='Turma')),
            ],
            options={
                'unique_together': {('exam', 'inspector'), ('exam', 'school_class')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
