# Generated by Django 4.0.6 on 2023-08-31 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0102_client_has_followup_dashboard'),
        ('analytics', '0024_genericperformancesfollowup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genericperformancesfollowup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='unity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.unity', verbose_name='Unidade'),
        ),
        migrations.RemoveField(
            model_name='genericperformancesfollowup',
            name='exam',
        ),
    ]
