# Generated by Django 4.0.6 on 2023-09-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0035_inspector_has_question_formatter'),
        ('analytics', '0025_alter_genericperformancesfollowup_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericperformancesfollowup',
            name='inspector',
        ),
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='inspectors',
            field=models.ManyToManyField(blank=True, to='inspectors.inspector', verbose_name='Professor'),
        ),
    ]
