# Generated by Django 4.0.6 on 2023-09-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0026_remove_genericperformancesfollowup_inspector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='question_type',
            field=models.SmallIntegerField(default=1, verbose_name='Tipo de questão'),
        ),
    ]
