# Generated by Django 4.0.6 on 2023-09-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0027_genericperformancesfollowup_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericperformancesfollowup',
            name='question_type',
        ),
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='discursive_quantity',
            field=models.IntegerField(default=0, verbose_name='Pendencias'),
        ),
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='discursive_total',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='objective_quantity',
            field=models.IntegerField(default=0, verbose_name='Pendencias'),
        ),
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='objective_total',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='genericperformancesfollowup',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
    ]
