# Generated by Django 4.0.6 on 2023-09-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0103_client_last_update_followup_dashboard'),
        ('classes', '0020_alter_grade_options'),
        ('analytics', '0028_remove_genericperformancesfollowup_question_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genericperformancesfollowup',
            unique_together={('object_id', 'deadline', 'unity', 'coordination', 'school_class')},
        ),
    ]
