# Generated by Django 4.0.6 on 2023-09-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0130_merge_20230821_1730'),
        ('analytics', '0029_alter_genericperformancesfollowup_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='discursive_examquestions',
            field=models.ManyToManyField(blank=True, related_name='discursive_performances', to='exams.examquestion', verbose_name='Questões Discursivas'),
        ),
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='objective_examquestions',
            field=models.ManyToManyField(blank=True, related_name='objective_performances', to='exams.examquestion', verbose_name='Questões objetivas'),
        ),
    ]
