# Generated by Django 4.0.6 on 2023-09-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0030_genericperformancesfollowup_discursive_examquestions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Correção de respostas'), (1, 'Envio de cartão de resposta')], default=0, verbose_name='Tipo'),
        ),
    ]
