# Generated by Django 4.0.6 on 2023-09-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0031_genericperformancesfollowup_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericperformancesfollowup',
            name='type',
        ),
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='cards_quantity',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='cards_total',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='discursive_cards_quantity',
            field=models.IntegerField(default=0, verbose_name='Pendencias cartões discursivas'),
        ),
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='discursive_cards_total',
            field=models.IntegerField(default=0, verbose_name='Total cartões discursivas'),
        ),
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='objective_cards_quantity',
            field=models.IntegerField(default=0, verbose_name='Pendencias cartões objetivas'),
        ),
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='objective_cards_total',
            field=models.IntegerField(default=0, verbose_name='Total cartões objetivas'),
        ),
    ]
