# Generated by Django 4.0.6 on 2023-09-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0033_alter_genericperformancesfollowup_cards_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='cards_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Data final para envio de respostas'),
        ),
        migrations.AlterField(
            model_name='genericperformancesfollowup',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Data final para correção de respostas'),
        ),
    ]
