# Generated by Django 4.0.6 on 2023-09-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0105_client_has_sisu_simulator'),
        ('classes', '0021_schoolclass_logo_schoolclass_slug'),
        ('analytics', '0034_genericperformancesfollowup_cards_deadline_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genericperformancesfollowup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='genericperformancesfollowup',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Respostas'), (1, 'Upaload de cartões')], default=0, verbose_name='Tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='genericperformancesfollowup',
            unique_together={('object_id', 'deadline', 'unity', 'coordination', 'school_class', 'type')},
        ),
    ]
