# Generated by Django 4.0.6 on 2024-01-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0035_alter_genericperformancesfollowup_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericperformancesfollowup',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Respostas'), (1, 'Upaload de cartões'), (2, 'Questões solicitadas')], default=0, verbose_name='Tipo'),
        ),
    ]
