# Generated by Django 4.0.6 on 2024-11-28 15:32

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0147_merge_20241030_1617'),
        ('analytics', '0036_alter_genericperformancesfollowup_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetabaseDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Título')),
                ('short_name', models.CharField(max_length=16, verbose_name='Título curto')),
                ('embbed_url', models.URLField(max_length=500, verbose_name='URL pública')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Dashboard Metabase',
                'verbose_name_plural': 'Dashboards Metabase',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
