# Generated by Django 4.0.6 on 2024-11-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0037_metabasedashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metabasedashboard',
            name='short_name',
            field=models.CharField(max_length=32, verbose_name='Título curto'),
        ),
    ]
