# Generated by Django 3.0.7 on 2020-10-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0001_initial'),
        ('applications', '0021_application_exam'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textualanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Question', verbose_name='Questão'),
        ),
        migrations.AddField(
            model_name='textualanswer',
            name='student_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.ApplicationStudent', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='optionanswer',
            name='question_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.QuestionOption', verbose_name='Alternativa'),
        ),
        migrations.AddField(
            model_name='optionanswer',
            name='student_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.ApplicationStudent', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Question', verbose_name='Questão'),
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='student_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.ApplicationStudent', verbose_name='Aluno'),
        ),
    ]
