# Generated by Django 3.0.7 on 2020-11-05 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20201029_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Tempo de resposta'),
        ),
        migrations.AddField(
            model_name='optionanswer',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Tempo de resposta'),
        ),
        migrations.AddField(
            model_name='textualanswer',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Tempo de resposta'),
        ),
    ]
