# Generated by Django 3.0.7 on 2020-11-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20201105_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionanswer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inativa'), (1, 'Ativa')], default=1, verbose_name='Status'),
        ),
    ]
