# Generated by Django 3.0.7 on 2020-12-23 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_application_category'),
        ('answers', '0005_auto_20201203_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionanswer',
            name='student_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_answers', to='applications.ApplicationStudent', verbose_name='Aluno'),
        ),
    ]
