# Generated by Django 3.0.7 on 2021-01-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_application_category'),
        ('questions', '0010_auto_20210111_1706'),
        ('answers', '0006_auto_20201223_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileanswer',
            name='student_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_answers', to='applications.ApplicationStudent', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='textualanswer',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Texto da resposta'),
        ),
        migrations.AlterField(
            model_name='textualanswer',
            name='student_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='textual_answers', to='applications.ApplicationStudent', verbose_name='Aluno'),
        ),
        migrations.AlterUniqueTogether(
            name='textualanswer',
            unique_together={('question', 'student_application')},
        ),
    ]
