# Generated by Django 3.0.7 on 2021-01-22 20:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0007_auto_20210119_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textualanswer',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Texto da resposta'),
        ),
    ]
