# Generated by Django 3.0.7 on 2021-02-17 17:43

from django.db import migrations, models
import fiscallizeon.answers.models
import fiscallizeon.core.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0008_auto_20210122_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileanswer',
            name='arquivo',
            field=models.FileField(storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to=fiscallizeon.answers.models.material_file_directory_path, verbose_name='Arquivo anexado'),
        ),
    ]
