# Generated by Django 3.0.7 on 2021-02-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0009_auto_20210217_1443'),
        ('answers', '0009_auto_20210212_1437'),
    ]

    operations = [
    ]
