# Generated by Django 3.0.7 on 2021-03-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0010_merge_20210221_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionanswer',
            name='index_alternative',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Posição da questão na prova'),
        ),
    ]
