# Generated by Django 3.0.7 on 2021-04-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0011_optionanswer_index_alternative'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='teacher_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Correção do professor'),
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='teacher_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota atribuída'),
        ),
        migrations.AddField(
            model_name='textualanswer',
            name='teacher_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Correção do professor'),
        ),
        migrations.AddField(
            model_name='textualanswer',
            name='teacher_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota atribuída'),
        ),
    ]
