# Generated by Django 3.0.7 on 2021-05-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0012_auto_20210403_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileanswer',
            name='teacher_grade',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Nota atribuída'),
        ),
        migrations.AlterField(
            model_name='textualanswer',
            name='teacher_grade',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Nota atribuída'),
        ),
    ]
