# Generated by Django 3.2.4 on 2021-09-13 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0037_auto_20210813_1511'),
        ('answers', '0014_optionanswer_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionanswer',
            name='student_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='option_answers', to='applications.applicationstudent', verbose_name='Aluno'),
        ),
    ]
