# Generated by Django 3.2.3 on 2021-09-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0014_optionanswer_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='highlighter',
            field=models.BooleanField(blank=True, null=True, verbose_name='Via QRCode'),
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
