# Generated by Django 3.2.3 on 2021-09-07 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0015_auto_20210907_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileanswer',
            old_name='highlighter',
            new_name='send_on_qrcode',
        ),
    ]
