# Generated by Django 3.2.4 on 2021-09-13 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0038_auto_20210913_1535'),
        ('answers', '0015_alter_optionanswer_student_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionanswer',
            name='student_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_answers', to='applications.applicationstudent', verbose_name='Aluno'),
        ),
    ]
