# Generated by Django 3.2.3 on 2021-09-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0016_rename_highlighter_fileanswer_send_on_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='reload_page',
            field=models.BooleanField(default=False),
        ),
    ]
