# Generated by Django 3.2.3 on 2021-09-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0017_fileanswer_reload_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileanswer',
            name='reload_page',
            field=models.BooleanField(blank=True, default=False, verbose_name='Página atualizada'),
        ),
        migrations.AlterField(
            model_name='fileanswer',
            name='send_on_qrcode',
            field=models.BooleanField(blank=True, default=False, verbose_name='Via QRCode'),
            preserve_default=False,
        ),
    ]
