# Generated by Django 3.2.3 on 2021-09-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0018_auto_20210907_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileanswer',
            name='send_on_qrcode',
            field=models.BooleanField(blank=True, default=False, verbose_name='Via QRCode'),
        ),
    ]
