# Generated by Django 3.2.3 on 2021-09-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0019_alter_fileanswer_send_on_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileanswer',
            name='reload_page',
        ),
        migrations.AlterField(
            model_name='fileanswer',
            name='send_on_qrcode',
            field=models.BooleanField(default=False, verbose_name='Via QRCode'),
        ),
    ]
