# Generated by Django 3.2.4 on 2021-09-17 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0017_alter_optionanswer_student_application'),
        ('answers', '0020_auto_20210908_1529'),
    ]

    operations = [
    ]
