# Generated by Django 3.2.4 on 2021-12-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0021_merge_20210917_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='annotations_teaher',
            field=models.JSONField(blank=True, null=True, verbose_name='Anotações do professor'),
        ),
    ]
