# Generated by Django 3.2.4 on 2021-12-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0021_merge_20210917_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='img_annotations',
            field=models.JSONField(blank=True, null=True, verbose_name='Anotações das imagens'),
        ),
    ]
