# Generated by Django 3.2.4 on 2022-01-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0022_fileanswer_annotations_teaher'),
        ('answers', '0022_fileanswer_img_annotations'),
    ]

    operations = [
    ]
