# Generated by Django 4.0.2 on 2022-02-24 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answers', '0023_merge_20220106_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='who_corrected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Corrigido por'),
        ),
        migrations.AddField(
            model_name='textualanswer',
            name='who_corrected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Corrigido por'),
        ),
    ]
