# Generated by Django 4.0.2 on 2022-03-31 02:55

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import fiscallizeon.answers.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0072_remove_exam_aggrupate_answers_and_more'),
        ('applications', '0049_alter_application_answer_sheet'),
        ('answers', '0024_fileanswer_who_corrected_textualanswer_who_corrected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileanswer',
            name='arquivo',
            field=models.FileField(upload_to=fiscallizeon.answers.models.material_file_directory_path, verbose_name='Arquivo anexado'),
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('file', models.FileField(upload_to=fiscallizeon.answers.models.material_file_directory_path, verbose_name='Arquivo anexado')),
                ('application_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='applications.applicationstudent', verbose_name='Aplicação do aluno')),
                ('exam_teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='exams.examteachersubject', verbose_name='Anexado por')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
