# Generated by Django 4.0.2 on 2022-04-01 14:03

from django.db import migrations, models
import fiscallizeon.answers.models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0025_alter_fileanswer_arquivo_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='send_on_qrcode',
            field=models.BooleanField(default=False, verbose_name='Via QRCode'),
        ),
        migrations.AlterField(
            model_name='fileanswer',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=fiscallizeon.answers.models.material_file_directory_path, verbose_name='Arquivo anexado'),
        ),
    ]
