# Generated by Django 4.0.2 on 2022-04-05 13:18

from django.db import migrations, models
import fiscallizeon.answers.models
import fiscallizeon.core.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0026_attachments_send_on_qrcode_alter_fileanswer_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='file',
            field=models.FileField(storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to=fiscallizeon.answers.models.material_file_directory_path, verbose_name='Arquivo anexado'),
        ),
        migrations.AlterField(
            model_name='fileanswer',
            name='arquivo',
            field=models.FileField(blank=True, null=True, storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to=fiscallizeon.answers.models.material_file_directory_path, verbose_name='Arquivo anexado'),
        ),
    ]
