# Generated by Django 4.0.2 on 2022-06-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0031_alter_attachments_id_alter_fileanswer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='corrected_but_no_answer',
            field=models.BooleanField(blank=True, default=False, verbose_name='Corrigida mas sem resposta do aluno'),
        ),
    ]
