# Generated by Django 4.0.2 on 2022-06-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0032_fileanswer_corrected_but_no_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='textualanswer',
            name='corrected_but_no_answer',
            field=models.BooleanField(blank=True, default=False, verbose_name='Resposta corrigida mas sem resposta do aluno'),
        ),
    ]
