# Generated by Django 4.0.2 on 2022-07-12 23:11

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0038_alter_question_institution'),
        ('exams', '0084_exam_show_ranking_historicalexam_show_ranking'),
        ('applications', '0060_merge_20220620_2235'),
        ('answers', '0033_textualanswer_corrected_but_no_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetryAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('application_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.applicationstudent', verbose_name='aluno')),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.examquestion', verbose_name='questão na prova')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.questionoption', verbose_name='alternativa')),
            ],
            options={
                'verbose_name': 'resposta refeita',
                'verbose_name_plural': 'respostas refeitas',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
