# Generated by Django 4.0.2 on 2022-09-19 13:34

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0065_remove_applicationstudentcompetencesperformance_application_student_and_more'),
        ('answers', '0036_fileanswer_correction_file_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(max_length=8, verbose_name='Código do comprovante')),
                ('exam_name', models.CharField(max_length=150, verbose_name='Nome do caderno')),
                ('start_date', models.DateTimeField(verbose_name='Data inicial da aplicação')),
                ('end_date', models.DateTimeField(verbose_name='Data final da aplicação')),
                ('is_randomized', models.BooleanField(default=False, verbose_name='É randomizado')),
                ('answers_json', models.JSONField(verbose_name='Respostas das alternativas')),
                ('application_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proofs', to='applications.applicationstudent', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Comprovante de resposta',
                'verbose_name_plural': 'Comprovantes de respostas',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
