# Generated by Django 4.0.2 on 2022-09-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0037_proofanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofanswer',
            name='group_attachments',
            field=models.BooleanField(default=False, verbose_name='Os anexos são agrupados'),
        ),
    ]
