# Generated by Django 4.0.6 on 2023-08-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0039_alter_fileanswer_teacher_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='empty',
            field=models.BooleanField(default=False, verbose_name='Deixou em branco'),
        ),
        migrations.AddField(
            model_name='textualanswer',
            name='empty',
            field=models.BooleanField(default=False, verbose_name='Deixou em branco'),
        ),
    ]
