# Generated by Django 4.0.6 on 2024-01-25 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0056_alter_question_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0091_merge_20230926_1305'),
        ('answers', '0042_alter_historicalretryanswer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Valor do somatório')),
                ('empty', models.BooleanField(default=False, verbose_name='Resposta em branco ou anulada')),
                ('grade', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Nota calculada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sum_answers', to='questions.question', verbose_name='Questão')),
            ],
            options={
                'verbose_name': 'Resposta de somatório',
                'verbose_name_plural': 'Respostas de somatório',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='historicalretryanswer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical resposta refeita', 'verbose_name_plural': 'historical respostas refeitas'},
        ),
        migrations.AlterField(
            model_name='historicalretryanswer',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.CreateModel(
            name='SumAnswerQuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('checked', models.BooleanField(default=False, verbose_name='Marcada')),
                ('question_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionoption', verbose_name='Alternativa')),
                ('sum_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.sumanswer', verbose_name='Resposta de somatório')),
            ],
            options={
                'verbose_name': 'Resposta de alternativa de somatório',
                'verbose_name_plural': 'Respostas de alternativas de somatório',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='sumanswer',
            name='question_options',
            field=models.ManyToManyField(through='answers.SumAnswerQuestionOption', to='questions.questionoption', verbose_name='Alternativas'),
        ),
        migrations.AddField(
            model_name='sumanswer',
            name='student_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sum_answers', to='applications.applicationstudent', verbose_name='Aluno'),
        ),
    ]
