# Generated by Django 4.0.6 on 2024-02-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0043_sumanswer_alter_historicalretryanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalretryanswer',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical resposta refeita'},
        ),
        migrations.AlterField(
            model_name='historicalretryanswer',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
