# Generated by Django 4.0.6 on 2024-04-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0044_alter_historicalretryanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalretryanswer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical resposta refeita', 'verbose_name_plural': 'historical respostas refeitas'},
        ),
        migrations.AlterField(
            model_name='historicalretryanswer',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
