# Generated by Django 4.0.6 on 2024-11-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0189_merge_20241029_1055'),
        ('answers', '0047_alter_historicalretryanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='exam_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exams.examquestion', verbose_name='Questão da prova'),
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, verbose_name='Nota percentual'),
        ),
        migrations.AddField(
            model_name='textualanswer',
            name='exam_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exams.examquestion', verbose_name='Questão da prova'),
        ),
        migrations.AddField(
            model_name='textualanswer',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, verbose_name='Nota percentual'),
        ),
    ]
