# Generated by Django 4.0.6 on 2024-10-14 20:40

from django.db import migrations, models
import fiscallizeon.answers.models
import fiscallizeon.core.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0047_alter_historicalretryanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='teacher_audio_feedback',
            field=models.FileField(blank=True, null=True, storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to=fiscallizeon.answers.models.teachers_audio_firectory_path, verbose_name='Arquivo de audio do professor'),
        ),
    ]
