# Generated by Django 4.0.6 on 2024-10-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0048_fileanswer_teacher_audio_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='essay_was_corrected',
            field=models.BooleanField(default=False, verbose_name='A redação foi corrigida'),
        ),
    ]
