# Generated by Django 4.0.6 on 2024-10-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0049_fileanswer_essay_was_corrected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileanswer',
            name='essay_was_corrected',
            field=models.BooleanField(blank=True, default=False, verbose_name='A redação foi corrigida'),
        ),
    ]
