# Generated by Django 4.0.6 on 2025-01-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0048_fileanswer_exam_question_fileanswer_grade_and_more'),
        ('answers', '0050_alter_fileanswer_essay_was_corrected'),
    ]

    operations = [
    ]
