# Generated by Django 4.0.6 on 2024-12-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0050_alter_fileanswer_essay_was_corrected'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='ai_grade',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, verbose_name='Nota atribuída pela IA'),
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='ai_student_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback para o aluno'),
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='ai_teacher_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback para o professor'),
        ),
    ]
