# Generated by Django 4.0.6 on 2024-12-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0051_fileanswer_ai_grade_fileanswer_ai_student_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='ai_suggestion_accepted',
            field=models.BooleanField(default=False, verbose_name='Sugestão da IA aceita pelo professor'),
        ),
    ]
