# Generated by Django 4.0.6 on 2025-01-11 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0051_merge_20250107_1911'),
        ('answers', '0052_fileanswer_ai_suggestion_accepted'),
    ]

    operations = [
    ]
