# Generated by Django 3.2.4 on 2021-08-18 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0018_client_has_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('high_school', models.BooleanField(default=False, verbose_name='Ensino médio')),
                ('elementary_school', models.BooleanField(default=False, verbose_name='Ensino fundamental')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('content', tinymce.models.HTMLField(verbose_name='Texto da notificação')),
                ('start_date', models.DateTimeField(verbose_name='Data de início')),
                ('end_date', models.DateTimeField(verbose_name='Data de fim')),
                ('target_segment', models.CharField(choices=[('coordination', 'Coordenações'), ('student', 'Alunos'), ('inspector', 'Fiscais'), ('teacher', 'Professores')], max_length=255, verbose_name='Segmento de usuários')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Funcionalidade'), (1, 'Informação')], default=1, verbose_name='Categoria')),
                ('clients', models.ManyToManyField(blank=True, to='clients.Client', verbose_name='Clientes')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification', verbose_name='Notificação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Visualizaçao de notificação',
                'verbose_name_plural': 'Visualizações de notificações',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='notification',
            name='viewed_by',
            field=models.ManyToManyField(through='notifications.NotificationUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
