# Generated by Django 3.2.4 on 2021-08-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='show_modal',
            field=models.BooleanField(default=False, verbose_name='Mostrar modal automaticamente'),
        ),
    ]
