# Generated by Django 3.2.4 on 2021-08-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_show_modal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Função'), (1, 'Aviso')], default=1, verbose_name='Categoria'),
        ),
    ]
