# Generated by Django 4.0.6 on 2023-01-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_id_alter_notificationuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_form',
        ),
        migrations.AddField(
            model_name='notification',
            name='modal_height',
            field=models.CharField(choices=[('auto', 'Automático'), ('40', 'Pequeno'), ('60', 'Médio'), ('85', 'Grande (form)')], default='60', max_length=10, verbose_name='Altura da modal'),
        ),
        migrations.AddField(
            model_name='notification',
            name='modal_width',
            field=models.CharField(choices=[('sm', 'Pequeno'), ('md', 'Médio'), ('lg', 'Grande (form)')], default='md', max_length=10, verbose_name='Largura da modal'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Função'), (1, 'Aviso'), (2, 'Pesquisa (form)')], default=1, verbose_name='Categoria'),
        ),
    ]
