# Generated by Django 4.0.6 on 2023-01-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_remove_notification_is_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Função'), (1, 'Aviso'), (2, 'Pesquisa')], default=1, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='modal_height',
            field=models.CharField(choices=[('auto', 'Automático'), ('40vh', 'Pequeno'), ('60vh', 'Médio'), ('85vh', 'Grande (form)')], default='60vh', max_length=10, verbose_name='Altura da modal'),
        ),
    ]
