# Generated by Django 4.0.6 on 2023-06-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_alter_notificationuser_options_notification_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='show_form',
            field=models.BooleanField(default=False, verbose_name='Mostrar o campo para digitar o feedback'),
        ),
        migrations.AddField(
            model_name='notification',
            name='show_rating',
            field=models.BooleanField(default=False, verbose_name='Mostrar as estrelinhas'),
        ),
    ]
