# Generated by Django 4.0.6 on 2023-06-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_notification_answer_is_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Foi visualizado'),
        ),
    ]
