# Generated by Django 4.0.6 on 2023-06-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_notificationuser_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='persist',
            field=models.BooleanField(default=False, verbose_name='Mostrar modal até o usuário visualizar ou enviar o feedback'),
        ),
    ]
