# Generated by Django 4.0.6 on 2023-06-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_notification_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='delay',
            field=models.SmallIntegerField(default=1, verbose_name='Delay para mostrar a modal (segundos)'),
        ),
    ]
