# Generated by Django 4.0.6 on 2023-06-16 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_alter_notification_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='next_notification',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data que a notificação irá se repetir'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='repeat_days',
            field=models.SmallIntegerField(blank=True, help_text='Deixe 0 (zero) para que a mensagem não seja repetida.', null=True, verbose_name='Em quanto tempo essa mensagem se repete? (em dias)'),
        ),
    ]
