# Generated by Django 4.0.6 on 2023-06-16 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0019_notification_next_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='last_nps_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ultima notificação do NPS'),
            preserve_default=False,
        ),
    ]
