# Generated by Django 4.0.6 on 2023-06-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_notificationuser_last_nps_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='last_nps_date',
            field=models.DateTimeField(verbose_name='Ultima notificação do NPS'),
        ),
    ]
