# Generated by Django 4.0.6 on 2023-06-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0021_alter_notificationuser_last_nps_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='next_notification',
            field=models.DateTimeField(verbose_name='Data que a notificação irá se repetir'),
        ),
    ]
