# Generated by Django 4.0.6 on 2023-06-29 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0022_alter_notification_next_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='next_nps_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da próxima pesquisa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='next_notification',
            field=models.DateTimeField(blank=True, verbose_name='Data que a notificação irá se repetir'),
        ),
    ]
