# Generated by Django 4.0.6 on 2023-06-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0023_notificationuser_next_nps_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationuser',
            name='last_nps_date',
        ),
    ]
