# Generated by Django 4.0.6 on 2023-06-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0024_remove_notificationuser_last_nps_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='is_old',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
