# Generated by Django 4.0.6 on 2023-06-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0025_notificationuser_is_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationuser',
            name='is_old',
        ),
    ]
