# Generated by Django 4.0.6 on 2023-06-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0026_remove_notificationuser_is_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='next_notification',
        ),
    ]
