# Generated by Django 4.0.6 on 2023-07-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0019_alter_notification_model'),
        ('notifications', '0027_remove_notification_next_notification'),
    ]

    operations = [
    ]
