# Generated by Django 4.0.6 on 2023-07-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0028_alter_notification_model'),
        ('notifications', '0028_merge_20230710_1225'),
    ]

    operations = [
    ]
