# Generated by Django 4.0.6 on 2023-10-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0032_alter_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='urls',
            field=models.TextField(blank=True, help_text='Separe por virgula todas as urls onde você deseja chamar essa notificação', null=True, verbose_name='Lista de urls (Separada por virgula)'),
        ),
    ]
