# Generated by Django 4.0.6 on 2023-10-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0033_notification_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='next_nps_date',
            field=models.DateTimeField(blank=True, verbose_name='Data da próxima pesquisa'),
        ),
    ]
