# Generated by Django 4.0.6 on 2023-10-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0034_alter_notificationuser_next_nps_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='feedback_sent',
            field=models.BooleanField(default=False, verbose_name='Enviou o feedback'),
        ),
    ]
