# Generated by Django 4.0.6 on 2023-10-19 13:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0035_notificationuser_feedback_sent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationuser',
            unique_together={('notification', 'user', 'next_nps_date')},
        ),
    ]
