# Generated by Django 4.0.6 on 2023-10-19 13:50

from django.db import migrations, models

def remove_notifications_users(apps, schema_editor):
    NotificationUser = apps.get_model('notifications', 'NotificationUser')
    
    NotificationUser.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0036_alter_notificationuser_unique_together'),
    ]

    operations = [
        migrations.RunPython(remove_notifications_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='notificationuser',
            name='next_nps_date',
            field=models.DateField(blank=True, verbose_name='Data da próxima pesquisa'),
        ),
    ]
