# Generated by Django 4.0.6 on 2023-10-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0037_alter_notificationuser_next_nps_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='especial_trigger',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Depois de diagramar uma prova'), (1, 'Depois ver resultados de um caderno'), (2, 'Depois de enviar notas para Activesoft'), (3, 'Depois de ver resultados de uma aplicação'), (4, 'Depois de atualizar uma questão com pedido de correção')], null=True, verbose_name='Ações específicas para quando criar a notificação'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='trigger',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Depois de criar'), (1, 'Depois de deletar'), (2, 'Depois de atualizar'), (3, 'Antes de criar'), (4, 'Antes de deletar'), (5, 'Antes de atualizar'), (6, 'Na listagem')], null=True, verbose_name='Quando criar a notificação'),
        ),
    ]
