# Generated by Django 4.0.6 on 2023-10-25 12:42

from django.db import migrations, models
import fiscallizeon.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0038_notification_especial_trigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='segments',
            field=fiscallizeon.core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('coordination', 'Coordenações'), ('student', 'Alunos'), ('inspector', 'Fiscais'), ('teacher', 'Professores')], max_length=50, verbose_name='Segmentos de usuário'), blank=True, null=True, size=None),
        ),
    ]
