# Generated by Django 4.0.6 on 2023-10-25 12:57

from django.db import migrations, models
import fiscallizeon.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0039_notification_segments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='target_segment',
        ),
        migrations.AlterField(
            model_name='notification',
            name='segments',
            field=fiscallizeon.core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('coordination', 'Coordenações'), ('student', 'Alunos'), ('inspector', 'Fiscais'), ('teacher', 'Professores'), ('parent', 'Responsáveis'), ('partner', 'Parceiros')], max_length=50, verbose_name='Segmentos de usuário'), blank=True, null=True, size=None, verbose_name='Segmento de usuários'),
        ),
    ]
