# Generated by Django 4.0.6 on 2023-11-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0039_alter_notification_model'),
        ('notifications', '0040_remove_notification_target_segment_and_more'),
    ]

    operations = [
    ]
