# Generated by Django 4.0.6 on 2023-11-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0041_merge_20231121_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='rating',
            field=models.SmallIntegerField(blank=True, default=10, verbose_name='Qual nota você da para esta experiência?'),
        ),
    ]
