# Generated by Django 4.0.6 on 2023-11-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0042_alter_notificationuser_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='nps_type',
            field=models.CharField(blank=True, default='modal', max_length=30, verbose_name='Como mostrar a pesquisa'),
        ),
    ]
