# Generated by Django 4.0.6 on 2023-11-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0043_notification_nps_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='nps_type',
            field=models.CharField(blank=True, choices=[('modal', 'Em Modal'), ('component', 'Componente em baixo da página')], default='modal', max_length=30, verbose_name='Como mostrar a pesquisa'),
        ),
    ]
