# Generated by Django 4.0.6 on 2023-11-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0044_alter_notification_nps_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='especial_trigger',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Depois de diagramar uma prova'), (1, 'Depois ver resultados de um caderno (Coordenação)'), (2, 'Depois de enviar notas para Activesoft'), (3, 'Depois de ver resultados de uma aplicação'), (4, 'Depois de atualizar uma questão com pedido de correção')], null=True, verbose_name='Ações específicas para quando criar a notificação'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='model',
            field=models.CharField(blank=True, choices=[('exams.Exam', 'Cadernos'), ('ExamTemplate', 'Gabarito avulso'), ('questions.Question', 'Questions'), ('students.Student', 'Alunos'), ('inspectors.Inspector', 'Professor'), ('inspectors.Inspector', 'Fiscais')], max_length=100, null=True, verbose_name='Para qual modelo?'),
        ),
    ]
