# Generated by Django 4.0.6 on 2023-11-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0046_alter_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='especial_trigger',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Depois de diagramar uma prova'), (1, 'Depois ver resultados de um caderno (Coordenação)'), (2, 'Depois de enviar notas para Activesoft'), (3, 'Depois de ver resultados de uma aplicação (Aluno)'), (4, 'Depois que o aluno revisar uma questão')], null=True, verbose_name='Ações específicas para quando criar a notificação'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='model',
            field=models.CharField(blank=True, choices=[('exams.Exam', 'Cadernos'), ('applications.Application', 'Aplicação'), ('ApplicationMultiple', 'Multiplas Aplicações'), ('ExamTemplate', 'Gabarito avulso'), ('questions.Question', 'Questions'), ('students.Student', 'Alunos'), ('inspectors.Inspector', 'Professor'), ('Inspector', 'Fiscais')], max_length=100, null=True, verbose_name='Para qual modelo?'),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='next_nps_date',
            field=models.DateField(blank=True, verbose_name='Data da pesquisa'),
        ),
    ]
