# Generated by Django 4.0.6 on 2024-01-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0042_alter_notification_model'),
        ('notifications', '0047_alter_notification_especial_trigger_and_more'),
    ]

    operations = [
    ]
