# Generated by Django 4.0.6 on 2024-01-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0048_merge_20240126_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='model',
            field=models.CharField(blank=True, choices=[('exams.Exam', 'Cadernos'), ('applications.Application', 'Aplicação'), ('ApplicationMultiple', 'Multiplas Aplicações'), ('ExamTemplate', 'Gabarito avulso'), ('questions.Question', 'Questions'), ('students.Student', 'Alunos'), ('inspectors.Inspector', 'Professor'), ('Inspector', 'Fiscais')], max_length=100, null=True, verbose_name='Para qual modelo?'),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='rating',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Qual nota você da para esta experiência?'),
        ),
    ]
