# Generated by Django 4.0.6 on 2024-02-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0049_alter_notification_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('default', 'Padrão'), ('nps', 'NPS'), ('csat', 'CSAT')], default='default', max_length=30, verbose_name='Tipo de notificação'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='show_modal',
            field=models.BooleanField(default=False, verbose_name='Mostrar notificação automaticamente'),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Como podemos melhorar esta experiência?'),
        ),
    ]
