# Generated by Django 4.0.6 on 2024-01-31 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0043_alter_notification_model'),
        ('notifications', '0049_alter_notification_model_and_more'),
    ]

    operations = [
    ]
