# Generated by Django 4.0.6 on 2024-02-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0050_merge_20240131_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='model',
            field=models.CharField(blank=True, choices=[('exams.Exam', 'Cadernos'), ('applications.Application', 'Aplicação'), ('ApplicationMultiple', 'Multiplas Aplicações'), ('ExamTemplate', 'Gabarito avulso'), ('questions.Question', 'Questions'), ('students.Student', 'Alunos'), ('inspectors.Inspector', 'Professor'), ('Inspector', 'Fiscais')], max_length=100, null=True, verbose_name='Para qual modelo?'),
        ),
    ]
