# Generated by Django 4.0.6 on 2024-02-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0050_notification_type_alter_notification_show_modal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='especial_trigger',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Depois de diagramar uma prova'), (1, 'Depois ver resultados de um caderno (Coordenação)'), (5, 'Enquanto ver resultado de um caderno (Coordenação)'), (2, 'Depois de enviar notas para Activesoft'), (3, 'Depois de ver resultados de uma aplicação (Aluno)'), (4, 'Depois que o aluno revisar uma questão')], null=True, verbose_name='Ações específicas para quando criar a notificação'),
        ),
    ]
