# Generated by Django 4.0.6 on 2024-02-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0050_merge_20240131_1452'),
        ('notifications', '0051_alter_notification_model'),
    ]

    operations = [
    ]
