# Generated by Django 4.0.6 on 2024-02-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0051_alter_notification_especial_trigger'),
        ('notifications', '0051_alter_notification_model'),
    ]

    operations = [
    ]
