# Generated by Django 4.0.6 on 2024-02-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0052_merge_20240219_1544'),
        ('notifications', '0052_merge_20240220_1827'),
    ]

    operations = [
    ]
