# Generated by Django 4.0.6 on 2024-10-14 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0054_alter_notification_especial_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='display_until_end_date',
            field=models.BooleanField(blank=True, default=True, verbose_name='Mostrar contador de notificação até a data de fim definida'),
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuários'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Função'), (1, 'Aviso'), (2, 'Pesquisa'), (3, 'IA')], default=1, verbose_name='Categoria'),
        ),
    ]
