# Generated by Django 4.0.6 on 2024-08-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0054_alter_notification_especial_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Função'), (1, 'Aviso'), (2, 'Pesquisa'), (3, 'Onboarding')], default=1, verbose_name='Categoria'),
        ),
    ]
