# Generated by Django 4.0.6 on 2024-10-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0055_alter_notification_category'),
        ('notifications', '0055_notification_display_until_end_date_and_more'),
    ]

    operations = [
    ]
