# Generated by Django 4.0.6 on 2024-11-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0056_merge_20241029_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Função'), (1, 'Aviso'), (2, 'Pesquisa'), (4, 'IA'), (3, 'Onboarding')], default=1, verbose_name='Categoria'),
        ),
    ]
