# Generated by Django 4.0.2 on 2022-07-22 03:34

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0043_client_disable_stripped_answer_sheet'),
        ('answers', '0035_historicalretryanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('maximum_score', models.FloatField()),
                ('step', models.FloatField(default=40)),
            ],
            options={
                'verbose_name': 'Critério de correção',
                'verbose_name_plural': 'Critérios de correção',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TextCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'Correção de texto',
                'verbose_name_plural': 'Correções de texto',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CorrectionTextualAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('note', models.FloatField(default=0)),
                ('correction_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrections.correctioncriterion')),
                ('textual_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.textualanswer')),
            ],
            options={
                'verbose_name': 'Resposta de correção Answer',
                'verbose_name_plural': 'Respostas de correção Answer',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CorrectionFileAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('note', models.FloatField(default=0)),
                ('correction_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrections.correctioncriterion')),
                ('file_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.fileanswer')),
            ],
            options={
                'verbose_name': 'Resposta de correção FileAnswer',
                'verbose_name_plural': 'Respostas de correção FileAnswer',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='correctioncriterion',
            name='text_correction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrections.textcorrection'),
        ),
    ]
