# Generated by Django 4.0.2 on 2022-07-24 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0036_fileanswer_correction_file_answer_and_more'),
        ('corrections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctioncriterion',
            options={'ordering': ('created_at',), 'verbose_name': 'Critério de correção', 'verbose_name_plural': 'Critérios de correção'},
        ),
        migrations.AlterModelOptions(
            name='correctionfileanswer',
            options={'ordering': ('created_at',), 'verbose_name': 'Resposta de correção FileAnswer', 'verbose_name_plural': 'Respostas de correção FileAnswer'},
        ),
        migrations.AlterModelOptions(
            name='correctiontextualanswer',
            options={'ordering': ('created_at',), 'verbose_name': 'Resposta de correção Answer', 'verbose_name_plural': 'Respostas de correção Answer'},
        ),
        migrations.AlterModelOptions(
            name='textcorrection',
            options={'ordering': ('created_at',), 'verbose_name': 'Correção de texto', 'verbose_name_plural': 'Correções de texto'},
        ),
        migrations.AlterField(
            model_name='correctioncriterion',
            name='maximum_score',
            field=models.FloatField(default=0, verbose_name='Pontuação máxima'),
        ),
        migrations.AlterField(
            model_name='correctioncriterion',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='correctioncriterion',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='correctioncriterion',
            name='text_correction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrections.textcorrection', verbose_name='Correção de texto'),
        ),
        migrations.AlterField(
            model_name='correctionfileanswer',
            name='file_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_answers', to='answers.fileanswer'),
        ),
        migrations.AlterField(
            model_name='correctiontextualanswer',
            name='textual_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textual_answers', to='answers.textualanswer'),
        ),
    ]
