# Generated by Django 4.0.2 on 2022-07-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0002_alter_correctioncriterion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correctionfileanswer',
            old_name='note',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='correctiontextualanswer',
            old_name='note',
            new_name='point',
        ),
    ]
