# Generated by Django 4.0.6 on 2024-09-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0003_rename_note_correctionfileanswer_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctioncriterion',
            name='color',
            field=models.CharField(blank=True, default='#FAC515', max_length=10, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='correctioncriterion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='correctioncriterion',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome abreviado'),
        ),
    ]
