# Generated by Django 4.0.6 on 2024-09-28 02:17

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0004_correctioncriterion_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionDeviation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('short_name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('score', models.FloatField(default=0, verbose_name='Pontuação máxima')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrections.correctioncriterion', verbose_name='Critério de correção')),
            ],
            options={
                'verbose_name': 'Desvio de correção',
                'verbose_name_plural': 'Desvios de correção',
                'ordering': ('created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
