# Generated by Django 4.0.6 on 2024-10-21 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0143_merge_20240920_1822'),
        ('corrections', '0005_correctiondeviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctiondeviation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='clients.client'),
        ),
    ]
