# Generated by Django 3.0.7 on 2021-02-12 17:37

from django.db import migrations, models
import fiscallizeon.core.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to='avatars/'),
        ),
    ]
