# Generated by Django 4.0.6 on 2023-05-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temporarily_inactive',
            field=models.BooleanField(default=False, verbose_name='temporariamente inativo'),
        ),
    ]
