# Generated by Django 4.0.6 on 2023-06-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_temporarily_inactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='temporarily_inactive',
            field=models.BooleanField(default=False),
        ),
    ]
