# Generated by Django 4.0.6 on 2023-10-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_temporarily_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept_terms_of_question_import',
            field=models.BooleanField(blank=True, default=False, verbose_name='Aceitou os termos da importação de questão'),
        ),
    ]
