# Generated by Django 4.0.6 on 2023-12-18 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_accept_terms_of_question_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOTokenUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('refresh_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('expire_in', models.DateTimeField(verbose_name='Expira em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
