# Generated by Django 4.0.6 on 2023-12-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_accept_terms_of_question_import'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'permissions': (('can_change_permissions', 'Pode alterar permissões'),), 'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
    ]
