# Generated by Django 4.0.6 on 2023-12-21 20:50

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clients', '0111_merge_20231203_1412'),
        ('accounts', '0009_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('segment', models.CharField(choices=[('coordination', 'Coordenações'), ('student', 'Alunos'), ('inspector', 'Fiscais'), ('teacher', 'Professores'), ('partner', 'Parceiro'), ('parent', 'Responsáveis')], max_length=50, verbose_name='Segmentos de usuários')),
                ('default', models.BooleanField(blank=True, default=False, verbose_name='Grupo padrão')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_groups', to='clients.client')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'Grupo personalizado',
                'verbose_name_plural': 'Grupos personalizados',
                'unique_together': {('name', 'client')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.customgroup', verbose_name='Grupos customizados'),
        ),
    ]