# Generated by Django 4.0.6 on 2023-12-23 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_ssotokenuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssotokenuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
