# Generated by Django 4.0.6 on 2024-01-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_ssotokenuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_ai_credits',
            field=models.SmallIntegerField(blank=True, default=10, verbose_name='Créditos diários'),
        ),
    ]
