# Generated by Django 4.0.6 on 2024-02-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_ssotokenuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='temporarily_inactive',
            field=models.BooleanField(default=False, verbose_name='temporariamente inativo'),
        ),
    ]
