# Generated by Django 4.0.6 on 2023-12-22 15:48

from django.db import migrations, models
from django.core.management import call_command

def run_custom_command(apps, schema_editor):
    pass
    # Chame o comando personalizado aqui
    # call_command('create_groups')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customgroup_user_custom_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.customgroup', verbose_name='Grupos de permissão'),
        ),
        migrations.RunPython(run_custom_command),
    ]
