# Generated by Django 4.0.6 on 2024-01-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_ssotokenuser_user'),
        ('accounts', '0011_alter_user_custom_groups'),
    ]

    operations = [
    ]
