# Generated by Django 4.0.6 on 2024-01-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_daily_ai_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daily_ai_credits',
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_terms_of_intellectual_rights_of_questions',
            field=models.BooleanField(blank=True, default=False, verbose_name='Aceitou os termos da importação de questão'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_ai_credits',
            field=models.SmallIntegerField(blank=True, default=15, verbose_name='Créditos diários'),
        ),
        migrations.AddField(
            model_name='user',
            name='how_did_you_meet_us',
            field=models.CharField(blank=True, choices=[('internet', 'Busca da internet'), ('social_media', 'Nas redes sociais'), ('friends', 'Amigos ou familiares'), ('others', 'Outros')], max_length=40, verbose_name='Como você nos conheceu?'),
        ),
        migrations.AddField(
            model_name='user',
            name='how_did_you_meet_us_form',
            field=models.CharField(blank=True, max_length=254, verbose_name='Você poderia especificar? (Opcional)'),
        ),
        migrations.AddField(
            model_name='user',
            name='schools',
            field=models.JSONField(blank=True, null=True, verbose_name='Escolas'),
        ),
    ]
