# Generated by Django 4.0.6 on 2024-01-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_daily_ai_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_ai_credits',
            field=models.SmallIntegerField(blank=True, default=15, verbose_name='Crédito mensal'),
        ),
    ]
