# Generated by Django 4.0.6 on 2024-02-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_temporarily_inactive'),
        ('accounts', '0012_merge_20240108_1440'),
    ]

    operations = [
    ]
