# Generated by Django 4.0.6 on 2024-02-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_is_freemium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schools',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Escolas'),
        ),
    ]
