# Generated by Django 4.0.6 on 2024-02-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_schools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schools',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Escola(as)'),
        ),
    ]
