# Generated by Django 4.0.6 on 2024-02-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interested_in_purchasing_more_credits',
            field=models.BooleanField(blank=True, default=False, verbose_name='Tem interesse em comprar mais créditos'),
        ),
    ]
