# Generated by Django 4.0.6 on 2024-02-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merge_20240216_1705'),
        ('accounts', '0017_user_interested_in_purchasing_more_credits'),
    ]

    operations = [
    ]
