# Generated by Django 4.0.6 on 2024-03-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'permissions': (('can_change_permissions', 'Pode alterar permissões'), ('view_grade_map_dashboard', 'Pode visualizar o mapão de notas'), ('view_tri_dashboard', 'Pode visualizar o dashboard de TRI'), ('view_followup_dashboard', 'Pode visualizar dashboard de acompanhamento'), ('view_administration_dashboard', 'Pode visualizar o dashboard administrativo')), 'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
    ]
