# Generated by Django 4.0.6 on 2024-07-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'permissions': (('can_change_permissions', 'Pode alterar permissões'), ('view_grade_map_dashboard', 'Pode visualizar o mapão de notas'), ('view_tri_dashboard', 'Pode visualizar o dashboard de TRI'), ('view_followup_dashboard', 'Pode visualizar dashboard de acompanhamento'), ('view_administration_dashboard', 'Pode visualizar o dashboard administrativo'), ('view_dashboards', 'Pode visualizar o novo dashboard de acompanhamento'), ('can_use_hijack', 'Pode usar o hijack na listagem de professores/membros/alunos e etc...')), 'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
    ]
