# Generated by Django 4.0.6 on 2024-07-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_options'),
        ('accounts', '0022_user_can_request_ai_questions'),
    ]

    operations = [
    ]
