# Generated by Django 4.0.6 on 2024-10-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_merge_20240724_1200'),
        ('accounts', '0023_user_onboarding_responsible'),
    ]

    operations = [
    ]
