# Generated by Django 4.0.6 on 2024-11-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_merge_20241025_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color_mode_theme',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Cinza'), (1, 'Verde'), (2, 'Azul'), (3, 'Roxo'), (4, 'Rosa'), (5, 'Vermelho'), (6, 'Laranja'), (7, 'Amarelo')], null=True, verbose_name='cor do tema'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_viewed_starter_onboarding',
            field=models.BooleanField(default=False, verbose_name='já visualizou a integração inicial?'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='como gostaria de ser chamado(a)?'),
        ),
    ]
