# Generated by Django 4.2.18 on 2025-02-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_user_two_factor_enabled_twofactorauth'),
        ('accounts', '0027_user_mood_historicaluser'),
    ]

    operations = [
    ]
