# Generated by Django 4.2.18 on 2025-02-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_merge_20250210_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='Habilitação da autenticação de dois fatores'),
        ),
    ]
