# Generated by Django 4.2.18 on 2025-02-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_historicaluser_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='has_app_access',
            field=models.BooleanField(default=False, verbose_name='Pode acessar o APP'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_app_access',
            field=models.BooleanField(default=False, verbose_name='Pode acessar o APP'),
        ),
    ]
