# Generated by Django 4.2.19 on 2025-03-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_historicaluser_color_mode_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='background',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='background'),
        ),
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='background'),
        ),
    ]
