# Generated by Django 4.2.19 on 2025-03-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_historicaluser_background_user_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='mood',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Feliz'), (6, 'Grato'), (8, 'Contente'), (13, 'Entediado'), (12, 'Envergonhado'), (15, 'Triste'), (17, 'Irritado'), (18, 'Confuso'), (1, 'Radiante'), (2, 'Divertido'), (3, 'Hilariante'), (4, 'Brincalhão'), (7, 'Satisfeito'), (9, 'Inocente'), (10, 'Encantado'), (0, 'Afetuoso'), (11, 'Encantado'), (14, 'Exausto'), (16, 'Desolado'), (19, 'Tenso'), (20, 'Caveira'), (21, 'Alienígena'), (22, 'Com frio'), (23, 'Gato'), (24, 'Robô')], null=True, verbose_name='humor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mood',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Feliz'), (6, 'Grato'), (8, 'Contente'), (13, 'Entediado'), (12, 'Envergonhado'), (15, 'Triste'), (17, 'Irritado'), (18, 'Confuso'), (1, 'Radiante'), (2, 'Divertido'), (3, 'Hilariante'), (4, 'Brincalhão'), (7, 'Satisfeito'), (9, 'Inocente'), (10, 'Encantado'), (0, 'Afetuoso'), (11, 'Encantado'), (14, 'Exausto'), (16, 'Desolado'), (19, 'Tenso'), (20, 'Caveira'), (21, 'Alienígena'), (22, 'Com frio'), (23, 'Gato'), (24, 'Robô')], null=True, verbose_name='humor'),
        ),
    ]
