# Generated by Django 3.0.7 on 2021-01-08 21:25

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0003_knowledgearea_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActingField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('text', models.CharField(max_length=1024, verbose_name='Campo de Atuação')),
            ],
            options={
                'verbose_name': 'Campo de Atuação',
                'verbose_name_plural': 'Campos de Atuação',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('text', models.CharField(max_length=1024, verbose_name='Eixo')),
            ],
            options={
                'verbose_name': 'Eixo',
                'verbose_name_plural': 'Eixos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='KnowledgeObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('text', models.CharField(max_length=1024, verbose_name='Objecto de Conhecimento')),
            ],
            options={
                'verbose_name': 'Objeto de Conhecimento',
                'verbose_name_plural': 'Objetos de Conhecimento',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LanguagePractice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('text', models.CharField(max_length=1024, verbose_name='Prática de Linguagem')),
            ],
            options={
                'verbose_name': 'Prática de Linguagem',
                'verbose_name_plural': 'Práticas de Linguagem',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ThematicUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('text', models.CharField(max_length=1024, verbose_name='Unidade Temática')),
            ],
            options={
                'verbose_name': 'Unidade Temática',
                'verbose_name_plural': 'Unidades Temáticas',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(max_length=150, verbose_name='Código da competência')),
                ('text', models.CharField(max_length=1024, verbose_name='Competência')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject', verbose_name='Componente')),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Abiliity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(max_length=150, verbose_name='Código da habilidade')),
                ('text', models.CharField(max_length=1024, verbose_name='Habilidade')),
                ('acting_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bncc.ActingField', verbose_name='Campo de atuação')),
                ('axis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bncc.Axis', verbose_name='Eixo')),
                ('knowledge_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bncc.KnowledgeObject', verbose_name='Objeto de conhecimento')),
                ('language_practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bncc.LanguagePractice', verbose_name='Prática de linguagem')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject', verbose_name='Componente')),
                ('thematic_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bncc.ThematicUnit', verbose_name='Unidade temática')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
