# Generated by Django 3.0.7 on 2021-01-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bncc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Código da competência'),
        ),
    ]
