# Generated by Django 3.0.7 on 2021-01-12 17:57

from django.db import migrations, models
import time
        
class Migration(migrations.Migration):

    dependencies = [
        ('bncc', '0002_auto_20210112_1457'),
    ]

    operations = [
    ]
