# Generated by Django 3.0.7 on 2021-01-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20210108_1825'),
        ('bncc', '0003_data_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='abiliity',
            name='grades',
            field=models.ManyToManyField(related_name='abilities', to='classes.Grade', verbose_name='Anos/Séries'),
        ),
    ]
