# Generated by Django 3.0.7 on 2021-01-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bncc', '0004_abiliity_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiliity',
            name='text',
            field=models.CharField(max_length=4096, verbose_name='Habilidade'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='text',
            field=models.CharField(max_length=4096, verbose_name='Competência'),
        ),
    ]
