# Generated by Django 3.0.7 on 2021-04-23 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_remove_client_correction_by_subject'),
        ('bncc', '0005_auto_20210114_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='abiliity',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.Client'),
        ),
        migrations.AddField(
            model_name='competence',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.Client'),
        ),
    ]
