# Generated by Django 3.0.7 on 2021-04-24 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subject_parent_subject'),
        ('bncc', '0007_auto_20210423_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abiliity',
            options={'ordering': ('-created_at',), 'verbose_name': 'Habilidade', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ('-created_at',), 'verbose_name': 'Competência', 'verbose_name_plural': 'Competências'},
        ),
        migrations.AlterField(
            model_name='abiliity',
            name='text',
            field=models.TextField(max_length=4096, verbose_name='Habilidade'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='subject',
            field=models.ForeignKey(help_text='Será mostrado para esta disciplina e as disciplinas filhas', on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject', verbose_name='Componente'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='text',
            field=models.TextField(help_text='Descreva a competência acima', max_length=4096, verbose_name='Competência'),
        ),
    ]
