# Generated by Django 4.0.2 on 2022-03-09 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_alter_subject_parent_subject_alter_topic_name'),
        ('bncc', '0008_auto_20210423_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiliity',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Componente'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Será mostrado para esta disciplina e as disciplinas filhas', null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Componente'),
        ),
    ]
