# Generated by Django 4.0.2 on 2022-03-09 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_alter_subject_parent_subject_alter_topic_name'),
        ('bncc', '0009_alter_abiliity_subject_alter_competence_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='abiliity',
            name='knowledge_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.knowledgearea', verbose_name='Área de conhecimento'),
        ),
        migrations.AddField(
            model_name='competence',
            name='knowledge_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.knowledgearea', verbose_name='Área de conhecimento'),
        ),
    ]
