# Generated by Django 4.0.2 on 2022-06-14 18:13

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0084_exam_show_ranking_historicalexam_show_ranking'),
        ('bncc', '0014_alter_abiliity_id_alter_actingfield_id_alter_axis_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceExamPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('performance', models.FloatField(default=0)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bncc.competence', verbose_name='Competência')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='Caderno')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AbilityExamPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('performance', models.FloatField(default=0)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bncc.abiliity', verbose_name='Habilidade')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='Caderno')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
