# Generated by Django 4.0.2 on 2022-06-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bncc', '0015_competenceexamperformance_abilityexamperformance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competenceexamperformance',
            name='competence',
        ),
        migrations.RemoveField(
            model_name='competenceexamperformance',
            name='exam',
        ),
        migrations.DeleteModel(
            name='AbilityExamPerformance',
        ),
        migrations.DeleteModel(
            name='CompetenceExamPerformance',
        ),
    ]
