# Generated by Django 3.0.7 on 2020-12-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='knowlegd_area',
            new_name='knowledge_area',
        ),
    ]
