# Generated by Django 3.0.7 on 2021-01-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20210108_1825'),
        ('subjects', '0002_auto_20201205_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearea',
            name='grades',
            field=models.ManyToManyField(to='classes.Grade', verbose_name='Séries'),
        ),
    ]
