# Generated by Django 3.0.7 on 2021-03-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_knowledgearea_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='parent_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='subjects.Subject'),
        ),
    ]
