# Generated by Django 3.0.7 on 2021-04-30 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20210423_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome da disciplina'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='parent_subject',
            field=models.ForeignKey(help_text='A disciplina de referência será a fonte para geração das competências e habilidades da BNCC.', null=True, on_delete=django.db.models.deletion.PROTECT, to='subjects.Subject', verbose_name='Disciplina de referência'),
        ),
    ]
