# Generated by Django 3.0.7 on 2021-05-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_auto_20210430_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='stage',
            field=models.SmallIntegerField(choices=[(0, '1ª Etapa'), (1, '2ª Etapa'), (2, '3ª Etapa'), (3, '4ª Etapa'), (4, '5ª Etapa'), (5, '6ª Etapa'), (6, 'Geral')], default=6, verbose_name='Etapa'),
        ),
    ]
