# Generated by Django 3.0.7 on 2021-05-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_topic_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='stage',
            field=models.SmallIntegerField(choices=[(1, '1ª Etapa'), (2, '2ª Etapa'), (3, '3ª Etapa'), (4, '4ª Etapa'), (5, '5ª Etapa'), (6, '6ª Etapa'), (7, 'Geral')], default=7, verbose_name='Etapa de Ensino'),
        ),
    ]
