# Generated by Django 3.0.7 on 2021-05-09 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20210126_1340'),
        ('subjects', '0008_auto_20210507_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Grade', verbose_name='Série'),
        ),
    ]
