# Generated by Django 3.2.3 on 2021-06-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_topic_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
    ]
