# Generated by Django 4.0.2 on 2022-03-01 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_alter_subject_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='parent_subject',
            field=models.ForeignKey(blank=True, help_text='A disciplina de referência será a fonte para geração das competências e habilidades da BNCC.', null=True, on_delete=django.db.models.deletion.PROTECT, to='subjects.subject', verbose_name='Disciplina de referência'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=4096, verbose_name='Título'),
        ),
    ]
