# Generated by Django 4.0.2 on 2022-04-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_alter_subject_parent_subject_alter_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgearea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em'),
        ),
        migrations.AlterField(
            model_name='knowledgearea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em'),
        ),
    ]
