# Generated by Django 4.0.2 on 2022-06-14 18:13

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0084_exam_show_ranking_historicalexam_show_ranking'),
        ('subjects', '0015_alter_knowledgearea_id_alter_subject_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicExamPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('performance', models.FloatField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='Caderno')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.topic', verbose_name='Tópico')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
