# Generated by Django 4.0.2 on 2022-06-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0016_topicexamperformance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicExamPerformance',
        ),
    ]
