# Generated by Django 4.0.6 on 2023-02-07 20:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0070_merge_20230118_1114'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0018_alter_topic_options_thema_maintopic_topic_main_topic_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thema',
            new_name='Theme',
        ),
        migrations.RenameField(
            model_name='maintopic',
            old_name='thema',
            new_name='theme',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='thema',
            new_name='theme',
        ),
    ]
