# Generated by Django 4.0.6 on 2023-06-15 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0095_merge_20230523_1905'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0019_rename_thema_theme_rename_thema_maintopic_theme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=80, verbose_name='Nome da relação')),
                ('relation_type', models.SmallIntegerField(choices=[(0, 'Somar pesos das disciplinas'), (1, 'Média dos pesos')], default=0, verbose_name='Tipo de relação')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('subjects', models.ManyToManyField(to='subjects.subject', verbose_name='Relações')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Relação entre disciplinas',
                'verbose_name_plural': 'Relações entre disciplinas',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
