# Generated by Django 4.0.6 on 2023-06-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0020_subjectrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrelation',
            name='subjects',
            field=models.ManyToManyField(to='subjects.subject', verbose_name='Disciplinas relacionadas'),
        ),
    ]
