# Generated by Django 4.0.6 on 2024-04-05 02:28

from django.db import migrations

def create_knowledge_areas(apps, schema_editor):
    pass
    # Grade = apps.get_model('classes', 'Grade')
    # KnowledgeArea = apps.get_model('subjects', 'KnowledgeArea')
    
    # HIGHT_SCHOOL, ELEMENTARY_SCHOOL, ELEMENTARY_SCHOOL_2 = range(3)
    # knowledge_areas = [
    #     {'name': 'Ciências da Natureza e suas Tecnologias', 'grades': '1,2,3', 'level': HIGHT_SCHOOL},
    #     {'name': 'Ciências Humanas e Sociais Aplicadas', 'grades': '1,2,3', 'level': HIGHT_SCHOOL},
    #     {'name': 'Linguagens e suas Tecnologias', 'grades': '1,2,3', 'level': HIGHT_SCHOOL},
    #     {'name': 'Matemática e suas Tecnologias', 'grades': '1,2,3', 'level': HIGHT_SCHOOL},

    #     {'name': 'Linguagens', 'grades': '1,2,3,4,5', 'level': ELEMENTARY_SCHOOL},
    #     {'name': 'Matemática', 'grades': '1,2,3,4,5', 'level': ELEMENTARY_SCHOOL},
    #     {'name': 'Ciências da Natureza', 'grades': '1,2,3,4,5', 'level': ELEMENTARY_SCHOOL},
    #     {'name': 'Ciências Humanas', 'grades': '1,2,3,4,5', 'level': ELEMENTARY_SCHOOL},
    #     {'name': 'Ensino Religioso', 'grades': '1,2,3,4,5', 'level': ELEMENTARY_SCHOOL},

    #     {'name': 'Linguagens', 'grades': '6,7,8,9', 'level': ELEMENTARY_SCHOOL_2},
    #     {'name': 'Matemática', 'grades': '6,7,8,9', 'level': ELEMENTARY_SCHOOL_2},
    #     {'name': 'Ciências da Natureza', 'grades': '6,7,8,9', 'level': ELEMENTARY_SCHOOL_2},
    #     {'name': 'Ciências Humanas', 'grades': '6,7,8,9', 'level': ELEMENTARY_SCHOOL_2},
    #     {'name': 'Ensino Religioso', 'grades': '6,7,8,9', 'level': ELEMENTARY_SCHOOL_2},
    # ]

    # all_grades = list(Grade.objects.all().values('id', 'name', 'level'))

    # for knowledge_area in knowledge_areas:
    #     db_knowledge_area, created = KnowledgeArea.objects.get_or_create(
    #         name=knowledge_area['name']
    #     )
    #     for grade_name in knowledge_area['grades'].split(','):
    #         try:
    #             grade = list(filter(lambda x: x['name'] == grade_name and x['level'] == knowledge_area['level'], all_grades))[0]
    #             db_knowledge_area.grades.add(grade['id'])
    #         except Exception as e:
    #             print(e)
class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0021_alter_subjectrelation_subjects'),
    ]

    operations = [
        migrations.RunPython(create_knowledge_areas, migrations.RunPython.noop),
    ]
