# Generated by Django 4.0.6 on 2024-05-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0021_alter_subjectrelation_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_foreign_language_subject',
            field=models.BooleanField(blank=True, default=False, verbose_name='É disciplina de lingua estrangeira'),
        ),
    ]
