# Generated by Django 4.0.6 on 2024-05-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0022_subject_is_foreign_language_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='is_foreign_language_subject',
            field=models.BooleanField(blank=True, default=False, verbose_name='Disciplina de língua estrangeira'),
        ),
    ]
