# Generated by Django 4.0.6 on 2024-07-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0022_create_knowledge_area_data'),
        ('subjects', '0023_alter_subject_is_foreign_language_subject'),
    ]

    operations = [
    ]
