# Generated by Django 3.0.7 on 2021-01-18 18:39

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_auto_20201212_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('financial_responsible_name', models.CharField(max_length=255, verbose_name='Nome do responsável financeiro')),
                ('financial_responsible_phone', models.CharField(max_length=255, verbose_name='Telefone do responsável financeiro')),
                ('previous_school', models.CharField(max_length=255, verbose_name='Instituição anterior')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Alguma observação?')),
                ('next_grade', models.PositiveIntegerField(choices=[(0, '1º Ano (Ensino médio)'), (1, '2º Ano (Ensino médio)'), (2, '3º Ano (Ensino médio)')], verbose_name='Qual série irá cursar em 2021?')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['-created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
