# Generated by Django 3.0.7 on 2021-01-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20210125_1512'),
        ('candidates', '0002_auto_20210125_1558'),
    ]

    operations = [
    ]
