# Generated by Django 3.0.7 on 2021-01-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_merge_20210126_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='next_grade',
            field=models.PositiveIntegerField(choices=[(0, '1º Ano (Ensino médio)'), (1, '2º Ano (Ensino médio)'), (2, '3º Ano (Ensino médio)')], verbose_name='Qual série irá cursar em 2021?'),
        ),
    ]
