# Generated by Django 3.0.7 on 2021-01-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_auto_20210126_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='next_grade',
        ),
    ]
