# Generated by Django 3.0.7 on 2021-01-26 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20210126_1301'),
        ('candidates', '0005_remove_candidate_next_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='next_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.Grade', verbose_name='Qual série irá cursar em 2021?'),
        ),
    ]
