# Generated by Django 3.0.7 on 2021-03-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_candidate_next_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='financial_responsible_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do responsável financeiro'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='financial_responsible_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone do responsável financeiro'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='previous_school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instituição anterior'),
        ),
    ]
