# Generated by Django 3.2.4 on 2021-12-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_auto_20210326_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
