# Generated by Django 3.2.4 on 2022-01-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_candidate_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Digite seu CPF'),
        ),
    ]
