# Generated by Django 4.0.6 on 2023-01-02 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0019_alter_schoolclass_school_year'),
        ('candidates', '0013_alter_candidate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='next_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.grade', verbose_name='Qual série irá cursar em 2022?'),
        ),
    ]
