# Generated by Django 3.0.7 on 2020-10-29 19:27

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('enunciation', tinymce.models.HTMLField(verbose_name='Enunciado')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Discursiva'), (1, 'Objetiva'), (2, 'Arquivo anexado')], default=1, verbose_name='Tipo da questão')),
                ('coordination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.SchoolCoordination', verbose_name='Coordenação')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Topic', verbose_name='Tópico/Assunto')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('text', tinymce.models.HTMLField(verbose_name='Texto da alternativa')),
                ('is_correct', models.BooleanField(default=False, verbose_name='É a correta')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
