# Generated by Django 3.0.7 on 2020-11-03 18:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='commented_awnser',
            field=tinymce.models.HTMLField(default='', verbose_name='Resposta comentada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='feedback',
            field=tinymce.models.HTMLField(default='', verbose_name='Resposta comentada'),
            preserve_default=False,
        ),
    ]
