# Generated by Django 3.0.7 on 2020-11-16 16:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20201103_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ('created_at',), 'verbose_name': 'Alternativa', 'verbose_name_plural': 'Alternativas'},
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Fácil'), (1, 'Médio'), (2, 'Difícil')], default=1, verbose_name='Nível da questão'),
        ),
        migrations.AlterField(
            model_name='question',
            name='enunciation',
            field=tinymce.models.HTMLField(verbose_name='Enunciado da questão'),
        ),
        migrations.AlterField(
            model_name='question',
            name='feedback',
            field=tinymce.models.HTMLField(verbose_name='Feedback do professor'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='É a alternativa correta'),
        ),
    ]
