# Generated by Django 3.0.7 on 2020-12-05 19:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20201203_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='commented_awnser',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Resposta comentada'),
        ),
        migrations.AlterField(
            model_name='question',
            name='feedback',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Feedback do professor'),
        ),
    ]
