# Generated by Django 3.0.7 on 2021-01-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bncc', '0001_initial'),
        ('questions', '0005_auto_20201205_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='abilities',
            field=models.ManyToManyField(blank=True, to='bncc.Abiliity', verbose_name='Abilidades'),
        ),
        migrations.AddField(
            model_name='question',
            name='competence',
            field=models.ManyToManyField(blank=True, to='bncc.Competence', verbose_name='Competências'),
        ),
    ]
