# Generated by Django 3.0.7 on 2021-01-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20210110_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Fácil'), (1, 'Médio'), (2, 'Difícil')], default=1, verbose_name='Nível de dificuldade'),
        ),
    ]
