# Generated by Django 3.0.7 on 2021-01-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20210108_1825'),
        ('questions', '0008_auto_20210111_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Grade', verbose_name='Ano/Série'),
        ),
    ]
