# Generated by Django 3.0.7 on 2021-01-11 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_question_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='competence',
            new_name='competences',
        ),
    ]
