# Generated by Django 3.0.7 on 2021-02-01 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_logo'),
        ('questions', '0010_auto_20210111_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='board',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banca'),
        ),
        migrations.AddField(
            model_name='question',
            name='elaboration_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de elaboração'),
        ),
        migrations.AddField(
            model_name='question',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='É pública'),
        ),
        migrations.AlterField(
            model_name='question',
            name='coordination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.SchoolCoordination', verbose_name='Coordenação'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Fácil'), (1, 'Médio'), (2, 'Difícil'), (3, 'Indefinido')], default=3, verbose_name='Nível de dificuldade'),
        ),
    ]
