# Generated by Django 3.0.7 on 2021-02-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20210212_1511'),
        ('questions', '0011_auto_20210201_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='coordinations',
            field=models.ManyToManyField(related_name='questions', to='clients.SchoolCoordination', verbose_name='Coordenações autorizadas'),
        ),
    ]
