# Generated by Django 3.0.7 on 2021-01-12 17:57

from django.db import migrations, models

from fiscallizeon.questions.models import Question

def migrate_coordinations(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_question_coordinations'),
    ]

    operations = [
        migrations.RunPython(migrate_coordinations, reverse_code=migrations.RunPython.noop),
    ]
