# Generated by Django 3.0.7 on 2021-02-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_migrate_coordinatios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='coordination',
        ),
    ]
