# Generated by Django 3.0.7 on 2021-02-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20210212_1511'),
        ('questions', '0015_remove_question_coordination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='coordinations',
            field=models.ManyToManyField(help_text='Selecione as coordenações que terão acesso a essa questão', related_name='questions', to='clients.SchoolCoordination', verbose_name='Coordenações autorizadas'),
        ),
    ]
