# Generated by Django 3.0.7 on 2021-03-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_knowledgearea_grades'),
        ('questions', '0016_auto_20210216_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(related_name='questions', to='subjects.Topic', verbose_name='Assuntos abordados'),
        ),
    ]
