# Generated by Django 3.0.7 on 2021-03-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subject_parent_subject'),
        ('questions', '0017_question_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='questions', to='subjects.Topic', verbose_name='Assuntos abordados'),
        ),
    ]
