# Generated by Django 3.2.3 on 2021-06-04 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_question_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_copies', to='questions.question', verbose_name='Questão original'),
        ),
    ]
