# Generated by Django 3.2.3 on 2021-06-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_question_source_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='break_enunciation',
            field=models.BooleanField(default=False, help_text='Marque se deseja permitir que o enunciado seja quebrado na página ou coluna quando possível.', verbose_name='Permitir quebra do enunciado'),
        ),
        migrations.AddField(
            model_name='question',
            name='print_only_enunciation',
            field=models.BooleanField(default=False, help_text='Marque esta opção se desejar que seja impresso apenas o enunciado da questão, independente do tipo da questão.', verbose_name='Imprimir apenas enunciado'),
        ),
        migrations.AddField(
            model_name='question',
            name='quantity_lines',
            field=models.PositiveSmallIntegerField(default=20, help_text='Defina a quantidade  de linhas que será impressa caso seja uma questão discursiva', verbose_name='Quantidade de linhas'),
        ),
    ]
