# Generated by Django 3.2.4 on 2021-11-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_historicalquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Índice'),
        ),
    ]
