# Generated by Django 3.2.4 on 2021-11-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_questionoption_index'),
    ]

    operations = [
        
    ]
