# Generated by Django 3.2.4 on 2021-12-17 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0023_questionoption_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', tinymce.models.HTMLField(verbose_name='Título')),
                ('text', tinymce.models.HTMLField(verbose_name='Texto Base')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Texto Base',
                'verbose_name_plural': 'Textos Base',
                'ordering': ('created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='question',
            name='base_texts',
            field=models.ManyToManyField(blank=True, to='questions.BaseText', verbose_name='Textos base da questão'),
        ),
    ]
