# Generated by Django 3.2.4 on 2021-12-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_auto_20211217_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='A questão é abstrata, usada apenas na geração de gabarito avulso'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='A questão é abstrata, usada apenas na geração de gabarito avulso'),
        ),
        migrations.AlterField(
            model_name='basetext',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
