# Generated by Django 3.2.4 on 2021-12-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_auto_20211127_1241'),
        ('questions', '0025_auto_20211218_1044'),
    ]

    operations = [
    ]
