# Generated by Django 3.2.4 on 2021-12-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_merge_0024_auto_20211127_1241_0025_auto_20211218_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquestion',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='A questão é abstrata, usada apenas na geração de gabarito avulso'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='A questão é abstrata, usada apenas na geração de gabarito avulso'),
        ),
    ]
