# Generated by Django 4.0.2 on 2022-02-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_auto_20211229_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='force_one_column',
            field=models.BooleanField(default=False, help_text='Marque esta opção se desejar que a questão seja impressa em uma coluna, independente do tipo do tipo de prova.', verbose_name='Forçar uma coluna'),
        ),
        migrations.AddField(
            model_name='question',
            name='force_one_column',
            field=models.BooleanField(default=False, help_text='Marque esta opção se desejar que a questão seja impressa em uma coluna, independente do tipo do tipo de prova.', verbose_name='Forçar uma coluna'),
        ),
    ]
