# Generated by Django 4.0.2 on 2022-03-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_historicalquestion_force_one_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='force_break_page',
            field=models.BooleanField(default=False, help_text='Marque esta opção se desejar que a questão esteja obrigatoriamente na próxima página.', verbose_name='Forçar quebra de página'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='number_is_hidden',
            field=models.BooleanField(default=False, help_text='Marque esta opção se desejar que a questão não seja impressa com a numeração.', verbose_name='Não mostrar numeração'),
        ),
        migrations.AddField(
            model_name='question',
            name='force_break_page',
            field=models.BooleanField(default=False, help_text='Marque esta opção se desejar que a questão esteja obrigatoriamente na próxima página.', verbose_name='Forçar quebra de página'),
        ),
        migrations.AddField(
            model_name='question',
            name='number_is_hidden',
            field=models.BooleanField(default=False, help_text='Marque esta opção se desejar que a questão não seja impressa com a numeração.', verbose_name='Não mostrar numeração'),
        ),
    ]
