# Generated by Django 4.0.2 on 2022-03-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_historicalquestion_force_one_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='adapted',
            field=models.BooleanField(default=False, verbose_name='Adaptada'),
        ),
        migrations.AddField(
            model_name='question',
            name='adapted',
            field=models.BooleanField(default=False, verbose_name='Adaptada'),
        ),
    ]
