# Generated by Django 4.0.2 on 2022-03-30 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_historicalquestion_adapted_question_adapted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquestion',
            name='adapted',
        ),
        migrations.RemoveField(
            model_name='question',
            name='adapted',
        ),
    ]
