# Generated by Django 4.0.2 on 2022-04-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_historicalquestion_adapted_question_adapted'),
        ('questions', '0030_remove_historicalquestion_adapted_and_more'),
    ]

    operations = [
    ]
