# Generated by Django 4.0.2 on 2022-04-22 23:40
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0031_merge_20220402_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquestion',
            name='adapted',
        ),
        migrations.RemoveField(
            model_name='question',
            name='adapted',
        ),
        migrations.AlterField(
            model_name='basetext',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em'),
        ),
        migrations.AlterField(
            model_name='basetext',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em'),
        ),
    ]
