# Generated by Django 4.0.2 on 2022-04-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0032_remove_historicalquestion_adapted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='adapted',
            field=models.BooleanField(default=False, help_text='Questão adaptada?', verbose_name='Adaptada'),
        ),
        migrations.AddField(
            model_name='question',
            name='adapted',
            field=models.BooleanField(default=False, help_text='Questão adaptada?', verbose_name='Adaptada'),
        ),
    ]
