# Generated by Django 4.0.4 on 2022-04-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0033_historicalquestion_adapted_question_adapted'),
        ('questions', '0034_alter_basetext_id_alter_question_id_and_more'),
    ]

    operations = [
    ]
