# Generated by Django 4.0.4 on 2022-04-24 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0035_merge_20220424_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquestion',
            name='adapted',
        ),
        migrations.RemoveField(
            model_name='question',
            name='adapted',
        ),
        migrations.AlterField(
            model_name='basetext',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
