# Generated by Django 4.0.2 on 2022-07-22 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0001_initial'),
        ('questions', '0038_alter_question_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='text_correction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corrections.textcorrection', verbose_name='Correção de redação'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_correction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corrections.textcorrection', verbose_name='Correção de redação'),
        ),
    ]
