# Generated by Django 4.0.6 on 2022-09-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0040_alter_historicalquestion_text_correction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='answer_video',
            field=models.URLField(blank=True, null=True, verbose_name='Link da resposta em vídeo'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='answer_video_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Panda Vídeo'), (1, 'Youtube')], default=1, null=True, verbose_name='Fonte do vídeo'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_video',
            field=models.URLField(blank=True, null=True, verbose_name='Link da resposta em vídeo'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_video_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Panda Vídeo'), (1, 'Youtube')], default=1, null=True, verbose_name='Fonte do vídeo'),
        ),
    ]
