# Generated by Django 4.0.6 on 2022-11-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0041_historicalquestion_answer_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='superpro_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID da questão no Super Professor'),
        ),
        migrations.AddField(
            model_name='question',
            name='superpro_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID da questão no Super Professor'),
        ),
    ]
