# Generated by Django 4.0.6 on 2023-01-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0042_historicalquestion_superpro_id_question_superpro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='text_question_format',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Espaço em branco'), (1, 'Imprimir linhas')], default=0, verbose_name='Tipo de impressão de linhas'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_question_format',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Espaço em branco'), (1, 'Imprimir linhas')], default=0, verbose_name='Tipo de impressão de linhas'),
        ),
    ]
