# Generated by Django 4.0.6 on 2023-01-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0042_historicalquestion_superpro_id_question_superpro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instituição'),
        ),
    ]
