# Generated by Django 4.0.6 on 2023-01-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0043_alter_question_institution'),
        ('questions', '0043_historicalquestion_text_question_format_and_more'),
    ]

    operations = [
    ]
