# Generated by Django 4.0.6 on 2023-02-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0044_merge_20230118_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quantity_lines',
            field=models.PositiveSmallIntegerField(default=5, help_text='Defina a quantidade  de linhas que será impressa caso seja uma questão discursiva', verbose_name='Quantidade de linhas'),
        ),
    ]
