# Generated by Django 4.0.6 on 2023-04-20 00:35

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0092_remove_questiontag_is_question_correction_tag_and_more'),
        ('questions', '0045_alter_question_quantity_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionHistoryTags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('record_id', models.CharField(max_length=100, verbose_name='registro do histórico')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('tags', models.ManyToManyField(blank=True, to='clients.questiontag', verbose_name='Tags da edição')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
