# Generated by Django 4.0.6 on 2023-04-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0046_questionhistorytags'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionhistorytags',
            name='note',
            field=models.CharField(default='', max_length=100, verbose_name='nota de edição'),
        ),
    ]
