# Generated by Django 4.0.6 on 2023-12-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0048_alter_historicalquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalquestion',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Questão'},
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
