# Generated by Django 4.0.6 on 2023-12-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0048_alter_historicalquestion_options_and_more'),
        ('questions', '0048_sugestiontags'),
    ]

    operations = [
    ]
