# Generated by Django 4.0.6 on 2024-01-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0049_alter_historicalquestion_options_and_more'),
        ('questions', '0050_alter_historicalquestion_options_and_more'),
    ]

    operations = [
    ]
