# Generated by Django 4.0.6 on 2024-01-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0051_merge_20240116_1103'),
        ('questions', '0051_merge_20240117_1335'),
    ]

    operations = [
    ]
