# Generated by Django 4.0.6 on 2024-01-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0053_alter_sugestiontags_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='created_with_ai',
            field=models.BooleanField(blank=True, default=False, verbose_name='Criada com inteligencia artificial'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_with_ai',
            field=models.BooleanField(blank=True, default=False, verbose_name='Criada com inteligencia artificial'),
        ),
    ]
