# Generated by Django 4.0.6 on 2024-01-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0054_historicalquestion_created_with_ai_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalquestion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Questão', 'verbose_name_plural': 'historical Questões'},
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Discursiva'), (1, 'Objetiva'), (2, 'Arquivo anexado'), (3, 'Questão de somatório')], default=1, verbose_name='Tipo da questão'),
        ),
    ]
