# Generated by Django 4.0.6 on 2024-01-31 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0050_alter_question_options'),
        ('questions', '0054_historicalquestion_created_with_ai_and_more'),
    ]

    operations = [
    ]
