# Generated by Django 4.0.6 on 2024-01-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0055_merge_20240131_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Discursiva'), (1, 'Objetiva'), (2, 'Arquivo anexado'), (3, 'Somatório')], default=1, verbose_name='Tipo da questão'),
        ),
    ]
