# Generated by Django 4.0.6 on 2024-02-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0055_merge_20240131_1735'),
        ('questions', '0056_alter_question_category'),
    ]

    operations = [
    ]
