# Generated by Django 4.0.6 on 2024-02-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0055_alter_historicalquestion_options_and_more'),
        ('questions', '0056_alter_question_category'),
    ]

    operations = [
    ]
