# Generated by Django 4.0.6 on 2024-02-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0057_merge_20240222_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalquestion',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Questão'},
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Discursiva'), (1, 'Objetiva'), (2, 'Arquivo anexado'), (3, 'Somatório')], default=1, verbose_name='Tipo da questão'),
        ),
    ]
