# Generated by Django 4.0.6 on 2024-02-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0057_merge_20240222_1427'),
        ('questions', '0058_alter_historicalquestion_options_and_more'),
    ]

    operations = [
    ]
