# Generated by Django 4.0.6 on 2024-04-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0059_merge_20240222_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalquestion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Questão', 'verbose_name_plural': 'historical Questões'},
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
