# Generated by Django 4.0.6 on 2024-04-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0062_alter_historicalquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='print_only_enunciation',
            field=models.BooleanField(default=False, help_text='Marque esta opção se deseja remover o espaço para resposta do aluno (aplicável apenas para questões discursivas).', verbose_name='Imprimir apenas enunciado'),
        ),
    ]
