# Generated by Django 4.0.6 on 2024-04-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bncc', '0016_remove_competenceexamperformance_competence_and_more'),
        ('questions', '0063_alter_question_print_only_enunciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='abilities',
            field=models.ManyToManyField(blank=True, to='bncc.abiliity', verbose_name='Habilidades'),
        ),
    ]
