# Generated by Django 4.0.6 on 2024-04-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0064_alter_question_abilities'),
    ]

    operations = [
    ]
