# Generated by Django 4.0.6 on 2024-04-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0063_alter_question_options'),
        ('questions', '0065_merge_20240426_1147'),
    ]

    operations = [
    ]
