# Generated by Django 4.0.6 on 2024-05-03 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0021_alter_subjectrelation_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0027_merge_20240325_1412'),
        ('questions', '0065_merge_20240426_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='board',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banca'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='break_enunciation',
            field=models.BooleanField(default=False, help_text='Marque se deseja permitir que o enunciado seja quebrado na página ou coluna quando possível.', verbose_name='Permitir quebra do enunciado'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Discursiva'), (1, 'Objetiva'), (2, 'Arquivo anexado'), (3, 'Somatório')], default=1, verbose_name='Tipo da questão'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='commented_awnser',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Resposta comentada'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='elaboration_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de elaboração'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='enunciation',
            field=tinymce.models.HTMLField(default='', verbose_name='Enunciado da questão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='feedback',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Feedback do professor'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='grade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='classes.grade', verbose_name='Ano/Série'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='É pública'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Fácil'), (1, 'Médio'), (2, 'Difícil'), (3, 'Indefinido')], default=3, verbose_name='Nível de dificuldade'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='print_only_enunciation',
            field=models.BooleanField(default=False, help_text='Marque esta opção se deseja remover o espaço para resposta do aluno (aplicável apenas para questões discursivas).', verbose_name='Imprimir apenas enunciado'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='quantity_lines',
            field=models.PositiveSmallIntegerField(default=5, help_text='Defina a quantidade  de linhas que será impressa caso seja uma questão discursiva', verbose_name='Quantidade de linhas'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='source_question',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='questions.question', verbose_name='Questão original'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subjects.subject', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='topic',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subjects.topic', verbose_name='Tópico/Assunto'),
        ),
    ]
