# Generated by Django 4.0.6 on 2024-04-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0066_merge_20240429_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('can_duplicate_question', 'Pode duplicar questões'), ('can_add_subject_question', 'Pode cadastrar assuntos na criação de cadernos'), ('can_add_ability_and_competence_question', 'Pode cadastrar habilidade e competência na criação de cadernos')), 'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
    ]
