# Generated by Django 4.0.6 on 2024-05-15 18:40

from django.db import migrations, models
import fiscallizeon.core.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0067_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='support_image_question',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='support_image_question',
            field=models.ImageField(blank=True, null=True, storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to='questions/support-image'),
        ),
    ]
