# Generated by Django 4.0.6 on 2024-05-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0066_historicalquestion_board_and_more'),
        ('questions', '0067_alter_question_options'),
    ]

    operations = [
    ]
