# Generated by Django 4.0.6 on 2024-05-20 21:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0068_historicalquestion_support_image_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquestion',
            name='support_image_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='support_image_question',
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='support_content_question',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Conteudo de apoio à resposta'),
        ),
        migrations.AddField(
            model_name='question',
            name='support_content_question',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Conteudo de apoio à resposta'),
        ),
    ]
