# Generated by Django 4.0.6 on 2024-05-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0069_remove_historicalquestion_support_image_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='support_content_position',
            field=models.CharField(choices=[('center', 'Centralizado'), ('left', 'À Esquerda'), ('right', 'À Direita')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='support_content_position',
            field=models.CharField(choices=[('center', 'Centralizado'), ('left', 'À Esquerda'), ('right', 'À Direita')], default='center', max_length=10),
        ),
    ]
