# Generated by Django 4.0.6 on 2024-05-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0070_historicalquestion_support_content_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquestion',
            name='support_content_position',
            field=models.CharField(blank=True, choices=[('center', 'Centralizado'), ('left', 'À Esquerda'), ('right', 'À Direita')], default='center', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='support_content_position',
            field=models.CharField(blank=True, choices=[('center', 'Centralizado'), ('left', 'À Esquerda'), ('right', 'À Direita')], default='center', max_length=10, null=True),
        ),
    ]
