# Generated by Django 4.0.6 on 2024-05-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0068_merge_20240522_1257'),
        ('questions', '0071_alter_historicalquestion_support_content_position_and_more'),
    ]

    operations = [
    ]
