# Generated by Django 4.0.6 on 2024-05-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0072_merge_20240527_1805'),
    ]

    operations = [
    ]
