# Generated by Django 4.0.6 on 2024-09-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0073_merge_20240531_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='draft_rows_number',
            field=models.PositiveSmallIntegerField(default=0, help_text='Caso deseje adicionar ao caderno uma área para rascunho ou cálculos, informe um valor maior que zero', verbose_name='Quantidade de linhas para rascunho'),
        ),
        migrations.AddField(
            model_name='question',
            name='draft_rows_number',
            field=models.PositiveSmallIntegerField(default=0, help_text='Caso deseje adicionar ao caderno uma área para rascunho ou cálculos, informe um valor maior que zero', verbose_name='Quantidade de linhas para rascunho'),
        ),
    ]
