# Generated by Django 4.0.6 on 2024-09-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0074_historicalquestion_draft_rows_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquestion',
            name='draft_rows_number',
            field=models.PositiveSmallIntegerField(default=0, help_text='Caso deseje adicionar ao caderno uma área para rascunho ou cálculos, informe um valor maior que zero', verbose_name='Quantidade de linhas para rascunho.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='draft_rows_number',
            field=models.PositiveSmallIntegerField(default=0, help_text='Caso deseje adicionar ao caderno uma área para rascunho ou cálculos, informe um valor maior que zero', verbose_name='Quantidade de linhas para rascunho.'),
        ),
    ]
