# Generated by Django 4.0.6 on 2024-09-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0074_historicalquestion_draft_rows_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='is_essay',
            field=models.BooleanField(default=False, help_text='Marcando esta opção o malote de provas será impresso com uma folha de redação.', verbose_name='É uma redação'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_essay',
            field=models.BooleanField(default=False, help_text='Marcando esta opção o malote de provas será impresso com uma folha de redação.', verbose_name='É uma redação'),
        ),
    ]
