# Generated by Django 4.0.6 on 2024-09-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0075_alter_historicalquestion_draft_rows_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquestion',
            name='draft_rows_number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='draft_rows_number',
        ),
    ]
