# Generated by Django 4.0.6 on 2024-10-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0075_historicalquestion_is_essay_question_is_essay'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='theme',
            field=models.CharField(blank=True, help_text='Se a questão for redação você deve digitar o tema', max_length=512, null=True, verbose_name='Tema da redação'),
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.CharField(blank=True, help_text='Se a questão for redação você deve digitar o tema', max_length=512, null=True, verbose_name='Tema da redação'),
        ),
    ]
