# Generated by Django 4.0.6 on 2024-10-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0075_historicalquestion_is_essay_question_is_essay'),
        ('questions', '0077_historicalquestion_draft_rows_number_and_more'),
    ]

    operations = [
    ]
