# Generated by Django 4.0.6 on 2024-10-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0076_historicalquestion_theme_question_theme'),
        ('questions', '0078_merge_20241025_1223'),
    ]

    operations = [
    ]
