# Generated by Django 4.0.6 on 2024-11-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0078_merge_20241025_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='force_choices_with_statement',
            field=models.BooleanField(default=False, help_text='As alternativas de cada questão serão exibidas imediatamente junto ao enunciado. (Quebra de enunciado será desconsiderado.)', verbose_name='Forçar alternativas junto ao enunciado.'),
        ),
        migrations.AddField(
            model_name='question',
            name='force_choices_with_statement',
            field=models.BooleanField(default=False, help_text='As alternativas de cada questão serão exibidas imediatamente junto ao enunciado. (Quebra de enunciado será desconsiderado.)', verbose_name='Forçar alternativas junto ao enunciado.'),
        ),
    ]
