# Generated by Django 4.0.6 on 2024-11-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0079_historicalquestionoption'),
        ('questions', '0079_merge_20241030_1617'),
    ]

    operations = [
    ]
