# Generated by Django 4.0.6 on 2024-11-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0079_historicalquestion_force_choices_with_statement_and_more'),
        ('questions', '0080_merge_20241124_1415'),
    ]

    operations = [
    ]
