# Generated by Django 4.2.19 on 2025-05-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0081_merge_20241126_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='break_alternatives',
            field=models.BooleanField(default=False, help_text='Marque se deseja permitir que as alternativas sejam quebradas na página ou coluna quando possível.', verbose_name='Permitir quebra das alternativas'),
        ),
        migrations.AddField(
            model_name='question',
            name='break_alternatives',
            field=models.BooleanField(default=False, help_text='Marque se deseja permitir que as alternativas sejam quebradas na página ou coluna quando possível.', verbose_name='Permitir quebra das alternativas'),
        ),
    ]
