# Generated by Django 4.2.19 on 2025-07-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0083_historicalquestion_cloze_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquestion',
            name='cloze_content',
            field=models.CharField(blank=True, help_text='Utilize o formato [[opção]] para definir lacunas', max_length=1000, null=True, verbose_name='Conteúdo da questão de preenchimento de lacunas'),
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='incorrect_cloze_alternatives',
            field=models.CharField(blank=True, help_text='Informe as alternativas separadas por vírgula', max_length=1000, null=True, verbose_name='Alternativas incorretas da questão de preenchimento de lacunas'),
        ),
        migrations.AlterField(
            model_name='question',
            name='cloze_content',
            field=models.CharField(blank=True, help_text='Utilize o formato [[opção]] para definir lacunas', max_length=1000, null=True, verbose_name='Conteúdo da questão de preenchimento de lacunas'),
        ),
        migrations.AlterField(
            model_name='question',
            name='incorrect_cloze_alternatives',
            field=models.CharField(blank=True, help_text='Informe as alternativas separadas por vírgula', max_length=1000, null=True, verbose_name='Alternativas incorretas da questão de preenchimento de lacunas'),
        ),
    ]
