# Generated by Django 3.2.4 on 2021-08-20 22:05

from django.db import migrations, models
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('url_path', models.CharField(help_text='Utilize "namespace:name"', max_length=255, verbose_name='URL da página')),
                ('article_url', models.URLField(verbose_name='URL do artigo')),
                ('article_name', models.CharField(max_length=255, verbose_name='Título do artigo')),
                ('article_description', models.CharField(max_length=255, verbose_name='Descrição do link de ajuda')),
                ('is_student', models.BooleanField(default=False, verbose_name='Para alunos')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Para professores')),
                ('is_inspector', models.BooleanField(default=False, verbose_name='Para fiscais')),
                ('is_coordination', models.BooleanField(default=False, verbose_name='Para coordenadores')),
            ],
            options={
                'verbose_name': 'Link de ajuda',
                'verbose_name_plural': 'Links de ajuda',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
