# Generated by Django 4.0.4 on 2022-04-23 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_alter_helplink_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helplink',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
