# Generated by Django 4.0.6 on 2023-10-06 19:19

from django.db import migrations, models
import django_lifecycle.mixins
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0108_confignotification_coordination_send_notification_and_more'),
        ('help', '0005_alter_helplink_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da categoria')),
                ('icon', models.CharField(blank=True, help_text='Geralmente utilizado: https://fontawesome.com/icons, adicionar a tag <i></i> completa como no exemplo: <i class="fas fa-times"></i>', max_length=200, null=True, verbose_name='Icone da categoria')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descriçao')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('url_path', models.CharField(blank=True, help_text='Utilize "namespace:name"', max_length=255, null=True, verbose_name='URL da página')),
                ('segment', models.CharField(blank=True, choices=[('coordination', 'Coordenações'), ('student', 'Alunos'), ('inspector', 'Fiscais'), ('teacher', 'Professores'), ('partner', 'Parceiro')], max_length=30, null=True, verbose_name='Segmento de usuários')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Conteúdo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='tutorial/thumbnail/', verbose_name='Imagem de capa do tutorial')),
                ('youtube_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Url do vídeo')),
                ('views', models.IntegerField(blank=True, default=0, verbose_name='Visualizações')),
                ('status', models.SmallIntegerField(choices=[(0, 'Rescunho'), (1, 'Publicado')], default=0, verbose_name='Status do tutorial')),
                ('categories', models.ManyToManyField(to='help.tutorialcategory', verbose_name='Categoria')),
                ('clients', models.ManyToManyField(blank=True, to='clients.client', verbose_name='Clientes')),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutoriais',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
