# Generated by Django 4.0.6 on 2023-10-23 19:44

from django.db import migrations, models
import fiscallizeon.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0006_tutorialcategory_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='segment',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='segments',
            field=fiscallizeon.core.utils.ChoiceArrayField(base_field=models.CharField(choices=[('coordination', 'Coordenações'), ('student', 'Alunos'), ('inspector', 'Fiscais'), ('teacher', 'Professores'), ('partner', 'Parceiro')], max_length=50, verbose_name='Segmento'), blank=True, null=True, size=None),
        ),
    ]
