# Generated by Django 4.0.6 on 2024-03-18 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('help', '0007_remove_tutorial_segment_tutorial_segments'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('date', models.DateField(auto_now_add=True, verbose_name='data')),
                ('value', models.CharField(choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=1, verbose_name='valor')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='help.tutorial', verbose_name='tutorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'feedback do tutorial',
                'verbose_name_plural': 'feedbacks dos tutoriais',
                'ordering': ('-created_at',),
                'unique_together': {('tutorial', 'user', 'date')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
