# Generated by Django 3.0.7 on 2020-12-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200902_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_number',
            field=models.CharField(max_length=255, verbose_name='Número de matrícula'),
        ),
    ]
