# Generated by Django 3.0.7 on 2021-04-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20201212_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['created_at'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
    ]
