# Generated by Django 3.2.3 on 2021-06-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210430_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
    ]
