# Generated by Django 3.2.4 on 2022-01-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_erp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID ERP'),
        ),
    ]
