# Generated by Django 4.0.2 on 2022-06-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='responsible_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do responsável'),
        ),
    ]
