# Generated by Django 4.0.6 on 2022-11-10 20:24
from django.db import migrations
import os
import csv
import shutil
import requests

def csv_to_dict(csv_file):    
    data = []  
    
    with requests.get(csv_file, stream=True) as r:
        
        tmp_file = os.path.join("/tmp/students.csv")
        
        with open(tmp_file, 'wb') as f:
            shutil.copyfileobj(r.raw, f)
        
        with open(tmp_file, 'r') as file:
            csvreader = csv.DictReader(file)
            for rows in csvreader:
                data.append(rows)
    
    return data

def add_responsible_email_to_students(apps, scheme_editor):
    
    Client = apps.get_model('clients', 'Client')
    Student = apps.get_model('students', 'Student')
    
    client = Client.objects.filter(pk='60c76b23-e58e-44de-997f-821f3b26993d').first() # PK DO CEI EM PRODUÇÃO
    
    if client:
        students = []  
        
        csv_file = 'https://fiscallizeremote.nyc3.digitaloceanspaces.com/temp/Emails-Respons%C3%A1veis-CEI.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=6DZ2VNTMYEQYKLBRO5H7%2F20221110%2Fnyc3%2Fs3%2Faws4_request&X-Amz-Date=20221110T204213Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=a2a19f1af7f2067aa5b6fb83fba4493a3d5789b486c7f272d22adce75e4c6093'
        
        students = csv_to_dict(csv_file) 
        
        for _student in students:
            try:
                student = Student.objects.get(enrollment_number=_student['enrollment_number'], client=client, responsible_email__isnull=True)
                student.responsible_email = _student['responsible_email']
                student.save(skip_hooks=True)
            except:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_responsible_email'),
    ]

    operations = [
        migrations.RunPython(add_responsible_email_to_students, reverse_code=migrations.RunPython.noop)
    ]
