# Generated by Django 4.0.6 on 2023-03-27 19:28

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_student_user'),
    ]

    operations = [
        UnaccentExtension()
    ]
