# Generated by Django 4.0.6 on 2023-05-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20230327_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='responsible_email_two',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Segundo email do responsável'),
        ),
    ]
