# Generated by Django 4.0.6 on 2023-09-14 19:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_student_responsible_email_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSisuCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('courses_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='ID do curso'), size=None)),
                ('states', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='RN', max_length=2, verbose_name='Estado'), size=None)),
                ('year', models.SmallIntegerField(default=2023, verbose_name='Ano do curso')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Curso escolhido no SISU',
                'verbose_name_plural': 'Cursos escolhidos no SISU',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
