# Generated by Django 4.0.6 on 2023-10-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_studentsisucourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Nome da Escola'),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado'),
        ),
    ]
