# Generated by Django 4.0.6 on 2024-01-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_student_school_name_student_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsisucourse',
            name='year',
            field=models.SmallIntegerField(default=2024, verbose_name='Ano do curso'),
        ),
    ]
