# Generated by Django 4.0.6 on 2024-02-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_alter_studentsisucourse_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'permissions': (('can_import_student', 'Pode importar alunos'),), 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
    ]
