# Generated by Django 4.0.6 on 2024-02-06 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'permissions': (('can_import_student', 'Pode importar alunos'), ('can_reset_password', 'Pode resetar senha dos alunos'), ('can_active_student', 'Pode ativar ou desativar alunos')), 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
    ]
