# Generated by Django 4.0.6 on 2024-06-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'permissions': (('can_import_student', 'Pode importar alunos'), ('can_reset_password', 'Pode resetar senha dos alunos'), ('can_active_student', 'Pode ativar ou desativar alunos'), ('can_export_student', 'Pode exportar alunos'), ('can_import_students_application', 'Pode importar alunos em aplicações')), 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
    ]
