# Generated by Django 4.0.6 on 2024-06-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='responsible_email_four',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Quarto email do responsável'),
        ),
        migrations.AddField(
            model_name='student',
            name='responsible_email_three',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Terceiro email do responsável'),
        ),
    ]
