# Generated by Django 4.0.6 on 2024-07-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_student_responsible_email_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_enrollment_erp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de matrícula no ERP'),
        ),
    ]
