# Generated by Django 4.0.6 on 2025-01-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_student_id_enrollment_erp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsisucourse',
            name='year',
            field=models.SmallIntegerField(default=2025, verbose_name='Ano do curso'),
        ),
    ]
