# Generated by Django 4.0.6 on 2025-02-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0022_alter_integrationtoken_options'),
        ('students', '0028_alter_studentsisucourse_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='integration_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='integrations.integrationtoken', verbose_name='Token utilizado para integração'),
        ),
    ]
