# Generated by Django 4.2.19 on 2025-05-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_student_integration_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_atypical',
            field=models.BooleanField(default=False, help_text='Marque se o aluno for atípico, como autista, TDAH, etc.', verbose_name='É aluno atípico?'),
        ),
    ]
