# Generated by Django 3.0.7 on 2020-06-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationstudent_student_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstudent',
            name='student_room_id',
            field=models.BigIntegerField(blank=True, help_text='Código do aluno na sala', null=True, verbose_name='Código do aluno na sala'),
        ),
    ]
