# Generated by Django 3.0.7 on 2020-06-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20200613_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Término da prova'),
        ),
        migrations.AddField(
            model_name='applicationstudent',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início da prova'),
        ),
    ]
