# Generated by Django 3.0.7 on 2020-06-16 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_annotation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ('-created_at',), 'verbose_name': 'Anotação', 'verbose_name_plural': 'Anotações'},
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='date_time',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='application_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='applications.ApplicationStudent', verbose_name='Aluno'),
        ),
    ]
