# Generated by Django 3.0.7 on 2020-06-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_merge_20200616_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='min_time_bathroom',
        ),
        migrations.AddField(
            model_name='application',
            name='min_time_pause',
            field=models.DurationField(default='01:00:00', verbose_name='Tempo mínimo para pausar prova'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='min_time_finish',
            field=models.DurationField(verbose_name='Tempo mínimo para finalizar prova'),
        ),
    ]
