# Generated by Django 3.0.7 on 2020-07-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20200619_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='orchestrator_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Id da aplicação no orquestrador'),
        ),
        migrations.AddField(
            model_name='application',
            name='prefix',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Prefixo do domínio na Digital Ocean'),
        ),
    ]
