# Generated by Django 3.0.7 on 2020-07-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20200707_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='min_time_finish',
            field=models.DurationField(default='01:00:00', help_text='Formato: HH:MM:SS', verbose_name='Tempo mínimo para finalizar prova'),
        ),
        migrations.AlterField(
            model_name='application',
            name='min_time_pause',
            field=models.DurationField(default='01:00:00', help_text='Formato: HH:MM:SS', verbose_name='Tempo mínimo para pausar prova'),
        ),
    ]
