# Generated by Django 3.0.7 on 2020-07-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20200722_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='browser',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Browser'),
        ),
        migrations.AddField(
            model_name='applicationstudent',
            name='browser_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão do Browser'),
        ),
        migrations.AddField(
            model_name='applicationstudent',
            name='device',
            field=models.SmallIntegerField(blank=True, choices=[('Mobile', 0), ('PC', 1)], null=True, verbose_name='Tipo de dispositivo'),
        ),
        migrations.AddField(
            model_name='applicationstudent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Ip do Aluno'),
        ),
        migrations.AddField(
            model_name='applicationstudent',
            name='operation_system',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sistema operacional'),
        ),
        migrations.AddField(
            model_name='applicationstudent',
            name='operation_system_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sistema operacional'),
        ),
    ]
