# Generated by Django 3.0.7 on 2020-07-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20200729_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='device_family',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca do dispositivo'),
        ),
        migrations.AlterField(
            model_name='applicationstudent',
            name='device',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Mobile'), (1, 'PC'), (2, 'Tablet')], null=True, verbose_name='Tipo de dispositivo'),
        ),
        migrations.AlterField(
            model_name='applicationstudent',
            name='operation_system_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão do Sistema operacional'),
        ),
    ]
