# Generated by Django 3.0.7 on 2020-07-30 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0012_auto_20200729_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationannotation',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='applications.Application', verbose_name='Aplicação'),
        ),
        migrations.AlterField(
            model_name='applicationstudent',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Browser'),
        ),
        migrations.AlterField(
            model_name='applicationstudent',
            name='browser_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Versão do Browser'),
        ),
        migrations.AlterField(
            model_name='applicationstudent',
            name='operation_system',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema operacional'),
        ),
        migrations.AlterField(
            model_name='applicationstudent',
            name='operation_system_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Versão do Sistema operacional'),
        ),
        migrations.CreateModel(
            name='ApplicationNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('notice', models.TextField(max_length=255, verbose_name='Aviso')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='applications.Application', verbose_name='Aplicação')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Fiscal')),
            ],
            options={
                'verbose_name': 'Aviso de aplicação',
                'verbose_name_plural': 'Avisos de aplicações',
                'ordering': ('-created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
