# Generated by Django 3.0.7 on 2020-08-01 19:03
from datetime import timedelta

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_auto_20200730_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='max_time_tolerance',
            field=models.DurationField(default=timedelta(seconds=0), help_text='Formato: HH:MM:SS', verbose_name='Tempo de tolerância para iniciar a prova'),
        ),
    ]
