# Generated by Django 3.0.7 on 2020-08-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_application_max_time_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='justification_delay',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa de atraso'),
        ),
    ]
