# Generated by Django 3.0.7 on 2020-08-04 21:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_applicationstudent_justification_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='orientations',
            field=tinymce.models.HTMLField(blank=True, default='<ul><li></li></ul>', null=True, verbose_name='Orientações para aplicação'),
        ),
    ]
