# Generated by Django 3.0.7 on 2020-08-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_auto_20200804_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='can_be_done_cell',
            field=models.BooleanField(default=True, help_text='Marque se o aluno pode fazer no Celular', verbose_name='Pode ser feito no Celular'),
        ),
        migrations.AddField(
            model_name='application',
            name='can_be_done_pc',
            field=models.BooleanField(default=True, help_text='Marque se o aluno pode fazer no computador', verbose_name='Pode ser feito no PC'),
        ),
        migrations.AddField(
            model_name='application',
            name='can_be_done_tablet',
            field=models.BooleanField(default=True, help_text='Marque se o aluno pode fazer no Tablet', verbose_name='Pode ser feito no Tablet'),
        ),
    ]
