# Generated by Django 3.0.7 on 2020-08-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_auto_20200805_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='chat_room_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Id do ChatRoom no Janus'),
        ),
        migrations.AddField(
            model_name='application',
            name='chat_room_pin',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Pin do ChatRoom no Janus'),
        ),
    ]
