# Generated by Django 3.0.7 on 2020-09-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_auto_20200805_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstudent',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='applicationstudent',
            name='room_pin',
        ),
        migrations.RemoveField(
            model_name='applicationstudent',
            name='room_secret',
        ),
        migrations.AddField(
            model_name='application',
            name='video_room_id',
            field=models.CharField(blank=True, help_text='Identificador único da sala de video no Janus', max_length=255, null=True, verbose_name='ID da Sala de video no Janus'),
        ),
        migrations.AddField(
            model_name='application',
            name='video_room_pin',
            field=models.CharField(blank=True, help_text='Código obrigatório para entrar na sala', max_length=255, null=True, verbose_name='PIN da Sala de video no Janus'),
        ),
        migrations.AddField(
            model_name='application',
            name='video_room_secret',
            field=models.CharField(blank=True, help_text='Código necessário para editar e excluir sala', max_length=255, null=True, verbose_name='Secret da sala de video no Janus'),
        ),
        migrations.AddField(
            model_name='applicationstudent',
            name='text_room_id',
            field=models.CharField(blank=True, help_text='Identificador único da sala de texto no Janus', max_length=255, null=True, verbose_name='ID da Sala de texto no Janus'),
        ),
        migrations.AddField(
            model_name='applicationstudent',
            name='text_room_pin',
            field=models.CharField(blank=True, help_text='Código obrigatório para entrar na sala', max_length=255, null=True, verbose_name='PIN da Sala de texto no Janus'),
        ),
    ]
