# Generated by Django 3.0.7 on 2020-09-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_auto_20200925_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='chat_room_id',
            new_name='text_room_id',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='chat_room_pin',
            new_name='text_room_pin',
        ),
    ]
