# Generated by Django 3.0.7 on 2020-11-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_application_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Apenas Monitoramento'), (1, 'Apenas Prova'), (2, 'Monitoramento + Prova')], default=2, verbose_name='Categoria da aplicação'),
        ),
    ]
