# Generated by Django 3.0.7 on 2021-02-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_application_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='block_after_tolerance',
            field=models.BooleanField(default=False, help_text='Marque se o aluno não poderá acessar a prova após o tempo de tolerância', verbose_name='Bloquear prova após tolerância'),
        ),
    ]
