# Generated by Django 3.0.7 on 2021-02-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_application_block_after_tolerance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='block_after_tolerance',
            field=models.BooleanField(default=False, help_text='Marque se o aluno não poderá acessar o ambiente de prova após o tempo de tolerância', verbose_name='Bloquear prova após tolerância'),
        ),
    ]
