# Generated by Django 3.0.7 on 2021-02-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_auto_20210221_1537'),
        ('applications', '0024_auto_20210220_0008'),
    ]

    operations = [
    ]
