# Generated by Django 3.0.7 on 2021-02-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_application_allowance_student_stats_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='allowance_student_stats_date',
            new_name='student_stats_permission_date',
        ),
    ]
