# Generated by Django 3.2.3 on 2021-07-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_applicationstudent_empty_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='suspicion_taking_advantage',
            field=models.BooleanField(default=False, verbose_name='Suspeita obtenção de vantagem'),
        ),
    ]
