# Generated by Django 3.2.3 on 2021-06-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_alter_application_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='is_omr',
            field=models.BooleanField(default=False, verbose_name='Gerado por leitura de gabarito'),
        ),
    ]
