# Generated by Django 3.2.3 on 2021-06-28 18:59

from django.db import migrations, models
import fiscallizeon.applications.models
import fiscallizeon.core.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0031_auto_20210628_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstudent',
            name='answer_sheet',
        ),
        migrations.RemoveField(
            model_name='applicationstudent',
            name='last_answer_sheet_generation',
        ),
        migrations.AddField(
            model_name='application',
            name='answer_sheet',
            field=models.FileField(blank=True, null=True, storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to=fiscallizeon.applications.models.answer_sheet_file_directory_path, verbose_name='Caderno de respostas'),
        ),
        migrations.AddField(
            model_name='application',
            name='last_answer_sheet_generation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da última geração de gabarito'),
        ),
    ]
