# Generated by Django 3.2.3 on 2021-06-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0032_auto_20210628_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sheet_exporting_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Exportando'), (2, 'Finalizado'), (3, 'Erro'), (4, 'Desconhecido')], default=0, verbose_name='Status da exportação da folha de repsostas'),
        ),
    ]
