# Generated by Django 3.2.3 on 2021-06-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0033_application_sheet_exporting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sheet_exporting_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de exportações'),
        ),
    ]
