# Generated by Django 3.2.3 on 2021-07-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_annotation_suspicion_taking_advantage'),
        ('applications', '0034_application_sheet_exporting_count'),
    ]

    operations = [
    ]
