# Generated by Django 3.2.3 on 2021-07-16 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0035_merge_20210710_2112'),
        ('applications', '0035_merge_20210715_1714'),
    ]

    operations = [
    ]
