# Generated by Django 3.2.4 on 2021-08-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0009_inspector_is_discipline_coordinator'),
        ('applications', '0036_merge_20210715_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Monitoramento + Prova'), (3, 'Presencial')], default=2, verbose_name='Categoria da aplicação'),
        ),
        migrations.AlterField(
            model_name='application',
            name='inspectors',
            field=models.ManyToManyField(blank=True, related_name='applications', to='inspectors.Inspector', verbose_name='Fiscais'),
        ),
    ]
