# Generated by Django 3.2.4 on 2021-09-13 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0009_inspector_is_discipline_coordinator'),
        ('exams', '0042_auto_20210820_1228'),
        ('classes', '0006_auto_20210126_1340'),
        ('students', '0005_alter_student_options'),
        ('applications', '0037_auto_20210813_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Online'), (3, 'Presencial')], default=2, verbose_name='Qual tipo de aplicação?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exams.exam', verbose_name='Caderno de provas que será aplicado'),
        ),
        migrations.AlterField(
            model_name='application',
            name='inspectors',
            field=models.ManyToManyField(blank=True, help_text='Deixe em branco caso deseja um fiscal Fiscallize', related_name='applications', to='inspectors.Inspector', verbose_name='Fiscais que irão monitorar esta aplicação'),
        ),
        migrations.AlterField(
            model_name='application',
            name='school_classes',
            field=models.ManyToManyField(blank=True, related_name='applications', to='classes.SchoolClass', verbose_name='Adicionar alunos por turma'),
        ),
        migrations.AlterField(
            model_name='application',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='applications', through='applications.ApplicationStudent', to='students.Student', verbose_name='Adicionar alunos específicos'),
        ),
    ]
