# Generated by Django 3.2.4 on 2021-12-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0039_alter_application_student_stats_permission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Data final da aplicação'),
        ),
        migrations.AddField(
            model_name='application',
            name='end_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora final da aplicação'),
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Online'), (3, 'Presencial'), (4, 'Atividade de casa')], default=2, verbose_name='Qual tipo de aplicação?'),
        ),
    ]
