# Generated by Django 3.2.4 on 2021-11-12 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
        ('applications', '0039_alter_application_student_stats_permission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='room_distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='distribution.roomdistribution', verbose_name='Ensalamento'),
        ),
    ]
