# Generated by Django 3.2.4 on 2021-12-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0040_auto_20211215_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='end_end',
        ),
    ]
