# Generated by Django 3.2.4 on 2021-11-18 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_roomdistributionstudent'),
        ('applications', '0040_application_room_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='room_distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribution.roomdistribution', verbose_name='Ensalamento'),
        ),
    ]
