# Generated by Django 3.2.4 on 2021-12-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0041_remove_application_end_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(verbose_name='Data do início da aplicação'),
        ),
        migrations.AlterField(
            model_name='application',
            name='end',
            field=models.TimeField(verbose_name='Horário final da aplicação'),
        ),
        migrations.AlterField(
            model_name='application',
            name='start',
            field=models.TimeField(verbose_name='Horário inicial da aplicação'),
        ),
    ]
