# Generated by Django 3.2.4 on 2022-01-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0041_alter_application_room_distribution'),
        ('applications', '0042_auto_20211228_1936'),
    ]

    operations = [
    ]
