# Generated by Django 3.2.4 on 2022-01-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0043_merge_20220106_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_presential_sync',
            field=models.BooleanField(default=False),
        ),
    ]
