# Generated by Django 3.2.4 on 2022-02-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0044_application_is_presential_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deadline_wrongs_response',
            field=models.DateField(blank=True, help_text='Limite para o aluno solicitar a revisão da resposta', null=True, verbose_name='Tempo limite para erratas'),
        ),
    ]
