# Generated by Django 3.2.4 on 2022-02-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0045_application_deadline_wrongs_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='deadline_wrongs_response',
            new_name='deadline_to_request_review',
        ),
    ]
