# Generated by Django 3.2.4 on 2022-02-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0046_rename_deadline_wrongs_response_application_deadline_to_request_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='student_stats_permission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data para liberação dos resultados para os alunos'),
        ),
    ]
