# Generated by Django 3.2.4 on 2022-02-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0046_rename_deadline_wrongs_response_application_deadline_to_request_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='foreign_language',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Inglês'), (1, 'Espanhol')], null=True, verbose_name='Língua estrangeira escolhida'),
        ),
    ]
