# Generated by Django 4.0.2 on 2022-02-17 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0047_alter_application_student_stats_permission_date'),
        ('applications', '0047_applicationstudent_foreign_language'),
    ]

    operations = [
    ]
