# Generated by Django 4.0.2 on 2022-02-18 01:13

from django.db import migrations, models
import fiscallizeon.core.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0048_merge_20220217_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='answer_sheet',
            field=models.FileField(blank=True, null=True, storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Caderno de respostas'),
        ),
    ]
