# Generated by Django 4.0.2 on 2022-03-29 20:15

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0049_alter_application_answer_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomizationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('randomization_version', models.PositiveSmallIntegerField(default=1, verbose_name='Versão')),
                ('questions_json', models.JSONField(verbose_name='Questões')),
                ('application_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randomization_versions', to='applications.applicationstudent', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Versão da randomização',
                'verbose_name_plural': 'Versões das randomizações',
                'unique_together': {('application_student', 'randomization_version')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
