# Generated by Django 4.0.2 on 2022-04-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0049_alter_application_answer_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='inspectors_fiscallize',
            field=models.BooleanField(default=False, help_text='Fiscais da Fiscallize', verbose_name='Fiscais da Fiscallize'),
        ),
    ]
