# Generated by Django 4.0.2 on 2022-04-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0049_alter_application_answer_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='duplicate_application',
            field=models.BooleanField(default=False, verbose_name='Aplicação Duplicada'),
        ),
    ]
