# Generated by Django 4.0.2 on 2022-04-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0050_randomizationversion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomizationversion',
            old_name='randomization_version',
            new_name='version_count',
        ),
        migrations.AlterUniqueTogether(
            name='randomizationversion',
            unique_together={('application_student', 'version_count')},
        ),
    ]
