# Generated by Django 4.0.2 on 2022-04-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0051_rename_randomization_version_randomizationversion_version_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomizationversion',
            old_name='questions_json',
            new_name='exam_json',
        ),
    ]
