# Generated by Django 4.0.2 on 2022-04-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0052_rename_questions_json_randomizationversion_exam_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomizationversion',
            old_name='version_count',
            new_name='version_number',
        ),
        migrations.AlterUniqueTogether(
            name='randomizationversion',
            unique_together={('application_student', 'version_number')},
        ),
    ]
