# Generated by Django 4.0.4 on 2022-04-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0050_application_inspectors_fiscallize'),
        ('applications', '0053_alter_annotation_id_alter_application_id_and_more'),
    ]

    operations = [
    ]
