# Generated by Django 4.0.2 on 2022-04-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0053_alter_annotation_id_alter_application_id_and_more'),
        ('applications', '0053_rename_version_count_randomizationversion_version_number_and_more'),
    ]

    operations = [
    ]
