# Generated by Django 4.0.2 on 2022-05-03 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0054_merge_20220428_1639'),
        ('applications', '0054_merge_20220428_1904'),
    ]

    operations = [
    ]
