# Generated by Django 4.0.2 on 2022-05-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0050_application_duplicate_application'),
        ('applications', '0056_alter_application_inspectors_fiscallize_and_more'),
    ]

    operations = [
    ]
