# Generated by Django 4.0.2 on 2022-06-04 01:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0057_merge_20220505_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('validity', models.DateField(default=django.utils.timezone.now, verbose_name='Validade de acesso')),
                ('application_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hash_accesses', to='applications.applicationstudent', verbose_name='Aplicação do aluno')),
            ],
            options={
                'verbose_name': 'Hash de acesso',
                'verbose_name_plural': 'Hashes de acesso',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
