# Generated by Django 4.0.2 on 2022-06-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0057_merge_20220505_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='read_randomization_version',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Versão da randomização escaneada'),
        ),
    ]
