# Generated by Django 4.0.2 on 2022-06-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0057_merge_20220505_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='performance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
