# Generated by Django 4.0.2 on 2022-06-14 17:48

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bncc', '0014_alter_abiliity_id_alter_actingfield_id_alter_axis_id_and_more'),
        ('subjects', '0015_alter_knowledgearea_id_alter_subject_id_and_more'),
        ('applications', '0058_applicationstudent_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStudentTopicPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('performance', models.FloatField()),
                ('application_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicationstudent', verbose_name='Aluno')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.topic', verbose_name='Tópico')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ApplicationStudentCompetencesPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('performance', models.FloatField()),
                ('application_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicationstudent', verbose_name='Aluno')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bncc.competence', verbose_name='Competência')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ApplicationStudentAbilitiesPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('performance', models.FloatField()),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bncc.abiliity', verbose_name='Habilidade')),
                ('application_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicationstudent', verbose_name='Aluno')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
