# Generated by Django 4.0.2 on 2022-06-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0058_applicationstudent_read_randomization_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstudent',
            name='read_randomization_version',
            field=models.PositiveIntegerField(default=0, verbose_name='Versão da randomização escaneada'),
        ),
    ]
