# Generated by Django 4.0.2 on 2022-06-21 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0058_hashaccess'),
        ('applications', '0059_alter_applicationstudent_read_randomization_version'),
    ]

    operations = [
    ]
