# Generated by Django 4.0.2 on 2022-06-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0059_alter_applicationstudent_read_randomization_version'),
        ('applications', '0059_applicationstudenttopicperformance_and_more'),
    ]

    operations = [
    ]
