# Generated by Django 4.0.2 on 2022-06-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0060_merge_20220617_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstudent',
            name='performance',
        ),
    ]
