# Generated by Django 4.0.2 on 2022-06-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0061_remove_applicationstudent_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Desempenho'),
        ),
    ]
