# Generated by Django 4.0.2 on 2022-06-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0062_applicationstudent_performance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstudent',
            name='performance',
        ),
    ]
