# Generated by Django 4.0.2 on 2022-06-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0060_merge_20220620_2235'),
        ('applications', '0063_remove_applicationstudent_performance'),
    ]

    operations = [
    ]
