# Generated by Django 4.0.6 on 2022-09-20 14:57

from django.db import migrations, models
import fiscallizeon.core.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0065_remove_applicationstudentcompetencesperformance_application_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='answer_sheet',
            field=models.FileField(blank=True, max_length=512, null=True, storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Caderno de respostas'),
        ),
    ]
