# Generated by Django 4.0.6 on 2022-10-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0066_alter_application_answer_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='automatic_creation',
            field=models.BooleanField(default=False),
        ),
    ]
