# Generated by Django 4.0.6 on 2022-10-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0067_application_automatic_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='automatic_creation',
            field=models.BooleanField(default=False, verbose_name='Gera automaticamente aplicações para os novos alunos'),
        ),
    ]
