# Generated by Django 4.0.6 on 2022-10-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0069_application_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='leveling_test',
            field=models.BooleanField(default=False, verbose_name='Lista de nivelamento'),
        ),
    ]
