# Generated by Django 4.0.6 on 2022-10-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0070_application_leveling_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='automatic_creation',
            field=models.BooleanField(default=False, verbose_name='Gerada automaticamente'),
        ),
        migrations.AlterField(
            model_name='application',
            name='leveling_test',
            field=models.BooleanField(default=False, verbose_name='Lista de nivelamento, para novos alunos'),
        ),
    ]
