# Generated by Django 4.0.6 on 2022-11-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0071_alter_application_automatic_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Baixa'), (1, 'Média'), (2, 'Alta')], default=0, verbose_name='Prioridade'),
        ),
    ]
