# Generated by Django 4.0.6 on 2023-04-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0073_application_release_result_at_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='email_sended_to_parent',
            field=models.BooleanField(default=False, verbose_name='Email enviado para o responsável'),
        ),
    ]
