# Generated by Django 4.0.6 on 2023-05-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0074_applicationstudent_email_sended_to_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deadline_for_correction_of_responses',
            field=models.DateField(blank=True, help_text='Limite para os professores corrigirem as provas', null=True, verbose_name='Tempo limite para correção das respostas'),
        ),
    ]
