# Generated by Django 4.0.6 on 2023-05-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0075_application_deadline_for_correction_of_responses'),
        ('applications', '0075_application_show_result_only_for_started_application'),
    ]

    operations = [
    ]
