# Generated by Django 4.0.6 on 2023-05-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0076_merge_20230523_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deadline_for_correction_of_responses',
            field=models.DateField(blank=True, help_text='Limite para os professores corrigirem as respostas', null=True, verbose_name='Tempo limite para correção das respostas'),
        ),
    ]
