# Generated by Django 4.0.6 on 2023-05-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0077_alter_application_deadline_for_correction_of_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='max_time_tolerance',
            field=models.DurationField(default='00:10:00', help_text='Formato: HH:MM:SS', verbose_name='Tempo de tolerância para iniciar a prova'),
        ),
    ]
