# Generated by Django 4.0.6 on 2023-05-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0076_merge_20230523_1829'),
        ('applications', '0078_alter_application_max_time_tolerance'),
    ]

    operations = [
    ]
