# Generated by Django 4.0.6 on 2023-05-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0076_merge_20230522_1634'),
        ('applications', '0079_merge_20230524_0927'),
    ]

    operations = [
    ]
