# Generated by Django 4.0.6 on 2023-06-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0080_merge_20230526_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='feedback_after_clean',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback após zerar prova do aluno'),
        ),
    ]
