# Generated by Django 4.0.6 on 2023-07-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0047_questionhistorytags_note'),
        ('applications', '0080_merge_20230526_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='duplicated_answers',
            field=models.ManyToManyField(blank=True, to='questions.question', verbose_name='Questão'),
        ),
    ]
