# Generated by Django 4.0.6 on 2023-07-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0047_questionhistorytags_note'),
        ('applications', '0081_applicationstudent_duplicated_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstudent',
            name='duplicated_answers',
            field=models.ManyToManyField(blank=True, to='questions.question', verbose_name='Questão com respostas duplicadas'),
        ),
    ]
