# Generated by Django 4.0.6 on 2023-07-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0081_applicationstudent_feedback_after_clean'),
        ('applications', '0082_alter_applicationstudent_duplicated_answers'),
    ]

    operations = [
    ]
