# Generated by Django 4.0.6 on 2023-07-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0083_merge_20230704_1823'),
        ('applications', '0083_merge_20230710_1439'),
    ]

    operations = [
    ]
