# Generated by Django 4.0.6 on 2023-08-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0084_merge_20230710_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='book_is_printed',
            field=models.BooleanField(default=False, verbose_name='Caderno já impresso'),
        ),
        migrations.AddField(
            model_name='application',
            name='print_ready',
            field=models.BooleanField(default=False, verbose_name='Pronta para impressão'),
        ),
    ]
