# Generated by Django 4.0.6 on 2023-08-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0085_application_book_is_printed_application_print_ready'),
        ('applications', '0085_application_end_last_answer_sheet_generation'),
    ]

    operations = [
    ]
