# Generated by Django 4.0.6 on 2023-08-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0086_merge_20230821_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Online'), (3, 'Presencial'), (4, 'Lista de Exercício')], default=2, verbose_name='Qual tipo de aplicação?'),
        ),
    ]
