# Generated by Django 4.0.6 on 2023-08-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0047_questionhistorytags_note'),
        ('applications', '0086_merge_20230821_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='empty_option_questions',
            field=models.ManyToManyField(blank=True, related_name='empty_options', to='questions.question', verbose_name='Questões em branco'),
        ),
    ]
