# Generated by Django 4.0.6 on 2023-08-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0087_applicationstudent_empty_option_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='missed',
            field=models.BooleanField(default=False, verbose_name='O aluno faltou'),
        ),
    ]
