# Generated by Django 4.0.6 on 2023-09-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0087_alter_application_category'),
        ('applications', '0088_applicationstudent_missed'),
    ]

    operations = [
    ]
