# Generated by Django 4.0.6 on 2023-09-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0089_merge_20230911_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bag_pages',
            field=models.IntegerField(default=0, verbose_name='Páginas do malote'),
        ),
        migrations.AddField(
            model_name='application',
            name='book_pages',
            field=models.IntegerField(default=0, verbose_name='Páginas do caderno'),
        ),
    ]
