# Generated by Django 4.0.6 on 2023-09-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0090_application_bag_pages_application_book_pages'),
        ('applications', '0090_application_deadline_for_sending_response_letters'),
    ]

    operations = [
    ]
