# Generated by Django 4.0.6 on 2023-12-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0091_merge_20230926_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('-date', '-start'), 'permissions': (('can_disclose_application', 'Pode liberar resultado de aplicações'), ('can_add_and_remove_students', 'Pode adicionar ou remover alunos'), ('can_remove_generated_bag', 'Pode remover malote gerado'), ('can_duplicate_application', 'Pode duplicar aplicações'), ('can_print_bag_application', 'Pode imprimir malote')), 'verbose_name': 'Aplicação', 'verbose_name_plural': 'Aplicações'},
        ),
    ]
