# Generated by Django 4.0.6 on 2024-02-16 21:49

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0039_inspector_has_new_teacher_experience'),
        ('applications', '0091_merge_20230926_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDeadlineCorrectionResponseException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('date', models.DateField(verbose_name='tempo limite para correção das respostas')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_exceptions', to='applications.application', verbose_name='aplicação')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_exceptions', to='inspectors.inspector', verbose_name='professor')),
            ],
            options={
                'verbose_name': 'exceção da data limite para professores corrigirem respostas',
                'verbose_name_plural': 'exceções da data limite para professores corrigirem respostas',
                'ordering': ('-created_at',),
                'unique_together': {('application', 'teacher')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
