# Generated by Django 4.0.6 on 2023-12-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0092_alter_application_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('-date', '-start'), 'permissions': (('can_disclose_application', 'Pode liberar resultado de aplicações'), ('can_add_and_remove_students', 'Pode adicionar ou remover alunos'), ('can_remove_generated_bag', 'Pode remover malote gerado'), ('can_duplicate_application', 'Pode duplicar aplicações'), ('can_print_bag_application', 'Pode imprimir malote'), ('can_access_print_list', 'Pode acessar a lista de impressão')), 'verbose_name': 'Aplicação', 'verbose_name_plural': 'Aplicações'},
        ),
    ]
