# Generated by Django 4.0.6 on 2024-02-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0092_applicationdeadlinecorrectionresponseexception'),
        ('applications', '0093_alter_application_options'),
    ]

    operations = [
    ]
