# Generated by Django 4.0.6 on 2024-02-27 18:18

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0094_merge_20240222_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRandomizationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('version_number', models.PositiveSmallIntegerField(default=1, verbose_name='Versão')),
                ('sequential', models.PositiveSmallIntegerField(verbose_name='Sequencial')),
                ('exam_json', models.JSONField(verbose_name='Questões')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randomization_versions', to='applications.application', verbose_name='Aplicação')),
            ],
            options={
                'verbose_name': 'Versão da randomização de aplicação',
                'verbose_name_plural': 'Versões das randomizações de aplicação',
                'unique_together': {('application', 'version_number')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='randomizationversion',
            name='application_randomization_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_randomization_versions', to='applications.applicationrandomizationversion', verbose_name='Randomização da aplicação'),
        ),
    ]
