# Generated by Django 4.0.6 on 2024-02-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0094_merge_20240222_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='min_time_pause',
            field=models.DurationField(blank=True, default='01:00:00', help_text='Formato: HH:MM:SS', verbose_name='Tempo mínimo para pausar prova'),
        ),
    ]
