# Generated by Django 4.0.6 on 2024-02-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0095_alter_application_min_time_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deadline_for_correction_of_responses',
            field=models.DateField(blank=True, help_text='Limite para os professores corrigirem as respostas', null=True, verbose_name='Data limite para os professores corrigirem as respostas'),
        ),
        migrations.AlterField(
            model_name='application',
            name='deadline_for_sending_response_letters',
            field=models.DateField(blank=True, help_text='Limite para o envio dos cartões resposta', null=True, verbose_name='Data limite para envio dos cartões resposta'),
        ),
        migrations.AlterField(
            model_name='application',
            name='deadline_to_request_review',
            field=models.DateField(blank=True, help_text='Limite para o aluno solicitar a revisão da resposta', null=True, verbose_name='Data limite para o aluno solicitar correção da resposta'),
        ),
    ]
