# Generated by Django 4.0.6 on 2024-03-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0096_alter_applicationrandomizationversion_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrandomizationversion',
            name='exam_hash',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Hash da prova no momento da geração'),
        ),
    ]
