# Generated by Django 4.0.6 on 2024-02-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0096_alter_application_deadline_for_correction_of_responses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='max_time_tolerance',
            field=models.DurationField(blank=True, default='00:10:00', help_text='Formato: HH:MM:SS', verbose_name='Tempo de tolerância para iniciar a prova'),
        ),
        migrations.AlterField(
            model_name='application',
            name='min_time_finish',
            field=models.DurationField(blank=True, default='01:00:00', help_text='Formato: HH:MM:SS', verbose_name='Tempo mínimo para finalizar prova'),
        ),
    ]
