# Generated by Django 4.0.6 on 2024-04-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0097_alter_application_max_time_tolerance_and_more'),
        ('applications', '0097_applicationrandomizationversion_exam_hash'),
    ]

    operations = [
    ]
