# Generated by Django 4.0.6 on 2024-04-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0098_merge_20240402_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='max_time_finish',
            field=models.DurationField(blank=True, help_text='Formato: HH:MM:SS', null=True, verbose_name='Tempo máximo para realização'),
        ),
    ]
