# Generated by Django 4.0.6 on 2024-07-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0100_historicalapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hide_knowledge_areas_name',
            field=models.BooleanField(default=False, help_text='Designa se durante uma aplicação online, os nomes das áreas do conhecimento devem ser ocultados.', verbose_name='ocultar nome das áreas de conhecimento?'),
        ),
        migrations.AddField(
            model_name='application',
            name='hide_subjects_name',
            field=models.BooleanField(default=False, help_text='Designa se durante uma aplicação online, os nomes das disciplinas devem ser ocultados.', verbose_name='ocultar nome das disciplinas?'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='hide_knowledge_areas_name',
            field=models.BooleanField(default=False, help_text='Designa se durante uma aplicação online, os nomes das áreas do conhecimento devem ser ocultados.', verbose_name='ocultar nome das áreas de conhecimento?'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='hide_subjects_name',
            field=models.BooleanField(default=False, help_text='Designa se durante uma aplicação online, os nomes das disciplinas devem ser ocultados.', verbose_name='ocultar nome das disciplinas?'),
        ),
    ]
