# Generated by Django 4.0.6 on 2024-07-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0098_merge_20240404_2320'),
        ('applications', '0101_application_hide_knowledge_areas_name_and_more'),
    ]

    operations = [
    ]
