# Generated by Django 4.0.6 on 2024-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0102_merge_20240724_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='student_stats_permission_date',
            field=models.DateTimeField(blank=True, help_text='O resultado nunca será liberado ao aluno se esse campo ficar vazio.', null=True, verbose_name='Data para liberação dos resultados para os alunos'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='student_stats_permission_date',
            field=models.DateTimeField(blank=True, help_text='O resultado nunca será liberado ao aluno se esse campo ficar vazio.', null=True, verbose_name='Data para liberação dos resultados para os alunos'),
        ),
    ]
