# Generated by Django 4.0.6 on 2024-11-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0103_alter_application_student_stats_permission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='student_stats_permission_date',
            field=models.DateTimeField(blank=True, help_text='Deixe vazio para que o resultado nunca seja liberado.', null=True, verbose_name='Data para liberação dos resultados para os alunos'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='student_stats_permission_date',
            field=models.DateTimeField(blank=True, help_text='Deixe vazio para que o resultado nunca seja liberado.', null=True, verbose_name='Data para liberação dos resultados para os alunos'),
        ),
    ]
