# Generated by Django 4.0.6 on 2024-12-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0104_alter_application_student_stats_permission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='allow_student_redo_list',
            field=models.BooleanField(default=False, verbose_name='Permitir que o aluno refaça a lista'),
        ),
        migrations.AddField(
            model_name='applicationstudent',
            name='has_redone_exercise_list',
            field=models.BooleanField(default=False, verbose_name='Aluno refez a lista de exercício'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='allow_student_redo_list',
            field=models.BooleanField(default=False, verbose_name='Permitir que o aluno refaça a lista'),
        ),
    ]
