# Generated by Django 4.0.6 on 2025-01-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0105_application_allow_student_redo_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstudent',
            name='has_redone_exercise_list',
        ),
    ]
