# Generated by Django 4.0.6 on 2025-02-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0106_remove_applicationstudent_has_redone_exercise_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='token_online',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Token de acesso para aplicação online'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='token_online',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Token de acesso para aplicação online'),
        ),
    ]
