# Generated by Django 4.2.19 on 2025-05-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0107_application_token_online_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationstudent",
            name="custom_time_finish",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Término personalizado da prova"
            ),
        ),
    ]
