# Generated by Django 4.2.19 on 2025-05-07 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0163_client_has_customize_application"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0107_application_token_online_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Registrado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_types",
                        to="clients.client",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_types",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="application",
            name="application_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de aplicação personalizada",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="applications.applicationtype",
                verbose_name="Tipo de aplicação",
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="application_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Tipo de aplicação personalizada",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="applications.applicationtype",
                verbose_name="Tipo de aplicação",
            ),
        ),
    ]
