# Generated by Django 4.2.19 on 2025-05-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0108_applicationstudent_custom_time_finish'),
        ('applications', '0108_applicationtype_application_application_type_and_more'),
    ]

    operations = [
    ]
