# Generated by Django 4.2.19 on 2025-05-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0109_merge_20250527_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='sheet_exporting_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Exportando'), (2, 'Finalizado'), (3, 'Erro'), (4, 'Desconhecido')], default=0, verbose_name='Status da exportação da folha de respostas'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='sheet_exporting_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Exportando'), (2, 'Finalizado'), (3, 'Erro'), (4, 'Desconhecido')], default=0, verbose_name='Status da exportação da folha de respostas'),
        ),
    ]
