# Generated by Django 4.0.6 on 2023-11-14 11:34

from django.db import migrations, models
import fiscallizeon.core.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('omrnps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npsapplication',
            old_name='day',
            new_name='date',
        ),
        migrations.AddField(
            model_name='npsapplication',
            name='answer_sheet',
            field=models.FileField(blank=True, max_length=512, null=True, storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Caderno de respostas'),
        ),
        migrations.AddField(
            model_name='npsapplication',
            name='sheet_exporting_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Exportando'), (2, 'Finalizado'), (3, 'Erro'), (4, 'Desconhecido')], default=0, verbose_name='Status da exportação da folha de repsostas'),
        ),
    ]
