# Generated by Django 4.0.6 on 2023-11-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omrnps', '0003_rename_day_npsapplication_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npsapplicationaxis',
            options={'ordering': ['order']},
        ),
    ]
