# Generated by Django 4.0.6 on 2023-11-16 17:22

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('omrnps', '0004_alter_npsapplicationaxis_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherorder',
            options={'ordering': ('order',)},
        ),
        migrations.CreateModel(
            name='UnityAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('grade', models.PositiveSmallIntegerField(verbose_name='Nota')),
                ('class_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='omrnps.classapplication', verbose_name='Turma da aplicação')),
            ],
            options={
                'verbose_name': 'Resposta da unidade',
                'verbose_name_plural': 'Respostas da unidade',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
