# Generated by Django 4.0.6 on 2023-11-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omrnps', '0005_alter_teacherorder_options_unityanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npsaxis',
            options={'ordering': ('name',), 'verbose_name': 'Eixo de NPS', 'verbose_name_plural': 'Eixos de NPS'},
        ),
        migrations.AlterField(
            model_name='npsaxis',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
    ]
