# Generated by Django 4.0.6 on 2023-11-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omrnps', '0006_alter_npsaxis_options_alter_npsaxis_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npsaxis',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Nome'),
        ),
    ]
