# Generated by Django 4.0.6 on 2023-11-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omrnps', '0007_alter_npsaxis_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='npsapplication',
            name='name',
            field=models.CharField(default='Formulário de avaliação de professores', max_length=255, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='npsapplication',
            name='show_teahcer_name',
            field=models.BooleanField(default=False, verbose_name='Mostrar nome do professor'),
        ),
    ]
