# Generated by Django 4.0.6 on 2023-11-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omrnps', '0009_omrnpscategory_omrnpsupload_omrnpspage_omrnpserror'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacheranswer',
            options={'verbose_name': 'Avaliação de professor', 'verbose_name_plural': 'Avaliações de professor'},
        ),
        migrations.RemoveField(
            model_name='omrnpsupload',
            name='filename',
        ),
        migrations.AddField(
            model_name='teacheranswer',
            name='omr_nps_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='omrnps.omrnpspage', verbose_name='Folha escaneada'),
        ),
        migrations.AddField(
            model_name='unityanswer',
            name='omr_nps_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='omrnps.omrnpspage', verbose_name='Folha escaneada'),
        ),
        migrations.AlterField(
            model_name='omrnpsupload',
            name='total_pages',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Páginas lidas'),
        ),
        migrations.AlterField(
            model_name='teacheranswer',
            name='nps_application_axis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='omrnps.npsapplicationaxis', verbose_name='Eixo avaliado'),
        ),
    ]
