# Generated by Django 4.0.6 on 2024-05-16 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omrnps', '0010_alter_teacheranswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrnpspage',
            name='class_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='omrnps.classapplication', verbose_name='Turma'),
        ),
    ]
