# Generated by Django 4.0.6 on 2024-05-16 16:23

from django.db import migrations, models
import django.db.models.deletion
import fiscallizeon.core.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0128_merge_20240504_1554'),
        ('omrnps', '0011_omrnpspage_class_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='npsapplication',
            name='client',
            field=models.ForeignKey(default='2b7e2005-69e5-4552-b1d3-ca48fbc24954', on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='npsapplication',
            name='answer_sheet',
            field=models.FileField(blank=True, max_length=512, null=True, storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Malote de folhas de resposta'),
        ),
    ]
