# Generated by Django 4.0.6 on 2024-05-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omrnps', '0013_teacheranswer_created_by_unityanswer_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='omrnpscategory',
            options={'ordering': ('sequential',), 'permissions': (('export_answer_sheet', 'Pode exportar folha de respostas NPS'),), 'verbose_name': 'Categoria de NPS', 'verbose_name_plural': 'Categorias de NPS'},
        ),
    ]
