# Generated by Django 4.0.6 on 2024-08-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omrnps', '0014_alter_omrnpscategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrnpserror',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Outro'), (1, 'QRCode não identificado'), (2, 'Marcações não identificadas'), (3, 'Turma não encontrada')], default=0, verbose_name='Categoria'),
        ),
    ]
