# Generated by Django 3.0.7 on 2020-09-02 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('inspectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='coordination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.SchoolCoordination', verbose_name='Coordenação'),
        ),
    ]
