# Generated by Django 3.0.7 on 2021-02-16 17:02

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_knowledgearea_grades'),
        ('inspectors', '0002_inspector_coordination'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject', verbose_name='Disciplina')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectors.Inspector', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Lecionador da displina',
                'verbose_name_plural': 'Lecionadores das displinas',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='inspector',
            name='subjects',
            field=models.ManyToManyField(through='inspectors.TeacherSubject', to='subjects.Subject', verbose_name='Disciplinas'),
        ),
    ]
