# Generated by Django 3.0.7 on 2021-02-19 16:10

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20210212_1511'),
        ('inspectors', '0003_auto_20210216_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectorCoordination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('coordination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.SchoolCoordination', verbose_name='Coordenação')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectors.Inspector', verbose_name='Fiscal')),
            ],
            options={
                'verbose_name': 'Fiscal da coordenação',
                'verbose_name_plural': 'Fiscais das coordenações',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='inspector',
            name='coordinations',
            field=models.ManyToManyField(blank=True, related_name='inspectors', through='inspectors.InspectorCoordination', to='clients.SchoolCoordination', verbose_name='Coordenações'),
        ),
    ]
