# Generated by Django 3.0.7 on 2021-01-12 17:57

from django.db import migrations, models

from fiscallizeon.inspectors.models import Inspector

def migrate_coordinations(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0004_auto_20210219_1310'),
    ]

    operations = [
        migrations.RunPython(migrate_coordinations, reverse_code=migrations.RunPython.noop),
    ]
