# Generated by Django 3.0.7 on 2021-02-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0005_migrate_coordinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='coordination',
        ),
    ]
