# Generated by Django 3.0.7 on 2021-02-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_knowledgearea_grades'),
        ('inspectors', '0006_remove_inspector_coordination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='subjects',
            field=models.ManyToManyField(blank=True, through='inspectors.TeacherSubject', to='subjects.Subject', verbose_name='Disciplinas'),
        ),
    ]
