# Generated by Django 3.0.7 on 2021-03-15 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_knowledgearea_grades'),
        ('inspectors', '0007_auto_20210225_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectorcoordination',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspectors.Inspector', verbose_name='Fiscal'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects.Subject', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspectors.Inspector', verbose_name='Professor'),
        ),
    ]
