# Generated by Django 3.0.7 on 2021-05-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0008_auto_20210315_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='is_discipline_coordinator',
            field=models.BooleanField(default=False, verbose_name='É coordenador de disciplina'),
        ),
    ]
