# Generated by Django 3.2.3 on 2021-09-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0009_inspector_is_discipline_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='can_approve',
            field=models.BooleanField(default=True, verbose_name='Aprovar'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='can_fail',
            field=models.BooleanField(default=True, verbose_name='Reprovar'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='can_seggest_correction',
            field=models.BooleanField(default=True, verbose_name='Sugerir Correção'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='can_update_note',
            field=models.BooleanField(default=True, verbose_name='Atualizar Nota'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='can_viewed',
            field=models.BooleanField(default=True, verbose_name='dar Visto'),
        ),
    ]
