# Generated by Django 3.2.3 on 2021-09-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0010_auto_20210923_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspector',
            old_name='can_seggest_correction',
            new_name='can_suggest_correction',
        ),
    ]
