# Generated by Django 3.2.4 on 2021-09-23 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_alter_subject_options'),
        ('inspectors', '0011_rename_can_seggest_correction_inspector_can_suggest_correction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectorcoordination',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectors.inspector', verbose_name='Fiscal'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectors.inspector', verbose_name='Professor'),
        ),
    ]
