# Generated by Django 3.2.4 on 2022-02-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0014_auto_20220201_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='can_response_wrongs',
            field=models.BooleanField(default=True, verbose_name='Pode responder erratas'),
        ),
    ]
