# Generated by Django 3.2.4 on 2022-02-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0015_alter_inspector_can_response_wrongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='can_answer_wrongs_others_teachers',
            field=models.BooleanField(default=False, verbose_name='Pode responder erratas de outros professores'),
        ),
    ]
