# Generated by Django 4.0.2 on 2022-02-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0016_inspector_can_answer_wrongs_others_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='can_correct_questions_other_teachers',
            field=models.BooleanField(default=False, verbose_name='Pode corrigir questões de outros professores'),
        ),
    ]
