# Generated by Django 3.2.3 on 2022-02-24 16:24
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0017_inspector_can_correct_questions_other_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='can_correct_questions_other_teachers',
            field=models.BooleanField(default=False, verbose_name='Pode corrigir questões de outros professores da mesma disciplina'),
        ),
    ]
