# Generated by Django 4.0.2 on 2022-03-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_schoolclass_id_erp'),
        ('inspectors', '0018_alter_inspector_can_correct_questions_other_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='classes_he_teaches',
            field=models.ManyToManyField(blank=True, related_name='inspectors', to='classes.SchoolClass', verbose_name='Turmas que ministra'),
        ),
    ]
