# Generated by Django 4.0.2 on 2022-04-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0018_alter_inspector_can_correct_questions_other_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='inspectorcoordination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em'),
        ),
        migrations.AlterField(
            model_name='inspectorcoordination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em'),
        ),
    ]
