# Generated by Django 4.0.4 on 2022-04-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0019_inspector_classes_he_teaches'),
        ('inspectors', '0021_alter_inspector_id_alter_inspectorcoordination_id_and_more'),
    ]

    operations = [
    ]
