# Generated by Django 4.0.2 on 2022-08-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0023_alter_inspector_id_alter_inspectorcoordination_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='can_annul',
            field=models.BooleanField(default=True, verbose_name='Pode anular'),
        ),
    ]
