# Generated by Django 4.0.2 on 2022-09-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_alter_course_created_at_alter_coursetype_created_at_and_more'),
        ('inspectors', '0024_inspector_can_annul'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubject',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='classes',
            field=models.ManyToManyField(blank=True, to='classes.SchoolClass', verbose_name='Turmas '),
        ),
    ]
