# Generated by Django 4.0.6 on 2022-10-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0025_teachersubject_is_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersubject',
            name='is_abstract',
        ),
        migrations.AddField(
            model_name='inspector',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='Professor abstrato'),
        ),
    ]
