# Generated by Django 4.0.2 on 2022-09-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_alter_course_created_at_alter_coursetype_created_at_and_more'),
        ('inspectors', '0025_teachersubject_active_teachersubject_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubject',
            name='grades',
            field=models.ManyToManyField(blank=True, to='classes.Grade', verbose_name='Séries'),
        ),
    ]
