# Generated by Django 4.0.2 on 2022-09-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0026_teachersubject_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersubject',
            name='grades',
        ),
    ]
