# Generated by Django 4.0.2 on 2022-09-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_alter_course_created_at_alter_coursetype_created_at_and_more'),
        ('inspectors', '0027_remove_teachersubject_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubject',
            name='school_year',
            field=models.SmallIntegerField(blank=True, default='2022', verbose_name='Ano letivo'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='classes',
            field=models.ManyToManyField(blank=True, to='classes.SchoolClass', verbose_name='Turmas'),
        ),
    ]
