# Generated by Django 4.0.6 on 2022-10-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0028_teachersubject_school_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='can_correct_questions_other_teachers',
            field=models.BooleanField(default=False, verbose_name='pode corrigir respostas de alunos de cadernos de outros professores da mesma disciplina'),
        ),
    ]
