# Generated by Django 4.0.6 on 2022-11-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0029_alter_inspector_can_correct_questions_other_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='already_integrated_with_superpro',
            field=models.BooleanField(default=False, verbose_name='já fez integração com Super Professor?'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='enable_integration_superpro',
            field=models.BooleanField(default=False, verbose_name='habilitar integração com Super Professor?'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='superpro_data',
            field=models.JSONField(blank=True, null=True, verbose_name='dados do superpro'),
        ),
    ]
