# Generated by Django 4.0.6 on 2022-10-26 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0026_remove_teachersubject_is_abstract_and_more'),
        ('inspectors', '0029_alter_inspector_can_correct_questions_other_teachers'),
    ]

    operations = [
    ]
