# Generated by Django 4.0.6 on 2022-11-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0030_inspector_already_integrated_with_superpro_and_more'),
        ('inspectors', '0030_merge_20221026_1937'),
    ]

    operations = [
    ]
