# Generated by Django 4.0.6 on 2022-11-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0031_merge_20221112_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='enable_integration_superpro_via_file',
            field=models.BooleanField(default=False, verbose_name='habilitar integração com Super Professor via arquivo?'),
        ),
    ]
