# Generated by Django 4.0.6 on 2023-01-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0032_inspector_enable_integration_superpro_via_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubject',
            name='school_year',
            field=models.SmallIntegerField(blank=True, default='2023', verbose_name='Ano letivo'),
        ),
    ]
