# Generated by Django 4.0.6 on 2023-02-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0033_alter_teachersubject_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='skip_introduction_questions_bank',
            field=models.BooleanField(default=False, verbose_name='Pular introdução do banco de questões?'),
        ),
    ]
