# Generated by Django 4.0.6 on 2023-03-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0034_inspector_skip_introduction_questions_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='has_question_formatter',
            field=models.BooleanField(default=False, verbose_name='O professor pode utilizar o formatador de questões'),
        ),
    ]
