# Generated by Django 4.0.6 on 2023-11-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0035_inspector_has_question_formatter'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='has_ia_creation',
            field=models.BooleanField(default=False, verbose_name='O professor pode criar questão com IA'),
        ),
    ]
