# Generated by Django 4.0.6 on 2024-01-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0035_inspector_has_question_formatter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubject',
            name='school_year',
            field=models.SmallIntegerField(blank=True, default='2024', verbose_name='Ano letivo'),
        ),
    ]
