# Generated by Django 4.0.6 on 2023-12-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0035_inspector_has_question_formatter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspector',
            options={'permissions': (('can_change_permissions_inspector', 'Pode alterar as permissões de fiscais'), ('can_change_permissions_teacher', 'Pode alterar as permissões de professores'), ('view_teacher', 'Pode visualizar professores'), ('add_teacher', 'Pode adicionar professores'), ('change_teacher', 'Pode alterar professores'), ('delete_teacher', 'Pode deletar professores')), 'verbose_name': 'Fiscal', 'verbose_name_plural': 'Fiscais'},
        ),
    ]
