# Generated by Django 4.0.6 on 2024-01-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0036_alter_teachersubject_school_year'),
        ('inspectors', '0036_inspector_has_ia_creation'),
    ]

    operations = [
    ]
