# Generated by Django 4.0.6 on 2024-01-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0036_alter_teachersubject_school_year'),
        ('inspectors', '0037_alter_inspector_options'),
    ]

    operations = [
    ]
