# Generated by Django 4.0.6 on 2024-01-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0038_merge_20240117_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='has_new_teacher_experience',
            field=models.BooleanField(default=False, verbose_name='Tem acesso a nova experiência de professor'),
        ),
    ]
