# Generated by Django 4.0.6 on 2024-01-31 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0039_alter_inspector_options'),
        ('inspectors', '0039_inspector_has_new_teacher_experience'),
    ]

    operations = [
    ]
