# Generated by Django 4.0.6 on 2024-04-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0042_alter_inspector_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspector',
            options={'permissions': (('can_change_permissions_inspector', 'Pode alterar as permissões de fiscais'), ('can_change_permissions_teacher', 'Pode alterar as permissões de professores'), ('can_add_exercice_list', 'Pode adicionar lista de exercícios'), ('view_teacher', 'Pode visualizar professores'), ('add_teacher', 'Pode adicionar professores'), ('change_teacher', 'Pode alterar professores'), ('delete_teacher', 'Pode deletar professores'), ('can_import_teacher', 'Pode importar professores'), ('can_reset_password', 'Pode resetar senha dos professores')), 'verbose_name': 'Fiscal', 'verbose_name_plural': 'Fiscais'},
        ),
    ]
