# Generated by Django 4.0.6 on 2024-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0043_alter_inspector_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='is_ispector_ia',
            field=models.BooleanField(default=False, verbose_name='Professor virtual (IA)'),
        ),
    ]
