# Generated by Django 4.0.6 on 2024-07-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0044_inspector_is_ispector_ia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspector',
            old_name='is_ispector_ia',
            new_name='is_inspector_ia',
        ),
    ]
