# Generated by Django 4.0.6 on 2024-11-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0045_rename_is_ispector_ia_inspector_is_inspector_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='show_questions_bank_tutorial',
            field=models.BooleanField(default=True, verbose_name='Exibir tutorial do banco de questões'),
        ),
    ]
