# Generated by Django 4.0.6 on 2024-11-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0046_inspector_can_access_coordinator_profile'),
        ('inspectors', '0046_inspector_show_questions_bank_tutorial'),
    ]

    operations = [
    ]
