# Generated by Django 4.0.6 on 2025-01-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0047_merge_20241125_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubject',
            name='school_year',
            field=models.SmallIntegerField(blank=True, default='2025', verbose_name='Ano letivo'),
        ),
    ]
