# Generated by Django 3.2.4 on 2021-11-12 20:09

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0039_alter_application_student_stats_permission_date'),
        ('clients', '0020_merge_20210821_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Capacidade máxima de alunos')),
                ('coordination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='clients.schoolcoordination')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RoomDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Por nome'), (1, 'Por nome e turma')], verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Ensalamento',
                'verbose_name_plural': 'Ensalamentos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RoomDistributionStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('application_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_distribution', to='applications.applicationstudent')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='distribution.roomdistribution')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='distribution.room')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
