# Generated by Django 3.2.4 on 2021-11-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomDistributionStudent',
        ),
    ]
