# Generated by Django 3.2.4 on 2021-12-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_roomdistributionstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdistribution',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Por nome e série'), (1, 'Por nome e turma')], verbose_name='Categoria'),
        ),
    ]
