# Generated by Django 3.2.4 on 2021-12-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_roomdistributionstudent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AlterField(
            model_name='roomdistribution',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Por nome e série'), (1, 'Por nome e turma')], verbose_name='Categoria'),
        ),
    ]
