# Generated by Django 3.2.4 on 2022-01-03 12:54

from django.db import migrations, models
import fiscallizeon.core.storage_backends
import fiscallizeon.distribution.models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_auto_20211206_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdistribution',
            name='exams_bag',
            field=models.FileField(blank=True, null=True, storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to=fiscallizeon.distribution.models.exams_bag_file_directory_path, verbose_name='Malote de provas'),
        ),
        migrations.AddField(
            model_name='roomdistribution',
            name='exams_bag_generation_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Número de gerações de malote de provas'),
        ),
        migrations.AddField(
            model_name='roomdistribution',
            name='last_exams_bag_generation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última geração de malote de provas'),
        ),
    ]
