# Generated by Django 3.2.4 on 2022-01-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_auto_20220103_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdistribution',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Desconhecido'), (1, 'Aguardando exportação'), (2, 'Exportando'), (3, 'Exportação finalizada'), (4, 'Erro de exportação')], default=1, verbose_name='Status da exportação'),
        ),
    ]
