# Generated by Django 3.2.4 on 2022-01-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_alter_roomdistribution_category'),
        ('distribution', '0006_roomdistribution_status'),
    ]

    operations = [
    ]
