# Generated by Django 3.2.4 on 2022-01-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_merge_20220106_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdistribution',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Desconhecido'), (1, 'Aguardando exportação'), (2, 'Exportando malote'), (3, 'Malote exportado'), (4, 'Erro de exportação')], default=1, verbose_name='Status da exportação'),
        ),
    ]
