# Generated by Django 3.2.4 on 2022-02-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_id_erp'),
        ('distribution', '0008_alter_roomdistribution_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomdistributionstudent',
            options={'verbose_name': 'Aluno ensalado', 'verbose_name_plural': 'Alunos ensalados'},
        ),
        migrations.AlterUniqueTogether(
            name='roomdistributionstudent',
            unique_together={('distribution', 'student', 'room')},
        ),
    ]
