# Generated by Django 4.0.2 on 2022-02-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0009_auto_20220209_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdistribution',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Por nome e coordenação'), (0, 'Por nome e série'), (1, 'Por nome e turma')], verbose_name='Categoria'),
        ),
    ]
