# Generated by Django 4.0.2 on 2022-03-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0010_alter_roomdistribution_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdistribution',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Desconhecido'), (1, 'Aguardando exportação do malote'), (2, 'Exportando malote'), (3, 'Malote exportado'), (4, 'Erro de exportação'), (5, 'Distribuindo alunos')], default=1, verbose_name='Status da exportação'),
        ),
    ]
