# Generated by Django 4.0.6 on 2022-12-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0015_alter_room_id_alter_roomdistribution_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdistribution',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='Já foi impresso'),
        ),
    ]
