# Generated by Django 4.0.6 on 2022-12-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0016_roomdistribution_is_printed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdistribution',
            name='is_printed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Já foi impresso'),
        ),
    ]
