# Generated by Django 4.0.6 on 2024-04-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0017_alter_roomdistribution_is_printed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdistribution',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Desconhecido'), (1, 'Sem malote gerado'), (2, 'Exportando malote'), (3, 'Malote exportado'), (4, 'Erro de exportação'), (5, 'Distribuindo alunos')], default=1, verbose_name='Status da exportação'),
        ),
    ]
