# Generated by Django 4.2.19 on 2025-03-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0018_alter_roomdistribution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdistribution',
            name='shuffle_students',
            field=models.BooleanField(default=False, verbose_name='Ordenar alunos aleatoriamente?'),
        ),
    ]
