# Generated by Django 4.2.19 on 2025-03-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0019_roomdistribution_shuffle_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdistribution',
            name='balance_rooms',
            field=models.BooleanField(default=False, help_text='O sistema tentará equilibrar a quantidade de alunos por sala, de modo que a ocupação percentual entre elas seja o mais próximo possível', verbose_name='Equilibrar quantidade de alunos entre as salas selecionadas?'),
        ),
        migrations.AlterField(
            model_name='roomdistribution',
            name='shuffle_students',
            field=models.BooleanField(default=False, help_text='O sistema respeitará o tipo de ensalamento selecionado mas não irá alocar os alunos de modo alfabético', verbose_name='Ignorar ordenação alfabética?'),
        ),
    ]
