# Generated by Django 4.0.6 on 2023-11-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiquery',
            name='finish_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('stop', 'Sucesso'), ('length', 'Incompleto'), ('function_call', 'Chamada de função'), ('content_filter', 'Filtro de conteúdo'), ('null', 'Desconhecido')], null=True, verbose_name='Status de finalização'),
        ),
        migrations.AlterField(
            model_name='openaiquery',
            name='input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de tokens de entrada'),
        ),
        migrations.AlterField(
            model_name='openaiquery',
            name='output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de tokens de saída'),
        ),
    ]
