# Generated by Django 4.0.6 on 2023-11-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_openaiquery_finish_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openaiquery',
            options={'verbose_name': 'Prompt GPT', 'verbose_name_plural': 'Prompts GPT'},
        ),
        migrations.AlterField(
            model_name='openaiquery',
            name='finish_reason',
            field=models.CharField(blank=True, choices=[('stop', 'Sucesso'), ('length', 'Incompleto'), ('function_call', 'Chamada de função'), ('content_filter', 'Filtro de conteúdo'), ('null', 'Desconhecido')], default='null', max_length=64, null=True, verbose_name='Status de finalização'),
        ),
    ]
