# Generated by Django 4.0.6 on 2023-12-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_openaiquery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiquery',
            name='prompt_category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Geração de questão'), (2, 'Melhoramento de questão')], default=0, verbose_name='Categoria do prompt'),
        ),
    ]
