# Generated by Django 4.0.6 on 2024-01-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0021_alter_subjectrelation_subjects'),
        ('ai', '0005_alter_openaiquery_prompt_category_questionimprove'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionimprove',
            name='abilities_status',
            field=models.SmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Ignorado'), (2, 'Aplicado')], default=0, verbose_name='Habilidades aplicadas?'),
        ),
        migrations.AddField(
            model_name='questionimprove',
            name='commented_answer_status',
            field=models.SmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Ignorado'), (2, 'Aplicado')], default=0, verbose_name='Resposta comentada aplicada?'),
        ),
        migrations.AddField(
            model_name='questionimprove',
            name='competences_status',
            field=models.SmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Ignorado'), (2, 'Aplicado')], default=0, verbose_name='Competências aplicadas?'),
        ),
        migrations.AddField(
            model_name='questionimprove',
            name='enunciation_status',
            field=models.SmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Ignorado'), (2, 'Aplicado')], default=0, verbose_name='Correção de enunciado aplicada?'),
        ),
        migrations.AddField(
            model_name='questionimprove',
            name='topics_status',
            field=models.SmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Ignorado'), (2, 'Aplicado')], default=0, verbose_name='Assuntos aplicados?'),
        ),
        migrations.AlterField(
            model_name='questionimprove',
            name='topics',
            field=models.ManyToManyField(to='subjects.topic', verbose_name='Assuntos'),
        ),
    ]
