# Generated by Django 4.0.6 on 2024-01-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_questionimprove_abilities_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionimprove',
            name='liked_abilities',
            field=models.SmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Gostou'), (2, 'Não gostou')], default=0, verbose_name='Gostou Habilidades?'),
        ),
        migrations.AddField(
            model_name='questionimprove',
            name='liked_commented_answer',
            field=models.SmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Gostou'), (2, 'Não gostou')], default=0, verbose_name='Gostou da Resposta comentada?'),
        ),
        migrations.AddField(
            model_name='questionimprove',
            name='liked_competences',
            field=models.SmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Gostou'), (2, 'Não gostou')], default=0, verbose_name='Gostou Competências?'),
        ),
        migrations.AddField(
            model_name='questionimprove',
            name='liked_enunciation',
            field=models.SmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Gostou'), (2, 'Não gostou')], default=0, verbose_name='Gostou da sugestão do enunciado?'),
        ),
        migrations.AddField(
            model_name='questionimprove',
            name='liked_topics',
            field=models.SmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Gostou'), (2, 'Não gostou')], default=0, verbose_name='Gostou dos assuntos?'),
        ),
    ]
