# Generated by Django 4.0.6 on 2024-01-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bncc', '0016_remove_competenceexamperformance_competence_and_more'),
        ('subjects', '0021_alter_subjectrelation_subjects'),
        ('ai', '0008_questionimprove_applied_abilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimprove',
            name='applied_abilities',
            field=models.ManyToManyField(blank=True, related_name='applieds', to='bncc.abiliity', verbose_name='Habilidades Aplicados'),
        ),
        migrations.AlterField(
            model_name='questionimprove',
            name='applied_competences',
            field=models.ManyToManyField(blank=True, related_name='applieds', to='bncc.competence', verbose_name='Competências Aplicados'),
        ),
        migrations.AlterField(
            model_name='questionimprove',
            name='applied_topics',
            field=models.ManyToManyField(blank=True, related_name='applieds', to='subjects.topic', verbose_name='Assuntos Aplicados'),
        ),
    ]
