# Generated by Django 4.0.6 on 2024-01-23 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0113_client_has_new_teacher_experience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0009_alter_questionimprove_applied_abilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiquery',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='openaiquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
