# Generated by Django 4.0.6 on 2024-01-23 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0113_client_has_new_teacher_experience'),
        ('ai', '0010_openaiquery_client_openaiquery_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiquery',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Cliente'),
        ),
    ]
