# Generated by Django 4.0.6 on 2024-04-18 20:28

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_aicredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('identifier', models.CharField(max_length=255, unique=True, verbose_name='identificador')),
                ('input_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='preço entrada/1M tokens (em dólar)')),
                ('output_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='preço saída/1M tokens (em dólar)')),
            ],
            options={
                'verbose_name': 'modelo de IA',
                'verbose_name_plural': 'modelos de IA',
                'ordering': ('-created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='openaiquery',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='custo (em dólar)'),
        ),
        migrations.AddField(
            model_name='openaiquery',
            name='ai_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ai.aimodel', verbose_name='modelo de IA'),
        ),
    ]
