# Generated by Django 4.0.6 on 2024-12-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0014_create_model_and_add_to_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiquery',
            name='prompt_category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Geração de questão'), (2, 'Melhoramento de questão'), (3, 'Resolução de questão'), (4, 'Correção de questão discursiva')], default=0, verbose_name='Categoria do prompt'),
        ),
    ]
