# Generated by Django 4.0.6 on 2024-04-11 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import fiscallizeon.core.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('type', models.CharField(choices=[('students', 'students'), ('students', 'teacher'), ('coordinations', 'coordinations')], default='students', max_length=50, verbose_name='Onde foi a importação')),
                ('errors', fiscallizeon.core.fields.ChoiceArrayField(base_field=models.TextField(verbose_name='Erro'), blank=True, null=True, size=None, verbose_name='Erro')),
                ('file_url', models.URLField(max_length=500, verbose_name='Arquivo enviado')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
