# Generated by Django 4.0.6 on 2024-05-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_alter_import_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='type',
            field=models.CharField(choices=[('students', 'students'), ('students', 'teacher'), ('coordinations', 'coordinations'), ('exams', 'Instrumentos avaliativos'), ('elaboration_request', 'Solicitação de elaboração'), ('application_students', 'Alunos em aplicação')], default='students', max_length=50, verbose_name='Onde foi a importação'),
        ),
    ]
