# Generated by Django 4.2.19 on 2025-05-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0003_alter_import_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='type',
            field=models.CharField(choices=[('students', 'students'), ('students', 'teacher'), ('coordinations', 'coordinations'), ('exams', 'Instrumentos avaliativos'), ('elaboration_request', 'Solicitação de elaboração'), ('application_students', 'Alunos em aplicação'), ('essay_grades', 'Notas de redação')], default='students', max_length=50, verbose_name='Onde foi a importação'),
        ),
    ]
