# Generated by Django 3.0.7 on 2020-06-13 17:48

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('inspectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('event_type', models.PositiveIntegerField(choices=[(0, 'Outro'), (1, 'Banheiro')], default=1, verbose_name='Tipo de evento')),
                ('start', models.DateTimeField(verbose_name='Hora de início')),
                ('end', models.DateTimeField(verbose_name='Horário final')),
                ('response', models.PositiveIntegerField(choices=[(0, 'Aprovado'), (1, 'Rejeitado'), (2, 'Pendente')], default=2, verbose_name='Resposta do fiscal')),
                ('response_datetime', models.DateTimeField(verbose_name='Hora da resposta')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectors.Inspector', verbose_name='Fiscal')),
                ('student_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.ApplicationStudent')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
