# Generated by Django 3.0.7 on 2020-06-16 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20200616_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Fiscal'),
        ),
        migrations.AlterField(
            model_name='event',
            name='response_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora da resposta'),
        ),
    ]
