# Generated by Django 3.0.7 on 2020-06-17 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_merge_20200616_1620'),
        ('events', '0005_textmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='application_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='applications.ApplicationStudent', verbose_name='Usuário'),
        ),
    ]
