# Generated by Django 3.0.7 on 2020-06-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200617_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveIntegerField(choices=[(1, 'Banheiro'), (0, 'Outro')], default=1, verbose_name='Tipo de evento'),
        ),
    ]
