# Generated by Django 3.0.7 on 2020-06-18 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20200618_1546'),
        ('events', '0007_auto_20200618_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveIntegerField(choices=[(0, 'Outro'), (1, 'Banheiro')], default=1, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='student_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.ApplicationStudent'),
        ),
    ]
