# Generated by Django 3.0.7 on 2020-06-23 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20200619_1455'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_auto_20200618_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='application_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='applications.ApplicationStudent', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
