# Generated by Django 3.0.7 on 2020-08-07 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_auto_20200805_1600'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_auto_20200623_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='content',
            field=models.TextField(verbose_name='Conteúdo da mensagem'),
        ),
        migrations.CreateModel(
            name='ApplicationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('content', models.TextField(max_length=255, verbose_name='Conteúdo da mensagem')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='applications.Application', verbose_name='Aplicação')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Fiscal')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
