# Generated by Django 3.0.7 on 2020-10-27 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200807_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-created_at',), 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
