# Generated by Django 3.0.7 on 2021-01-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20201027_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveIntegerField(choices=[(0, 'Outro'), (1, 'Banheiro'), (2, 'Saída da aba de aplicação')], default=1, verbose_name='Tipo de evento'),
        ),
    ]
