# Generated by Django 3.0.7 on 2020-12-29 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0012_questionerrorreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionerrorreport',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal'),
        ),
    ]
