# Generated by Django 3.0.7 on 2021-01-18 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0013_auto_20201229_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveIntegerField(choices=[(0, 'Outro'), (1, 'Banheiro'), (2, 'Saída da aba de aplicação')], default=1, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='questionerrorreport',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to=settings.AUTH_USER_MODEL, verbose_name='Aluno'),
        ),
    ]
