# Generated by Django 3.0.7 on 2021-01-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20210118_1510'),
        ('events', '0012_auto_20210108_1825'),
    ]

    operations = [
    ]
