# Generated by Django 3.0.7 on 2021-02-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_merge_20210125_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationmessage',
            options={'verbose_name': 'Mensagem de aplicação', 'verbose_name_plural': 'Mensagens de aplicação'},
        ),
        migrations.AlterModelOptions(
            name='textmessage',
            options={'verbose_name': 'Mensagem de aluno', 'verbose_name_plural': 'Mensagens de alunos'},
        ),
    ]
