# Generated by Django 3.0.7 on 2021-03-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20210225_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationmessage',
            options={'ordering': ('created_at',), 'verbose_name': 'Mensagem de aplicação', 'verbose_name_plural': 'Mensagens de aplicação'},
        ),
        migrations.AlterModelOptions(
            name='questionerrorreport',
            options={'ordering': ('-created_at',), 'verbose_name': 'Erro em questão', 'verbose_name_plural': 'Erros em questões'},
        ),
        migrations.AlterModelOptions(
            name='textmessage',
            options={'ordering': ('created_at',), 'verbose_name': 'Mensagem de aluno', 'verbose_name_plural': 'Mensagens de alunos'},
        ),
    ]
