# Generated by Django 3.0.7 on 2021-03-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20210311_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionerrorreport',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Resolvido'), (1, 'Pendente')], default=1, verbose_name='Situação'),
        ),
    ]
