# Generated by Django 3.2.4 on 2022-01-25 18:44

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import fiscallizeon.core.storage_backends
import fiscallizeon.materials.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0010_alter_subject_options'),
        ('clients', '0031_rename_has_study_meterial_client_has_study_material'),
        ('classes', '0009_alter_schoolclass_school_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('material', models.FileField(blank=True, null=True, storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to=fiscallizeon.materials.models.study_material_file_directory_path, verbose_name='Arquivo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Cliente')),
                ('school_classes', models.ManyToManyField(to='classes.SchoolClass', verbose_name='Turmas')),
                ('subjects', models.ManyToManyField(to='subjects.Subject', verbose_name='Disciplinas')),
            ],
            options={
                'verbose_name': 'Material de estudo',
                'verbose_name_plural': 'Materiais de estudo',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
