# Generated by Django 3.2.4 on 2022-01-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_favoritestudymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='stage',
            field=models.SmallIntegerField(choices=[(1, '1ª Etapa'), (2, '2ª Etapa'), (3, '3ª Etapa'), (4, '4ª Etapa'), (5, '5ª Etapa'), (6, '6ª Etapa'), (7, 'Geral')], default=7, verbose_name='Etapa de Ensino'),
        ),
    ]
