# Generated by Django 3.2.4 on 2022-01-27 14:53

from django.db import migrations, models
import fiscallizeon.core.storage_backends
import fiscallizeon.materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_studymaterial_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='material',
            field=models.FileField(default='', storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to=fiscallizeon.materials.models.study_material_file_directory_path, verbose_name='Arquivo'),
        ),
    ]
