# Generated by Django 3.2.4 on 2022-02-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_auto_20220208_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='elaboration_material_study',
            field=models.DateField(null=True, verbose_name='Liberação de material de estudo'),
        ),
    ]
