# Generated by Django 3.2.4 on 2022-02-15 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_studymaterial_elaboration_material_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymaterial',
            old_name='elaboration_material_study',
            new_name='release_material_study',
        ),
    ]
