# Generated by Django 4.0.2 on 2022-02-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_rename_elaboration_material_study_studymaterial_release_material_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='emphasis',
            field=models.BooleanField(default=False, verbose_name='Em destaque'),
        ),
    ]
