# Generated by Django 3.2.3 on 2022-02-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_studymaterial_emphasis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='emphasis',
            field=models.BooleanField(default=False, help_text='Marque esta opção se deseja que o material fique em destaque para o aluno', verbose_name='Em destaque'),
        ),
    ]
