# Generated by Django 4.0.2 on 2022-03-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_alter_subject_parent_subject_alter_topic_name'),
        ('classes', '0010_schoolclass_id_erp'),
        ('materials', '0011_alter_studymaterial_emphasis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='grades',
            field=models.ManyToManyField(blank=True, to='classes.Grade', verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='school_classes',
            field=models.ManyToManyField(blank=True, null=True, to='classes.SchoolClass', verbose_name='Turmas'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='subjects.Subject', verbose_name='Disciplinas'),
        ),
    ]
