# Generated by Django 4.0.2 on 2022-03-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_alter_studymaterial_emphasis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='release_material_study',
            field=models.DateTimeField(null=True, verbose_name='Liberação de material de estudo'),
        ),
    ]
