# Generated by Django 4.0.2 on 2022-03-07 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0066_auto_20220214_1437'),
        ('materials', '0013_alter_studymaterial_school_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='Caderno'),
        ),
    ]
