# Generated by Django 4.0.2 on 2022-03-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0068_remove_exam_materials'),
        ('materials', '0014_studymaterial_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='exams.exam', verbose_name='Caderno'),
        ),
    ]
