# Generated by Django 4.0.2 on 2022-03-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_alter_studymaterial_release_material_study'),
        ('materials', '0015_alter_studymaterial_exam'),
    ]

    operations = [
    ]
