# Generated by Django 4.0.4 on 2022-04-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_alter_favoritestudymaterial_id_and_more'),
        ('materials', '0016_merge_20220312_1022'),
    ]

    operations = [
    ]
