# Generated by Django 4.0.6 on 2022-09-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0017_delete_topicexamperformance'),
        ('materials', '0018_alter_favoritestudymaterial_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='answer_video',
            field=models.URLField(blank=True, null=True, verbose_name='Link da resposta em vídeo'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='answer_video_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Panda Vídeo'), (1, 'Youtube')], default=1, null=True, verbose_name='Fonte do vídeo'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='material_type',
            field=models.SmallIntegerField(choices=[(0, 'Vídeo'), (1, 'Arquivo')], default=1, verbose_name='Tipo de material'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='materials', to='subjects.topic', verbose_name='Assuntos abordados'),
        ),
    ]
