# Generated by Django 4.0.6 on 2022-09-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_studymaterial_answer_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='topics',
        ),
    ]
