# Generated by Django 4.0.6 on 2022-09-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_remove_studymaterial_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='material_type',
        ),
    ]
