# Generated by Django 4.0.6 on 2023-05-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_remove_studymaterial_material_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymaterial',
            old_name='answer_video',
            new_name='material_video',
        ),
        migrations.RenameField(
            model_name='studymaterial',
            old_name='answer_video_type',
            new_name='material_video_type',
        ),
    ]
