# Generated by Django 4.0.6 on 2023-05-22 22:32

from django.db import migrations, models
import fiscallizeon.core.storage_backends
import fiscallizeon.materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_rename_answer_video_studymaterial_material_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='material',
            field=models.FileField(blank=True, default='', null=True, storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to=fiscallizeon.materials.models.study_material_file_directory_path, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='material_video',
            field=models.URLField(blank=True, null=True, verbose_name='Vídeo do material'),
        ),
    ]
