# Generated by Django 4.0.6 on 2025-04-16 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0162_merge_20250412_1519'),
        ('materials', '0024_studymaterial_send_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='teaching_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.teachingstage', verbose_name='etapa do ensino'),
        ),
    ]
