# Generated by Django 3.2.3 on 2021-06-25 20:16

from django.db import migrations, models
import django_lifecycle.mixins
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_migration_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('privacy', tinymce.models.HTMLField(verbose_name='Enunciado da questão')),
                ('terms_of_use', tinymce.models.HTMLField(verbose_name='Termos de uso')),
                ('cookies_politic', tinymce.models.HTMLField(verbose_name='Termos de uso')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
