# Generated by Django 3.2.3 on 2021-06-25 21:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='cookies_politic',
        ),
        migrations.AlterField(
            model_name='config',
            name='privacy',
            field=tinymce.models.HTMLField(verbose_name='Política de Privacidade'),
        ),
    ]
