# Generated by Django 4.0.2 on 2022-08-08 16:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_config_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='terms_of_use_inspectors',
            field=tinymce.models.HTMLField(default='<p></p>', verbose_name='Termos de uso para fiscais'),
            preserve_default=False,
        ),
    ]
