# Generated by Django 3.2.4 on 2021-08-19 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import fiscallizeon.core.storage_backends
import fiscallizeon.diagramations.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0010_alter_subject_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0006_auto_20210126_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('exam_file', models.FileField(storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to=fiscallizeon.diagramations.models.material_file_directory_path, verbose_name='Arquivo da prova')),
                ('template_file', models.FileField(storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to=fiscallizeon.diagramations.models.material_file_directory_path, verbose_name='Arquivo de gabarito')),
                ('application_date', models.DateField(verbose_name='Data que a prova será aplicada aos alunos')),
                ('question_weight', models.TextField(blank=True, null=True, verbose_name='Descreva como será a distribuição das notas para essa prova')),
                ('orientations', models.TextField(blank=True, null=True, verbose_name='Descreva detalhes sobre a elaboração da prova e aplicação')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Criado'), (1, 'Elaborando'), (2, 'Finalizado')], default=0, verbose_name='Status da solicitação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('grades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.grade', verbose_name='Série que será aplicada este caderno')),
                ('subjects', models.ManyToManyField(to='subjects.Subject', verbose_name='Disciplinas do caderno de provas')),
            ],
            options={
                'verbose_name': 'Solicitação de diagramação',
                'verbose_name_plural': 'Solicitações de Diagramação',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
