# Generated by Django 3.2.4 on 2021-08-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagramations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagramationrequest',
            old_name='grades',
            new_name='grade',
        ),
    ]
