# Generated by Django 3.2.4 on 2021-08-21 20:43

from django.db import migrations, models
import fiscallizeon.core.storage_backends
import fiscallizeon.diagramations.models


class Migration(migrations.Migration):

    dependencies = [
        ('diagramations', '0002_rename_grades_diagramationrequest_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagramationrequest',
            name='exam_file',
            field=models.FileField(help_text='Envie o arquivos com as questẽos que serão diagramadas. Arquivo: .pdf, .doc ou .docx', storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to=fiscallizeon.diagramations.models.material_file_directory_path, verbose_name='Arquivo da prova'),
        ),
        migrations.AlterField(
            model_name='diagramationrequest',
            name='template_file',
            field=models.FileField(help_text='Você pode enviar o gabarito juntamente com a prova no campo anterior, se preferir.', storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to=fiscallizeon.diagramations.models.material_file_directory_path, verbose_name='Arquivo de gabarito'),
        ),
    ]
