# Generated by Django 3.2.4 on 2021-08-24 18:06

from django.db import migrations, models
import fiscallizeon.core.storage_backends
import fiscallizeon.diagramations.models


class Migration(migrations.Migration):

    dependencies = [
        ('diagramations', '0003_auto_20210821_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagramationrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Solicitado'), (1, 'Elaborando'), (2, 'Finalizado')], default=0, verbose_name='Status da solicitação'),
        ),
        migrations.AlterField(
            model_name='diagramationrequest',
            name='template_file',
            field=models.FileField(blank=True, help_text='Você pode enviar o gabarito juntamente com a prova no campo anterior, se preferir.', null=True, storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to=fiscallizeon.diagramations.models.material_file_directory_path, verbose_name='Arquivo de gabarito'),
        ),
    ]
