# Generated by Django 3.2.4 on 2021-09-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagramations', '0005_auto_20210826_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagramationrequest',
            options={'ordering': ('-application_date', 'created_at'), 'verbose_name': 'Solicitação de diagramação', 'verbose_name_plural': 'Solicitações de Diagramação'},
        ),
    ]
