# Generated by Django 4.0.2 on 2022-04-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagramations', '0007_alter_diagramationrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagramationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
