# Generated by Django 3.0.7 on 2020-10-29 19:27

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Título da prova')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Elaborando'), (1, 'Aberta'), (2, 'Fechada')], default=0, verbose_name='Status')),
                ('coordination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.SchoolCoordination', verbose_name='Coordenação')),
            ],
            options={
                'verbose_name': 'Prova',
                'verbose_name_plural': 'Provas',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
