# Generated by Django 3.0.7 on 2020-11-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='group_by_topic',
            field=models.BooleanField(default=True, verbose_name='Agrupar por tópico'),
        ),
        migrations.AddField(
            model_name='exam',
            name='random_alternatives',
            field=models.BooleanField(default=False, verbose_name='Randomizar alternativas?'),
        ),
        migrations.AddField(
            model_name='exam',
            name='random_questions',
            field=models.BooleanField(default=False, verbose_name='Randomizar questões?'),
        ),
    ]
