# Generated by Django 3.0.7 on 2021-01-12 17:57

from django.db import migrations, models

from fiscallizeon.exams.models import Exam

def migrate_coordinations(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20210212_1547'),
    ]

    operations = [
        migrations.RunPython(migrate_coordinations, reverse_code=migrations.RunPython.noop),
    ]
