# Generated by Django 3.0.7 on 2021-02-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_migration_coordinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='coordination',
        ),
    ]
