# Generated by Django 3.0.7 on 2021-02-16 18:16

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20210216_1402'),
        ('inspectors', '0003_auto_20210216_1402'),
        ('exams', '0008_auto_20210212_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Questão na prova',
                'verbose_name_plural': 'Questões na prova',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher_subjects',
            field=models.ManyToManyField(to='inspectors.TeacherSubject'),
        ),
        migrations.CreateModel(
            name='StatusQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Aprovada'), (1, 'Reprovada'), (2, 'Em aberta'), (3, 'Aguardando correção')], default=2, verbose_name='Situação')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.ExamQuestion', verbose_name='Questão na prova')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam', verbose_name='Prova'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question', verbose_name='Questão'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions_2',
            field=models.ManyToManyField(related_name='exams', through='exams.ExamQuestion', to='questions.Question', verbose_name='Questões'),
        ),
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together={('question', 'exam')},
        ),
    ]
