# Generated by Django 3.0.7 on 2021-01-12 17:57

from django.db import migrations, models

from fiscallizeon.exams.models import Exam


def migrate_questions(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20210216_1516'),
    ]

    operations = [
        migrations.RunPython(migrate_questions, reverse_code=migrations.RunPython.noop),
    ]
