# Generated by Django 3.0.7 on 2021-02-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_migrate_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
    ]
