# Generated by Django 3.0.7 on 2021-02-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_remove_exam_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='questions_2',
            new_name='questions',
        ),
    ]
