# Generated by Django 3.0.7 on 2021-02-17 20:38

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0003_auto_20210216_1402'),
        ('exams', '0012_auto_20210216_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='teacher_subjects',
        ),
        migrations.CreateModel(
            name='ExamTeacherSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantity', models.SmallIntegerField(verbose_name='Quantidade de questões')),
                ('note', models.TextField(verbose_name='Observações')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam')),
                ('teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectors.TeacherSubject')),
            ],
            options={
                'verbose_name': 'Professor na prova',
                'verbose_name_plural': 'Professores na prova',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
