# Generated by Django 3.0.7 on 2021-02-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0003_auto_20210216_1402'),
        ('exams', '0013_auto_20210217_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='teacher_subjects',
            field=models.ManyToManyField(through='exams.ExamTeacherSubject', to='inspectors.TeacherSubject', verbose_name='Professor/Disciplina'),
        ),
    ]
