# Generated by Django 3.0.7 on 2021-02-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_exam_teacher_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examteachersubject',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
