# Generated by Django 3.0.7 on 2021-02-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_auto_20210218_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='examteachersubject',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Quantidade de questões'),
            preserve_default=False,
        ),
    ]
