# Generated by Django 3.0.7 on 2021-02-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_examteachersubject_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examteachersubject',
            options={'ordering': ('order',), 'verbose_name': 'Professor na prova', 'verbose_name_plural': 'Professores na prova'},
        ),
        migrations.AlterField(
            model_name='examteachersubject',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Ordem na prova'),
        ),
    ]
