# Generated by Django 3.0.7 on 2021-02-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20210126_1340'),
        ('exams', '0017_auto_20210219_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='examteachersubject',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Grade'),
        ),
    ]
