# Generated by Django 3.0.7 on 2021-02-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_examteachersubject_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='exam_teacher_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.ExamTeacherSubject', verbose_name='Disciplina/Professor'),
        ),
    ]
