# Generated by Django 3.0.7 on 2021-02-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_examquestion_exam_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Ordem na prova'),
        ),
    ]
