# Generated by Django 3.0.7 on 2021-02-23 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0016_auto_20210216_1402'),
        ('exams', '0021_auto_20210221_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='statusquestion',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aprovada'), (1, 'Reprovada'), (2, 'Em aberto'), (3, 'Aguardando correção'), (4, 'Corrigido')], default=2, verbose_name='Situação'),
        ),
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together={('question', 'exam', 'exam_teacher_subject')},
        ),
    ]
