# Generated by Django 3.0.7 on 2021-03-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_auto_20210223_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusquestion',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Está ativo'),
        ),
    ]
