# Generated by Django 3.0.7 on 2021-03-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0023_statusquestion_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('-created_at',), 'verbose_name': 'Prova', 'verbose_name_plural': 'Provas'},
        ),
    ]
