# Generated by Django 3.0.7 on 2021-03-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_auto_20210311_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examteachersubject',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='statusquestion',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
    ]
