# Generated by Django 3.0.7 on 2021-03-15 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0007_auto_20210225_1945'),
        ('questions', '0016_auto_20210216_1402'),
        ('exams', '0025_auto_20210312_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.Exam', verbose_name='Prova'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='exam_teacher_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exams.ExamTeacherSubject', verbose_name='Disciplina/Professor'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Question', verbose_name='Questão'),
        ),
        migrations.AlterField(
            model_name='examteachersubject',
            name='teacher_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspectors.TeacherSubject'),
        ),
    ]
