# Generated by Django 3.0.7 on 2021-03-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0026_auto_20210315_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='group_by_topic',
            field=models.BooleanField(default=False, verbose_name='Randomizar disciplinas?'),
        ),
    ]
