# Generated by Django 3.0.7 on 2021-04-02 19:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0028_auto_20210325_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=4, verbose_name='Nota da questão na prova'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Elaborando'), (1, 'Aberta'), (2, 'Fechada'), (3, 'Enviada para revisão')], default=0, verbose_name='Situação da prova'),
        ),
    ]
