# Generated by Django 3.0.7 on 2021-04-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0029_auto_20210402_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='examteachersubject',
            name='teacher_note',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Anotações do professor'),
        ),
    ]
