# Generated by Django 3.0.7 on 2021-04-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0029_auto_20210402_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='correction_by_subject',
            field=models.BooleanField(default=False, verbose_name='Correção pelos professores da disciplina'),
        ),
    ]
