# Generated by Django 3.0.7 on 2021-04-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0030_examteachersubject_teacher_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusquestion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='examteachersubject',
            name='teacher_note',
            field=models.TextField(blank=True, default='', help_text='Digite aqui alguma informação importante para sua coordenação', null=True, verbose_name='Anotações do professor'),
        ),
    ]
