# Generated by Django 3.0.7 on 2021-04-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0030_exam_correction_by_subject'),
        ('exams', '0031_auto_20210409_1605'),
    ]

    operations = [
    ]
