# Generated by Django 3.0.7 on 2021-04-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0032_merge_20210412_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='correction_by_subject',
            field=models.BooleanField(default=False, verbose_name='Permitir correção/visualização por professores da mesma disciplina'),
        ),
    ]
