# Generated by Django 3.0.7 on 2021-04-30 17:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0033_auto_20210416_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=5, verbose_name='Nota da questão na prova'),
        ),
    ]
