# Generated by Django 3.0.7 on 2021-04-30 19:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0034_auto_20210430_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=6, verbose_name='Nota da questão na prova'),
        ),
    ]
