# Generated by Django 3.2.3 on 2021-06-04 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0035_auto_20210430_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='source_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_copies', to='exams.exam'),
        ),
    ]
