# Generated by Django 3.2.3 on 2021-06-04 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0036_exam_source_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='Prova'),
        ),
    ]
