# Generated by Django 3.2.3 on 2021-06-04 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0037_alter_examquestion_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='exam_teacher_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.examteachersubject', verbose_name='Disciplina/Professor'),
        ),
    ]
