# Generated by Django 3.2.3 on 2021-07-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0038_alter_examquestion_exam_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='elaboration_deadline',
            field=models.DateField(null=True, verbose_name='Prazo para elaboração'),
        ),
    ]
