# Generated by Django 3.2.3 on 2021-08-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0039_exam_elaboration_deadline'),
        ('exams', '0039_historicalexam'),
    ]

    operations = [
    ]
