# Generated by Django 3.2.3 on 2021-08-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0040_merge_20210808_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusquestion',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aprovada'), (1, 'Reprovada'), (2, 'Em aberto'), (3, 'Aguardando correção'), (4, 'Corrigido'), (5, 'Visto')], default=2, verbose_name='Situação'),
        ),
    ]
