# Generated by Django 3.2.4 on 2021-08-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0041_alter_statusquestion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Elaborando'), (1, 'Em análise'), (2, 'Fechada'), (3, 'Revisão Gráfica')], default=0, verbose_name='Situação da prova'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Elaborando'), (1, 'Em análise'), (2, 'Fechada'), (3, 'Revisão Gráfica')], default=0, verbose_name='Situação da prova'),
        ),
    ]
