# Generated by Django 3.2.4 on 2021-10-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0042_auto_20210820_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_english_spanish',
            field=models.BooleanField(default=False, help_text='Marque esta opção se esta prova inicia com 5 questões de ingês e 5 de espanhol', verbose_name='Tem língua estrangeira'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='is_english_spanish',
            field=models.BooleanField(default=False, help_text='Marque esta opção se esta prova inicia com 5 questões de ingês e 5 de espanhol', verbose_name='Tem língua estrangeira'),
        ),
    ]
