# Generated by Django 3.2.4 on 2021-11-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0045_examheader_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examheader',
            options={'ordering': ('-main_header', '-created_at')},
        ),
        migrations.AddField(
            model_name='examheader',
            name='name',
            field=models.CharField(default='Cabeçalho', max_length=100, verbose_name='Nome do cabeçalho'),
        ),
    ]
