# Generated by Django 3.2.4 on 2021-11-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0046_auto_20211101_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examheader',
            name='created_by',
        ),
    ]
