# Generated by Django 3.2.4 on 2021-12-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0047_remove_examheader_created_by'),
    ]

    operations = [
      #  migrations.AddField(
        #    model_name='exam',
       #     name='is_abstract',
      #      field=models.BooleanField(default=False, verbose_name='O exame é apenas para gabarito? '),
      #  ),
       # migrations.AddField(
       #     model_name='historicalexam',
       #     name='is_abstract',
      #      field=models.BooleanField(default=False, verbose_name='O exame é apenas para gabarito? '),
       # ),
    ]
