# Generated by Django 3.2.4 on 2021-11-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0047_remove_examheader_created_by'),
    ]

    operations = [
        
    ]
