# Generated by Django 3.2.4 on 2021-12-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0048_examquestion_is_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='A prova é abstrata, usada apenas na geração de gabarito avulso'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='A prova é abstrata, usada apenas na geração de gabarito avulso'),
        ),
    ]
