# Generated by Django 3.2.4 on 2021-12-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0049_auto_20211218_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='base_text_location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Textos base por disciplina'), (1, 'Textos base no início da prova')], default=0, verbose_name='Situação da prova'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='base_text_location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Textos base por disciplina'), (1, 'Textos base no início da prova')], default=0, verbose_name='Situação da prova'),
        ),
    ]
