# Generated by Django 3.2.4 on 2021-12-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0048_auto_20211127_1241'),
        ('exams', '0050_auto_20211218_1146'),
    ]

    operations = [
    ]
