# Generated by Django 3.2.4 on 2021-12-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0049_auto_20211228_1936'),
        ('exams', '0051_merge_0048_auto_20211127_1241_0050_auto_20211218_1146'),
    ]

    operations = [
    ]
