# Generated by Django 3.2.4 on 2022-01-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0048_auto_20211213_1441'),
        ('exams', '0048_auto_20211219_1431'),
        ('exams', '0052_auto_20211229_1726'),
    ]

    operations = [
    ]
