# Generated by Django 3.2.4 on 2021-12-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0052_merge_20211229_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Prova'), (1, 'Atividade de Casa')], default=0, verbose_name='Categoria do caderno'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Prova'), (1, 'Atividade de Casa')], default=0, verbose_name='Categoria do caderno'),
        ),
    ]
