# Generated by Django 3.2.4 on 2022-01-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0053_auto_20211229_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Prova'), (1, 'Atividade de Casa')], default=0, verbose_name='Tipo do caderno'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Prova'), (1, 'Atividade de Casa')], default=0, verbose_name='Tipo do caderno'),
        ),
    ]
