# Generated by Django 3.2.4 on 2022-01-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_alter_client_has_exam_elaboration'),
        ('exams', '0054_auto_20220104_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('-created_at',), 'verbose_name': 'Caderno', 'verbose_name_plural': 'Cadernos'},
        ),
        migrations.AlterModelOptions(
            name='historicalexam',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Caderno'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='base_text_location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Textos base por disciplina'), (1, 'Textos base no início do caderno')], default=0, verbose_name='Situação do caderno'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='coordinations',
            field=models.ManyToManyField(related_name='exams', to='clients.SchoolCoordination', verbose_name='Coordenações autorizadas a acessar este caderno'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='É abstrato'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_english_spanish',
            field=models.BooleanField(default=False, help_text='Marque esta opção se este caderno inicia com 5 questões de ingês e 5 de espanhol', verbose_name='Tem língua estrangeira'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Título do caderno'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Elaborando'), (1, 'Em análise'), (2, 'Fechada'), (3, 'Revisão Gráfica')], default=0, verbose_name='Situação do caderno'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='base_text_location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Textos base por disciplina'), (1, 'Textos base no início do caderno')], default=0, verbose_name='Situação do caderno'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='É abstrato'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='is_english_spanish',
            field=models.BooleanField(default=False, help_text='Marque esta opção se este caderno inicia com 5 questões de ingês e 5 de espanhol', verbose_name='Tem língua estrangeira'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Elaborando'), (1, 'Em análise'), (2, 'Fechada'), (3, 'Revisão Gráfica')], default=0, verbose_name='Situação do caderno'),
        ),
    ]
