# Generated by Django 3.2.4 on 2022-01-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0053_merge_20220106_1835'),
        ('exams', '0055_auto_20220104_1728'),
    ]

    operations = [
    ]
