# Generated by Django 3.2.4 on 2022-01-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0056_merge_20220106_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='base_text_location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Textos base por disciplina'), (1, 'Textos base no início do caderno')], default=0, verbose_name='Situação da prova'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='É abstrato'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='base_text_location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Textos base por disciplina'), (1, 'Textos base no início do caderno')], default=0, verbose_name='Situação da prova'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='É abstrato'),
        ),
    ]
