# Generated by Django 3.2.4 on 2022-02-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0058_auto_20220117_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_english_spanish',
            field=models.BooleanField(default=False, verbose_name='Caderno com língua estrangeira'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='is_english_spanish',
            field=models.BooleanField(default=False, verbose_name='Caderno com língua estrangeira'),
        ),
    ]
