# Generated by Django 3.2.4 on 2022-02-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0059_auto_20220203_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_english_spanish',
            field=models.BooleanField(default=False, help_text='Ative esta opção se deseja que o aluno selecione uma língua estrangeira para realizar a prova', verbose_name='Caderno com língua estrangeira'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='is_english_spanish',
            field=models.BooleanField(default=False, help_text='Ative esta opção se deseja que o aluno selecione uma língua estrangeira para realizar a prova', verbose_name='Caderno com língua estrangeira'),
        ),
    ]
