# Generated by Django 3.2.4 on 2022-02-02 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0060_alter_wrong_exam_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrong',
            name='exam_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examquestion', verbose_name='Questão no Exame'),
        ),
    ]
