# Generated by Django 3.2.4 on 2022-02-02 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0061_alter_wrong_exam_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrong',
            name='exam_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrongs', to='exams.examquestion', verbose_name='Questão no Exame'),
        ),
        migrations.AlterField(
            model_name='wrong',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Resposta ao aluno'),
        ),
        migrations.AlterField(
            model_name='wrong',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aguardando revisão'), (1, 'Aceito'), (2, 'Recusado'), (3, 'Reaberto')], default=0, verbose_name='Situação'),
        ),
    ]
