# Generated by Django 3.2.4 on 2022-02-03 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_options'),
        ('exams', '0062_auto_20220202_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrong',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrongs', to='students.student', verbose_name='Aluno'),
        ),
    ]
