# Generated by Django 3.2.4 on 2022-02-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0063_alter_wrong_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrong',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aguardando revisão'), (1, 'Aceita'), (2, 'Recusada'), (3, 'Reaberta')], default=0, verbose_name='Situação'),
        ),
    ]
