# Generated by Django 3.2.4 on 2022-02-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0065_merge_0060_auto_20220208_1755_0064_alter_wrong_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='release_elaboration_teacher',
            field=models.DateField(null=True, verbose_name='Liberação para elaboração do professor'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='release_elaboration_teacher',
            field=models.DateField(null=True, verbose_name='Liberação para elaboração do professor'),
        ),
    ]
