# Generated by Django 4.0.2 on 2022-03-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0066_auto_20220214_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='base_text_location',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Textos base por questão'), (0, 'Textos base por disciplina'), (1, 'Textos base no início do caderno'), (2, 'Textos base no final do caderno')], default=3, verbose_name='Situação da prova'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='base_text_location',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Textos base por questão'), (0, 'Textos base por disciplina'), (1, 'Textos base no início do caderno'), (2, 'Textos base no final do caderno')], default=3, verbose_name='Situação da prova'),
        ),
    ]
