# Generated by Django 4.0.2 on 2022-03-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0067_exam_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='materials',
        ),
    ]
