# Generated by Django 4.0.2 on 2022-03-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0067_alter_exam_base_text_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='base_text_location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Textos base por questão'), (1, 'Textos base por disciplina'), (2, 'Textos base no início do caderno'), (3, 'Textos base no final do caderno')], default=0, verbose_name='Situação da prova'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='base_text_location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Textos base por questão'), (1, 'Textos base por disciplina'), (2, 'Textos base no início do caderno'), (3, 'Textos base no final do caderno')], default=0, verbose_name='Situação da prova'),
        ),
    ]
