# Generated by Django 4.0.2 on 2022-03-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0068_alter_exam_base_text_location_and_more'),
        ('exams', '0068_remove_exam_materials'),
    ]

    operations = [
    ]
