# Generated by Django 4.0.2 on 2022-03-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0068_alter_exam_base_text_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examteachersubject',
            name='subject_note',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Nota da disciplina'),
        ),
    ]
