# Generated by Django 4.0.2 on 2022-03-18 14:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0068_alter_exam_base_text_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='weight',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=9, verbose_name='Nota da questão na prova'),
        ),
    ]
