# Generated by Django 4.0.2 on 2022-03-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0069_alter_examquestion_weight'),
        ('exams', '0069_exam_created_by_historicalexam_created_by'),
        ('exams', '0069_examteachersubject_subject_note'),
    ]

    operations = [
    ]
