# Generated by Django 4.0.2 on 2022-03-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0069_alter_examquestion_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='aggrupate_answer',
            field=models.BooleanField(default=False, verbose_name='Agrupar respostas?'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='aggrupate_answer',
            field=models.BooleanField(default=False, verbose_name='Agrupar respostas?'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='O exame é apenas para gabarito? '),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='O exame é apenas para gabarito? '),
        ),
    ]
