# Generated by Django 4.0.2 on 2022-03-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0069_alter_examquestion_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='O exame é apenas para gabarito? '),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_english_spanish',
            field=models.BooleanField(default=False, help_text='Marque esta opção se este caderno inicia com 5 questões de ingês e 5 de espanhol', verbose_name='Tem língua estrangeira'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='O exame é apenas para gabarito? '),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='is_english_spanish',
            field=models.BooleanField(default=False, help_text='Marque esta opção se este caderno inicia com 5 questões de ingês e 5 de espanhol', verbose_name='Tem língua estrangeira'),
        ),
    ]
