# Generated by Django 4.0.2 on 2022-03-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0070_exam_aggrupate_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='aggrupate_answer',
            new_name='aggrupate_answers',
        ),
        migrations.RenameField(
            model_name='historicalexam',
            old_name='aggrupate_answer',
            new_name='aggrupate_answers',
        ),
    ]
