# Generated by Django 4.0.2 on 2022-03-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0071_rename_aggrupate_answer_exam_aggrupate_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='aggrupate_answers',
        ),
        migrations.RemoveField(
            model_name='historicalexam',
            name='aggrupate_answers',
        ),
        migrations.AddField(
            model_name='exam',
            name='group_attachments',
            field=models.BooleanField(default=False, verbose_name='Agrupar Anexos?'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='group_attachments',
            field=models.BooleanField(default=False, verbose_name='Agrupar Anexos?'),
        ),
    ]
