# Generated by Django 4.0.2 on 2022-03-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0071_alter_exam_base_text_location_alter_exam_is_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examteachersubject',
            name='subject_note',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Nota da disciplina'),
        ),
    ]
