# Generated by Django 4.0.2 on 2022-04-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0069_merge_20220312_1022'),
        ('exams', '0072_alter_examteachersubject_subject_note'),
    ]

    operations = [
    ]
