# Generated by Django 4.0.2 on 2022-04-05 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0072_remove_exam_aggrupate_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='start_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Qual número irá iniciar esta prova?'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='start_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Qual número irá iniciar esta prova?'),
        ),
    ]
