# Generated by Django 4.0.2 on 2022-04-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0073_exam_start_number_historicalexam_start_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='group_attachments',
            field=models.BooleanField(default=False, help_text='Ative esta opção se deseja que os alunos envie as respostas de anexo agrupadas ao final de cada disciplina.', verbose_name='Agrupar Anexos?'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='group_attachments',
            field=models.BooleanField(default=False, help_text='Ative esta opção se deseja que os alunos envie as respostas de anexo agrupadas ao final de cada disciplina.', verbose_name='Agrupar Anexos?'),
        ),
    ]
