# Generated by Django 4.0.2 on 2022-04-05 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0074_alter_exam_group_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='start_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Qual número irá iniciar este caderno?'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='start_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Qual número irá iniciar este caderno?'),
        ),
    ]
