# Generated by Django 4.0.2 on 2022-04-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0073_merge_20220405_1528'),
        ('exams', '0075_alter_exam_start_number_and_more'),
    ]

    operations = [
    ]
