# Generated by Django 4.0.4 on 2022-04-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0077_alter_exam_group_attachments_alter_exam_is_abstract_and_more'),
        ('exams', '0079_alter_exam_id_alter_examheader_id_and_more'),
    ]

    operations = [
    ]
