# Generated by Django 4.0.2 on 2022-04-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0070_alter_exam_is_abstract_alter_exam_is_english_spanish_and_more'),
        ('exams', '0081_alter_exam_id_alter_examheader_id_and_more'),
    ]

    operations = [
    ]
