# Generated by Django 4.0.2 on 2022-05-04 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0082_merge_20220428_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='base_text_location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Textos base por questão'), (1, 'Textos base por disciplina'), (2, 'Textos base no início do caderno'), (3, 'Textos base no final do caderno')], default=0, verbose_name='Situação da prova'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='O caderno é abstrato, usada apenas na geração de gabarito avulso'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_english_spanish',
            field=models.BooleanField(default=False, help_text='Ative esta opção se deseja que o aluno selecione uma língua estrangeira para realizar a prova', verbose_name='Caderno com língua estrangeira'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='source_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_copies', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='base_text_location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Textos base por questão'), (1, 'Textos base por disciplina'), (2, 'Textos base no início do caderno'), (3, 'Textos base no final do caderno')], default=0, verbose_name='Situação da prova'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='O caderno é abstrato, usada apenas na geração de gabarito avulso'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='is_english_spanish',
            field=models.BooleanField(default=False, help_text='Ative esta opção se deseja que o aluno selecione uma língua estrangeira para realizar a prova', verbose_name='Caderno com língua estrangeira'),
        ),
    ]
