# Generated by Django 4.0.2 on 2022-05-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0083_alter_exam_base_text_location_alter_exam_is_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='show_ranking',
            field=models.BooleanField(default=False, help_text='Ativa esta opção se deseja que os alunos vejam sua posição na prova.', verbose_name='mostrar ranking'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='show_ranking',
            field=models.BooleanField(default=False, help_text='Ativa esta opção se deseja que os alunos vejam sua posição na prova.', verbose_name='mostrar ranking'),
        ),
    ]
