# Generated by Django 4.0.2 on 2022-07-30 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0045_examprintconfig'),
        ('exams', '0084_exam_show_ranking_historicalexam_show_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_print_config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='clients.examprintconfig', verbose_name='configuração de impressão'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='exam_print_config',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.examprintconfig', verbose_name='configuração de impressão'),
        ),
    ]
