# Generated by Django 4.0.2 on 2022-08-04 19:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0085_exam_exam_print_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='weight',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=10, verbose_name='Nota da questão na prova'),
        ),
        migrations.AlterField(
            model_name='examteachersubject',
            name='subject_note',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Nota da disciplina'),
        ),
        migrations.AlterField(
            model_name='historicalexamquestion',
            name='weight',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=10, verbose_name='Nota da questão na prova'),
        ),
    ]
