# Generated by Django 4.0.2 on 2022-08-04 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0085_exam_exam_print_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='orientations',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Orientações para a prova'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='orientations',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Orientações para a prova'),
        ),
        migrations.CreateModel(
            name='ExamOrientation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(default='Orientações Padrão', max_length=100, verbose_name='Título')),
                ('content', tinymce.models.HTMLField()),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
