# Generated by Django 4.0.2 on 2022-08-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0086_exam_orientations_historicalexam_orientations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusquestion',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aprovada'), (1, 'Reprovada'), (2, 'Em aberto'), (3, 'Aguardando correção'), (4, 'Corrigido'), (5, 'Visto'), (6, 'Anulada')], default=2, verbose_name='Situação'),
        ),
    ]
