# Generated by Django 4.0.2 on 2022-08-10 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0086_alter_examquestion_weight_and_more'),
        ('exams', '0087_alter_statusquestion_status'),
    ]

    operations = [
    ]
