# Generated by Django 4.0.2 on 2022-08-11 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0050_alter_examprintconfig_client'),
        ('exams', '0088_merge_20220810_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_print_config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='clients.examprintconfig', verbose_name='configuração de impressão'),
        ),
    ]
