# Generated by Django 4.0.6 on 2022-08-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0089_alter_exam_exam_print_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='examteachersubject',
            name='is_foreign_language',
            field=models.BooleanField(default=False, verbose_name='É língua estrangeira'),
        ),
    ]
