# Generated by Django 4.0.6 on 2022-08-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0090_examteachersubject_is_foreign_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='is_foreign_language',
            field=models.BooleanField(default=False, verbose_name='É língua estrangeira'),
        ),
        migrations.AddField(
            model_name='historicalexamquestion',
            name='is_foreign_language',
            field=models.BooleanField(default=False, verbose_name='É língua estrangeira'),
        ),
    ]
