# Generated by Django 4.0.2 on 2022-08-24 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0092_exam_update_foreign_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='foreign_language_start_examteachersubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_foreign_language', to='exams.examteachersubject', verbose_name='Teacher Subject que inicia a lingua estrangeira'),
        ),
        migrations.AddField(
            model_name='exam',
            name='foreign_language_start_index',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Index que inicia a lingua estrangeira'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='foreign_language_start_examteachersubject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='exams.examteachersubject', verbose_name='Teacher Subject que inicia a lingua estrangeira'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='foreign_language_start_index',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Index que inicia a lingua estrangeira'),
        ),
    ]
