# Generated by Django 4.0.2 on 2022-08-25 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0093_exam_foreign_language_start_examteachersubject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalexam',
            old_name='foreign_language_start_examteachersubject',
            new_name='where_is_espanhol_subject',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='foreign_language_start_examteachersubject',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='foreign_language_start_index',
        ),
        migrations.RemoveField(
            model_name='historicalexam',
            name='foreign_language_start_index',
        ),
        migrations.AddField(
            model_name='exam',
            name='where_is_english_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams_english_teacher', to='exams.examteachersubject', verbose_name=''),
        ),
        migrations.AddField(
            model_name='exam',
            name='where_is_espanhol_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams_espanhol_teacher', to='exams.examteachersubject', verbose_name='Teacher Subject que inicia a lingua estrangeira'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='where_is_english_subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='exams.examteachersubject', verbose_name=''),
        ),
    ]
