# Generated by Django 4.0.2 on 2022-08-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0094_rename_foreign_language_start_examteachersubject_historicalexam_where_is_espanhol_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='where_is_english_subject',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='where_is_espanhol_subject',
        ),
        migrations.RemoveField(
            model_name='historicalexam',
            name='where_is_english_subject',
        ),
        migrations.RemoveField(
            model_name='historicalexam',
            name='where_is_espanhol_subject',
        ),
    ]
