# Generated by Django 4.0.6 on 2022-09-06 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0024_inspector_can_annul'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0016_alter_course_created_at_alter_coursetype_created_at_and_more'),
        ('exams', '0095_remove_exam_where_is_english_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalExamTeacherSubject',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('quantity', models.SmallIntegerField(verbose_name='Quantidade de questões')),
                ('note', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Ordem na prova')),
                ('teacher_note', models.TextField(blank=True, default='', help_text='Digite aqui alguma informação importante para sua coordenação', null=True, verbose_name='Anotações do professor')),
                ('subject_note', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Nota da disciplina')),
                ('is_foreign_language', models.BooleanField(default=False, verbose_name='É língua estrangeira')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('exam', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='exams.exam')),
                ('grade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='classes.grade')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('teacher_subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inspectors.teachersubject')),
            ],
            options={
                'verbose_name': 'historical Professor na prova',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
