# Generated by Django 4.0.6 on 2022-10-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0096_historicalexamteachersubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='examteachersubject',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='Professor abstrato'),
        ),
        migrations.AddField(
            model_name='historicalexamteachersubject',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='Professor abstrato'),
        ),
    ]
