# Generated by Django 4.0.6 on 2022-10-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0098_remove_examteachersubject_is_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='automatic_creation',
            field=models.BooleanField(default=False, verbose_name='Lista gerada automaticamente'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='automatic_creation',
            field=models.BooleanField(default=False, verbose_name='Lista gerada automaticamente'),
        ),
    ]
