# Generated by Django 4.0.6 on 2022-10-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0099_exam_automatic_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Baixa'), (1, 'Média'), (2, 'Alta')], default=0, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Baixa'), (1, 'Média'), (2, 'Alta')], default=0, verbose_name='Prioridade'),
        ),
    ]
