# Generated by Django 4.0.6 on 2022-10-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0100_exam_priority_historicalexam_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='automatic_creation',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='historicalexam',
            name='automatic_creation',
        ),
        migrations.RemoveField(
            model_name='historicalexam',
            name='priority',
        ),
    ]
