# Generated by Django 4.0.6 on 2022-11-18 20:45

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import fiscallizeon.exams.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0101_remove_exam_automatic_creation_remove_exam_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTeacherSubjectFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('file', models.FileField(blank=True, null=True, upload_to=fiscallizeon.exams.models.directory_path_file, verbose_name='arquivo')),
                ('exam_teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examteachersubject', verbose_name='professor na prova')),
            ],
            options={
                'verbose_name': 'arquivo do professor na prova',
                'verbose_name_plural': 'arquivos dos professores nas provas',
                'ordering': ('-created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
