# Generated by Django 4.0.6 on 2022-11-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0102_exam_level_historicalexam_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='level',
            new_name='stage',
        ),
        migrations.RenameField(
            model_name='historicalexam',
            old_name='level',
            new_name='stage',
        ),
    ]
