# Generated by Django 4.0.6 on 2022-11-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0103_rename_level_exam_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='stage',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Ensino Fundamental 1'), (1, 'Ensino Fundamental 2'), (2, 'Ensino Médio')], null=True, verbose_name='Etapa do Ensino'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='stage',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Ensino Fundamental 1'), (1, 'Ensino Fundamental 2'), (2, 'Ensino Médio')], null=True, verbose_name='Etapa do Ensino'),
        ),
    ]
