# Generated by Django 4.0.6 on 2022-11-22 18:56

from django.db import migrations

def set_elaboration_email_sent_true(apps, scheme_editor):
    ExamTeacherSubject = apps.get_model('exams', 'ExamTeacherSubject')
    ExamTeacherSubject.objects.update(elaboration_email_sent=True)
    
class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0105_examteachersubject_elaboration_email_sent_and_more'),
    ]

    operations = [
        migrations.RunPython(set_elaboration_email_sent_true, reverse_code=migrations.RunPython.noop)
    ]
