# Generated by Django 4.0.6 on 2022-11-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0106_set_elaboration_exam_sent_in_examteachersuject_true'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='historicalexam',
            name='stage',
        ),
    ]
