# Generated by Django 4.0.6 on 2022-11-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0102_examteachersubjectfile'),
        ('exams', '0107_remove_exam_stage_remove_historicalexam_stage'),
    ]

    operations = [
    ]
