# Generated by Django 4.0.6 on 2022-11-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0109_examteachersubject_block_questions_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examteachersubject',
            name='block_quantity_limit',
            field=models.BooleanField(default=False, help_text='Ao ativar essa opção você limitará a quantidade de questões que podem ser inseridas por este professor', verbose_name='Limitar a quantidade de questão inseridas'),
        ),
        migrations.AddField(
            model_name='historicalexamteachersubject',
            name='block_quantity_limit',
            field=models.BooleanField(default=False, help_text='Ao ativar essa opção você limitará a quantidade de questões que podem ser inseridas por este professor', verbose_name='Limitar a quantidade de questão inseridas'),
        ),
    ]
