# Generated by Django 4.0.6 on 2022-12-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0066_teachingstage_educationsystem'),
        ('exams', '0110_examteachersubject_block_quantity_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='education_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.educationsystem', verbose_name='Sistema de ensino'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teaching_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.teachingstage', verbose_name='Etapa do ensino'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='education_system',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.educationsystem', verbose_name='Sistema de ensino'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='teaching_stage',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.teachingstage', verbose_name='Etapa do ensino'),
        ),
    ]
