# Generated by Django 4.0.6 on 2022-12-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0111_exam_education_system_exam_teaching_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='Já foi impresso'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='Já foi impresso'),
        ),
    ]
