# Generated by Django 4.0.6 on 2022-12-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0112_exam_is_printed_historicalexam_is_printed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examteachersubject',
            name='block_questions_quantity',
            field=models.BooleanField(default=False, verbose_name='Definir quantidade de questões objetivas/discursivas'),
        ),
        migrations.AlterField(
            model_name='historicalexamteachersubject',
            name='block_questions_quantity',
            field=models.BooleanField(default=False, verbose_name='Definir quantidade de questões objetivas/discursivas'),
        ),
    ]
