# Generated by Django 4.0.6 on 2023-01-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0109_examquestion_short_code_and_more'),
        ('exams', '0113_alter_examteachersubject_block_questions_quantity_and_more'),
    ]

    operations = [
    ]
