# Generated by Django 4.0.6 on 2023-03-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0114_merge_20230102_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='id_erp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='código de exportação'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='id_erp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='código de exportação'),
        ),
    ]
