# Generated by Django 4.0.6 on 2023-04-05 17:51

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0090_alter_questiontag_options'),
        ('exams', '0115_exam_id_erp_historicalexam_id_erp'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTagStatusQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.statusquestion', verbose_name='Situação da questão')),
                ('tags', models.ManyToManyField(to='clients.questiontag', verbose_name='Tags da questão')),
            ],
            options={
                'verbose_name': 'Tags em status de questão',
                'verbose_name_plural': 'Tags em status de questões',
                'ordering': ['-created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
