# Generated by Django 4.0.6 on 2023-04-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0115_exam_id_erp_historicalexam_id_erp'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_grade',
            field=models.PositiveIntegerField(blank=True, help_text='Você pode deixar essa valor em branco caso deseje escolher as notas de acordo com os professores inseridos no caderno', null=True, verbose_name='Nota desse caderno?'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='total_grade',
            field=models.PositiveIntegerField(blank=True, help_text='Você pode deixar essa valor em branco caso deseje escolher as notas de acordo com os professores inseridos no caderno', null=True, verbose_name='Nota desse caderno?'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Elaborando'), (1, 'Em análise'), (2, 'Fechada'), (3, 'Revisão Gráfica'), (4, 'Revisão de texto')], default=0, verbose_name='Situação do caderno'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Elaborando'), (1, 'Em análise'), (2, 'Fechada'), (3, 'Revisão Gráfica'), (4, 'Revisão de texto')], default=0, verbose_name='Situação do caderno'),
        ),
    ]
