# Generated by Django 4.0.6 on 2023-04-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0092_remove_questiontag_is_question_correction_tag_and_more'),
        ('exams', '0116_questiontagstatusquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontagstatusquestion',
            name='tags',
            field=models.ManyToManyField(blank=True, to='clients.questiontag', verbose_name='Tags da questão'),
        ),
    ]
