# Generated by Django 4.0.6 on 2023-04-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0116_exam_total_grade_historicalexam_total_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_grade',
            field=models.PositiveIntegerField(blank=True, help_text='Você pode deixar essa valor em branco caso deseje escolher as notas de acordo com os professores inseridos no caderno', null=True, verbose_name='Nota geral do caderno'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='total_grade',
            field=models.PositiveIntegerField(blank=True, help_text='Você pode deixar essa valor em branco caso deseje escolher as notas de acordo com os professores inseridos no caderno', null=True, verbose_name='Nota geral do caderno'),
        ),
    ]
