# Generated by Django 4.0.6 on 2023-04-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0116_clientcustompage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcustompage',
            name='name',
            field=models.CharField(default='Página customizada', max_length=255, verbose_name='Nome da página'),
        ),
    ]
