# Generated by Django 4.0.6 on 2023-04-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0117_clientcustompage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustompage',
            name='location',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Antes do caderno do aluno'), (1, 'Antes da lista de presença'), (2, 'Antes da folha de respostas objetivas'), (3, 'Antes da folha de respostas discursivas')], default=0, verbose_name='Local'),
        ),
    ]
