# Generated by Django 4.0.6 on 2023-04-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0116_questiontagstatusquestion'),
        ('exams', '0117_alter_exam_total_grade_and_more'),
    ]

    operations = [
    ]
