# Generated by Django 4.0.6 on 2023-04-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0117_alter_questiontagstatusquestion_tags'),
        ('exams', '0118_merge_20230413_1406'),
    ]

    operations = [
    ]
