# Generated by Django 4.0.6 on 2023-05-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0119_alter_clientcustompage_location'),
        ('exams', '0119_merge_20230418_1635'),
    ]

    operations = [
    ]
