# Generated by Django 4.0.6 on 2023-05-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0118_examquestion_block_weight_and_more'),
        ('exams', '0119_merge_20230418_1635'),
    ]

    operations = [
    ]
