# Generated by Django 4.0.6 on 2023-05-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0120_merge_20230503_0904'),
        ('exams', '0120_merge_20230510_1334'),
    ]

    operations = [
    ]
