# Generated by Django 4.0.6 on 2023-06-01 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0120_merge_20230503_0904'),
        ('exams', '0120_merge_20230523_1823'),
    ]

    operations = [
    ]
