# Generated by Django 4.0.6 on 2023-05-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0120_merge_20230523_1823'),
        ('exams', '0121_merge_20230518_1851'),
    ]

    operations = [
    ]
