# Generated by Django 4.0.6 on 2023-06-01 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0121_merge_20230601_2014'),
        ('exams', '0122_merge_20230523_1905'),
    ]

    operations = [
    ]
