# Generated by Django 4.0.6 on 2023-06-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0123_merge_20230601_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='related_subjects',
            field=models.BooleanField(default=False, verbose_name='Relacionar disciplinas'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='related_subjects',
            field=models.BooleanField(default=False, verbose_name='Relacionar disciplinas'),
        ),
    ]
