# Generated by Django 4.0.6 on 2023-06-16 15:33

from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0124_alter_examteachersubject_discursive_quantity_and_more'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE;'),
        migrations.AlterField(
            model_name='examteachersubject',
            name='discursive_quantity',
            field=models.IntegerField(default=0, help_text='Quantidade de questões discursivas que poderão ser adicionada ao caderno', verbose_name='Discursivas'),
        ),
        migrations.AlterField(
            model_name='examteachersubject',
            name='objective_quantity',
            field=models.IntegerField(default=0, help_text='Quantidade de questões objetivas que poderão ser adicionada ao caderno', verbose_name='Objetivas'),
        ),
        migrations.AlterField(
            model_name='historicalexamteachersubject',
            name='discursive_quantity',
            field=models.IntegerField(default=0, help_text='Quantidade de questões discursivas que poderão ser adicionada ao caderno', verbose_name='Discursivas'),
        ),
        migrations.AlterField(
            model_name='historicalexamteachersubject',
            name='objective_quantity',
            field=models.IntegerField(default=0, help_text='Quantidade de questões objetivas que poderão ser adicionada ao caderno', verbose_name='Objetivas'),
        ),
        migrations.RunSQL('SET CONSTRAINTS ALL DEFERRED;'),
    ]
