# Generated by Django 4.0.6 on 2023-07-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0125_alter_examteachersubject_discursive_quantity_and_more'),
        ('exams', '0125_exam_relations'),
    ]

    operations = [
    ]
