# Generated by Django 4.0.6 on 2023-07-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0126_merge_20230623_1537'),
        ('exams', '0126_merge_20230711_1007'),
    ]

    operations = [
    ]
