# Generated by Django 4.0.6 on 2023-07-24 20:30

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0126_merge_20230711_1007'),
    ]

    operations = [
        UnaccentExtension()
    ]
