# Generated by Django 4.0.6 on 2023-07-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0126_merge_20230711_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusquestion',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aprovada'), (1, 'Reprovada'), (2, 'Em aberto'), (3, 'Aguardando correção'), (4, 'Corrigido'), (5, 'Visto'), (6, 'Anulada'), (7, 'Usar depois')], default=2, verbose_name='Situação'),
        ),
    ]
