# Generated by Django 4.0.6 on 2023-07-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0127_alter_statusquestion_status'),
        ('exams', '0127_merge_20230711_1658'),
    ]

    operations = [
    ]
