# Generated by Django 4.0.6 on 2023-08-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0127_auto_20230724_1730'),
        ('exams', '0128_alter_examquestion_unique_together_and_more'),
    ]

    operations = [
    ]
