# Generated by Django 4.0.6 on 2023-08-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0128_merge_20230726_1717'),
        ('exams', '0129_merge_20230816_0935'),
    ]

    operations = [
    ]
