# Generated by Django 4.0.6 on 2023-08-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0130_merge_20230821_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Prova'), (1, 'Lista de Exercício')], default=0, verbose_name='Tipo do caderno'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Prova'), (1, 'Lista de Exercício')], default=0, verbose_name='Tipo do caderno'),
        ),
    ]
