# Generated by Django 4.0.6 on 2023-10-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0132_exam_is_enem_simulator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Prova'), (1, 'Lista de Exercício')], default=0, verbose_name='Tipo da avaliação'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='group_by_topic',
            field=models.BooleanField(default=False, verbose_name='Embaralhar disciplinas?'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Título da avaliação'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='random_alternatives',
            field=models.BooleanField(default=False, verbose_name='Embaralhar alternativas?'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='random_questions',
            field=models.BooleanField(default=False, verbose_name='Embaralhar questões?'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='show_ranking',
            field=models.BooleanField(default=False, help_text='Ativa esta opção se deseja que os alunos vejam sua posição na prova.', verbose_name='mostrar colocação do aluno na avaliação'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Prova'), (1, 'Lista de Exercício')], default=0, verbose_name='Tipo da avaliação'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='group_by_topic',
            field=models.BooleanField(default=False, verbose_name='Embaralhar disciplinas?'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Título da avaliação'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='random_alternatives',
            field=models.BooleanField(default=False, verbose_name='Embaralhar alternativas?'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='random_questions',
            field=models.BooleanField(default=False, verbose_name='Embaralhar questões?'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='show_ranking',
            field=models.BooleanField(default=False, help_text='Ativa esta opção se deseja que os alunos vejam sua posição na prova.', verbose_name='mostrar colocação do aluno na avaliação'),
        ),
    ]
