# Generated by Django 4.0.6 on 2023-10-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0132_exam_is_enem_simulator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Elaborando'), (1, 'Revisão de itens'), (2, 'Fechada'), (3, 'Diagramação'), (4, 'Revisão de texto')], default=0, verbose_name='Situação do caderno'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Elaborando'), (1, 'Revisão de itens'), (2, 'Fechada'), (3, 'Diagramação'), (4, 'Revisão de texto')], default=0, verbose_name='Situação do caderno'),
        ),
    ]
