# Generated by Django 4.0.6 on 2023-10-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0133_alter_examteachersubject_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='salta_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Código de prova Salta'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='salta_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Código de prova Salta'),
        ),
    ]
