# Generated by Django 4.0.6 on 2023-10-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0133_alter_exam_status_alter_historicalexam_status'),
        ('exams', '0133_alter_examteachersubject_unique_together'),
    ]

    operations = [
    ]
