# Generated by Django 4.0.6 on 2023-10-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0133_alter_exam_category_alter_exam_group_by_topic_and_more'),
        ('exams', '0134_merge_20231021_2244'),
    ]

    operations = [
    ]
