# Generated by Django 4.0.6 on 2023-10-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0134_exam_salta_code_historicalexam_salta_code'),
        ('exams', '0135_merge_20231026_1501'),
    ]

    operations = [
    ]
