# Generated by Django 4.0.6 on 2023-10-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0136_merge_20231027_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Elaborando'), (1, 'Revisão de itens'), (2, 'Fechada'), (3, 'Diagramação'), (4, 'Revisão de texto'), (5, 'Pronto para impressão')], default=0, verbose_name='Situação do caderno'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Elaborando'), (1, 'Revisão de itens'), (2, 'Fechada'), (3, 'Diagramação'), (4, 'Revisão de texto'), (5, 'Pronto para impressão')], default=0, verbose_name='Situação do caderno'),
        ),
    ]
