# Generated by Django 4.0.6 on 2023-11-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0137_alter_exam_status_alter_historicalexam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='Foi adicionada em uma solicitação atrasada'),
        ),
        migrations.AddField(
            model_name='historicalexamquestion',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='Foi adicionada em uma solicitação atrasada'),
        ),
    ]
