# Generated by Django 4.0.6 on 2023-11-23 19:38

from django.db import migrations
from fiscallizeon.exams.models import ExamQuestion
from django.db.models import F

def set_is_lates(apps, schema_editor):
    queryset = ExamQuestion.objects.filter(
        exam__elaboration_deadline__isnull=False
    ).annotate(deadline=F('exam__elaboration_deadline'))
    
    queryset.filter(deadline__lt=F('created_at')).update(is_late=True)

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0138_examquestion_is_late_historicalexamquestion_is_late'),
    ]

    operations = [
        migrations.RunPython(set_is_lates, reverse_code=migrations.RunPython.noop)
    ]
