# Generated by Django 4.0.6 on 2023-12-03 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0138_alter_historicalexam_options_and_more'),
        ('exams', '0139_auto_20231123_1638'),
    ]

    operations = [
    ]
