# Generated by Django 4.0.6 on 2024-01-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0140_merge_20231203_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusquestion',
            name='annuled_give_score',
            field=models.BooleanField(default=False, verbose_name='Questão anulada e pontuação dada'),
        ),
    ]
