# Generated by Django 4.0.6 on 2023-12-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0140_merge_20231203_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalexam',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Caderno'},
        ),
        migrations.AlterModelOptions(
            name='historicalexamquestion',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Questão na prova'},
        ),
        migrations.AlterModelOptions(
            name='historicalexamteachersubject',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Professor na prova'},
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalexamquestion',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalexamteachersubject',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='statusquestion',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aprovada'), (1, 'Reprovada'), (2, 'Em aberto'), (3, 'Aguardando correção'), (4, 'Corrigido'), (5, 'Visto'), (6, 'Anulada'), (7, 'Usar depois'), (8, 'Rascunho')], default=2, verbose_name='Situação'),
        ),
    ]
