# Generated by Django 4.0.6 on 2023-12-14 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0141_alter_exam_options_alter_historicalexam_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('-created_at',), 'permissions': (('can_change_status_exam', 'Pode alterar o status do caderno'),), 'verbose_name': 'Caderno', 'verbose_name_plural': 'Cadernos'},
        ),
    ]
