# Generated by Django 4.0.6 on 2024-01-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0141_alter_historicalexam_options_and_more'),
        ('exams', '0141_statusquestion_annuled_give_score'),
    ]

    operations = [
    ]
