# Generated by Django 4.0.6 on 2023-12-14 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0142_alter_exam_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('-created_at',), 'permissions': (('can_change_status_exam', 'Pode alterar o status do caderno'), ('can_diagram_exam', 'Pode diagramar caderno')), 'verbose_name': 'Caderno', 'verbose_name_plural': 'Cadernos'},
        ),
    ]
