# Generated by Django 4.0.6 on 2024-02-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0143_alter_exam_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='not_applicable',
            field=models.BooleanField(default=False, verbose_name='não aplicável?'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='not_applicable',
            field=models.BooleanField(default=False, verbose_name='não aplicável?'),
        ),
    ]
