# Generated by Django 4.0.6 on 2024-02-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0143_exam_not_applicable_historicalexam_not_applicable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalexam',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Caderno', 'verbose_name_plural': 'historical Cadernos'},
        ),
        migrations.AlterModelOptions(
            name='historicalexamquestion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Questão na prova', 'verbose_name_plural': 'historical Questões na prova'},
        ),
        migrations.AlterModelOptions(
            name='historicalexamteachersubject',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Professor na prova', 'verbose_name_plural': 'historical Professores na prova'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='not_applicable',
            field=models.BooleanField(default=False, help_text='Marque esta opção se deseja que esse caderno não seja usado em aplicações.', verbose_name='não permitir aplicação do caderno?'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='not_applicable',
            field=models.BooleanField(default=False, help_text='Marque esta opção se deseja que esse caderno não seja usado em aplicações.', verbose_name='não permitir aplicação do caderno?'),
        ),
        migrations.AlterField(
            model_name='historicalexamquestion',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalexamteachersubject',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
