# Generated by Django 4.0.6 on 2023-12-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0145_alter_exam_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('-created_at',), 'permissions': (('can_change_status_exam', 'Pode alterar o status dos cadernos'), ('can_diagram_exam', 'Pode diagramar cadernos'), ('can_review_questions_exam', 'Pode revisar questões dos caderno'), ('can_view_result_exam', 'Pode visualizar resultado dos caderno'), ('can_correct_answers_exam', 'Pode corrigir respostas dos cadernos'), ('can_print_exam', 'Pode imprimir cadernos')), 'verbose_name': 'Caderno', 'verbose_name_plural': 'Cadernos'},
        ),
    ]
