# Generated by Django 4.0.6 on 2023-12-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0147_alter_exam_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('-created_at',), 'permissions': (('can_change_status_exam', 'Pode alterar o status dos cadernos'), ('can_diagram_exam', 'Pode diagramar cadernos'), ('can_review_questions_exam', 'Pode revisar questões dos caderno'), ('can_view_result_exam', 'Pode visualizar resultado dos caderno'), ('can_correct_answers_exam', 'Pode corrigir respostas dos cadernos'), ('can_print_exam', 'Pode imprimir cadernos'), ('view_template_exam', 'Pode visualizar gabarito avulso'), ('add_template_exam', 'Pode adicionar gabarito avulso'), ('change_template_exam', 'Pode alterar gabarito avulso'), ('delete_template_exam', 'Pode deletar gabarito avulso'), ('print_template_exam', 'Pode imprimir gabarito para divulgação'), ('export_template_exam_results', 'Pode exportar dados de gabarito avulso')), 'verbose_name': 'Caderno', 'verbose_name_plural': 'Cadernos'},
        ),
    ]
