# Generated by Django 4.0.6 on 2024-01-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0141_alter_historicalexam_options_and_more'),
        ('exams', '0150_alter_exam_options'),
    ]

    operations = [
    ]
