# Generated by Django 4.0.6 on 2024-01-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0142_merge_20240121_1710'),
        ('exams', '0151_merge_20240108_1440'),
    ]

    operations = [
    ]
