# Generated by Django 4.0.6 on 2024-02-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0143_exam_not_applicable_historicalexam_not_applicable'),
        ('exams', '0152_merge_20240122_1038'),
    ]

    operations = [
    ]
