# Generated by Django 4.0.6 on 2024-02-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0143_alter_historicalexam_options_and_more'),
        ('exams', '0154_alter_historicalexam_options_and_more'),
    ]

    operations = [
    ]
