# Generated by Django 4.0.6 on 2024-02-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0155_merge_20240222_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='four_alternatives',
            field=models.BooleanField(default=False, help_text='Ative esta opção se deseja que o caderno tenha 4 alternativas por questão', verbose_name='Caderno com 4 alternativas por questão'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='four_alternatives',
            field=models.BooleanField(default=False, help_text='Ative esta opção se deseja que o caderno tenha 4 alternativas por questão', verbose_name='Caderno com 4 alternativas por questão'),
        ),
    ]
