# Generated by Django 4.0.6 on 2024-03-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0156_alter_historicalexam_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_grade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Você pode deixar essa valor em branco caso deseje escolher as notas de acordo com os professores inseridos no caderno', max_digits=10, null=True, verbose_name='Nota geral do caderno'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='total_grade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Você pode deixar essa valor em branco caso deseje escolher as notas de acordo com os professores inseridos no caderno', max_digits=10, null=True, verbose_name='Nota geral do caderno'),
        ),
    ]
