# Generated by Django 4.0.6 on 2024-03-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0156_alter_historicalexam_options_and_more'),
        ('exams', '0156_exam_four_alternatives_and_more'),
    ]

    operations = [
    ]
