# Generated by Django 4.0.6 on 2024-03-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0156_exam_four_alternatives_and_more'),
        ('exams', '0157_alter_exam_total_grade_and_more'),
    ]

    operations = [
    ]
