# Generated by Django 4.0.6 on 2024-03-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0158_alter_historicalexam_options_and_more'),
        ('exams', '0158_merge_20240325_1412'),
    ]

    operations = [
    ]
