# Generated by Django 4.0.6 on 2024-03-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0157_merge_20240322_1348'),
        ('exams', '0159_alter_historicalexam_options_and_more'),
    ]

    operations = [
    ]
