# Generated by Django 4.0.6 on 2024-03-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0159_merge_20240326_1815'),
        ('exams', '0160_merge_20240327_1122'),
    ]

    operations = [
    ]
