# Generated by Django 4.0.6 on 2024-03-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0157_alter_historicalexam_options_and_more'),
        ('exams', '0160_merge_20240327_1122'),
    ]

    operations = [
    ]
