# Generated by Django 4.0.6 on 2024-03-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0162_alter_historicalexam_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalexam',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Caderno', 'verbose_name_plural': 'historical Cadernos'},
        ),
        migrations.AlterModelOptions(
            name='historicalexamquestion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Questão na prova', 'verbose_name_plural': 'historical Questões na prova'},
        ),
        migrations.AlterModelOptions(
            name='historicalexamteachersubject',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Professor na prova', 'verbose_name_plural': 'historical Professores na prova'},
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalexamquestion',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalexamteachersubject',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
