# Generated by Django 4.0.6 on 2024-04-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0158_merge_20240321_0855'),
        ('exams', '0163_alter_historicalexam_options_and_more'),
    ]

    operations = [
    ]
