# Generated by Django 4.0.6 on 2024-04-10 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0164_merge_20240401_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='source_exam_teacher_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.examteachersubject', verbose_name='Solicitação original'),
        ),
        migrations.AddField(
            model_name='historicalexamquestion',
            name='source_exam_teacher_subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='exams.examteachersubject', verbose_name='Solicitação original'),
        ),
    ]
