# Generated by Django 4.0.6 on 2024-04-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0164_merge_20240401_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='salta_code',
        ),
        migrations.RemoveField(
            model_name='historicalexam',
            name='salta_code',
        ),
        migrations.AddField(
            model_name='exam',
            name='external_code',
            field=models.PositiveIntegerField(blank=True, help_text='Código a ser utilizado para o aluno identificar o caderno no cartão resposta', null=True, verbose_name='Código de prova'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='external_code',
            field=models.PositiveIntegerField(blank=True, help_text='Código a ser utilizado para o aluno identificar o caderno no cartão resposta', null=True, verbose_name='Código de prova'),
        ),
    ]
