# Generated by Django 4.0.6 on 2024-04-05 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0161_merge_20240328_1701'),
        ('exams', '0164_merge_20240401_1004'),
    ]

    operations = [
    ]
