# Generated by Django 4.0.6 on 2024-04-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0165_examquestion_source_exam_teacher_subject_and_more'),
    ]

    operations = [
    ]
