# Generated by Django 4.0.6 on 2024-04-05 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0158_merge_20240325_1412'),
        ('exams', '0165_remove_exam_salta_code_and_more'),
    ]

    operations = [
    ]
