# Generated by Django 4.0.6 on 2024-04-27 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0166_merge_20240405_1834'),
        ('exams', '0166_merge_20240426_2129'),
    ]

    operations = [
    ]
