# Generated by Django 4.0.6 on 2024-05-15 19:34

import django.contrib.postgres.fields
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0167_merge_20240426_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions_availables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(verbose_name='UUID'), blank=True, null=True, size=None, verbose_name='UUIDS'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='questions_availables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(verbose_name='UUID'), blank=True, null=True, size=None, verbose_name='UUIDS'),
        ),
    ]
