# Generated by Django 4.0.6 on 2024-05-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0167_merge_20240426_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={
                'ordering': ('-created_at',),
                'permissions': (
                    ('can_change_status_exam', 'Pode alterar o status dos cadernos'),
                    ('can_diagram_exam', 'Pode diagramar cadernos'),
                    ('can_review_questions_exam', 'Pode revisar questões dos caderno'),
                    ('can_view_result_exam', 'Pode visualizar resultado dos caderno'),
                    ('can_correct_answers_exam', 'Pode corrigir respostas dos cadernos'),
                    ('can_print_exam', 'Pode imprimir cadernos'),
                    ('can_duplicate_exam', 'Pode duplicar cadernos'),
                    ('export_results_exam', 'Pode exportar dados dos cadernos'),
                    ('can_import_exams', 'Pode importar cadernos'),
                    ('can_import_examteachersubjects', 'Pode importar solicitações a professores'),
                    ('view_template_exam', 'Pode visualizar gabarito avulso'),
                    ('add_template_exam', 'Pode adicionar gabarito avulso'),
                    ('change_template_exam', 'Pode alterar gabarito avulso'),
                    ('delete_template_exam', 'Pode deletar gabarito avulso'),
                    ('print_template_exam', 'Pode imprimir gabarito para divulgação'),
                    ('export_template_exam_results', 'Pode exportar dados de gabarito avulso'),
                    ('can_duplicate_template_exam', 'Pode duplicar gabarito avulso'),
                ),
                'verbose_name': 'Caderno',
                'verbose_name_plural': 'Cadernos',
            }
        ),
    ]
