# Generated by Django 4.0.6 on 2024-04-29 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0167_merge_20240426_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='quantity_alternatives',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2)], verbose_name='quantidade de alternativas'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='quantity_alternatives',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2)], verbose_name='quantidade de alternativas'),
        ),
    ]
