# Generated by Django 4.0.6 on 2024-07-11 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0168_exam_questions_availables_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questions_availables',
        ),
        migrations.RemoveField(
            model_name='historicalexam',
            name='questions_availables',
        ),
    ]
