# Generated by Django 4.0.6 on 2024-05-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0168_alter_exam_options'),
        ('exams', '0168_exam_quantity_alternatives_and_more'),
    ]

    operations = [
    ]
