# Generated by Django 4.0.6 on 2024-06-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0169_merge_20240522_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustompage',
            name='location',
            field=models.SmallIntegerField(choices=[(0, 'Antes do caderno do aluno'), (4, 'Após o caderno do aluno'), (1, 'Antes da lista de presença'), (2, 'Antes da folha de respostas objetivas'), (3, 'Antes da folha de respostas discursivas')], default=0, verbose_name='Local'),
        ),
    ]
