# Generated by Django 4.0.6 on 2024-07-11 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0169_remove_exam_questions_availables_and_more'),
        ('exams', '0170_alter_clientcustompage_location'),
    ]

    operations = [
    ]
