# Generated by Django 4.0.6 on 2024-07-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0170_alter_clientcustompage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='examteachersubject',
            name='has_error_create_exam_question_ia',
            field=models.BooleanField(default=False, verbose_name='Erro ao gerar ExamQuestion com IA'),
        ),
        migrations.AddField(
            model_name='historicalexamteachersubject',
            name='has_error_create_exam_question_ia',
            field=models.BooleanField(default=False, verbose_name='Erro ao gerar ExamQuestion com IA'),
        ),
    ]
