# Generated by Django 4.0.6 on 2024-07-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0170_alter_clientcustompage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='template_quantity_alternatives',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='quantidade de alternativas'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='template_quantity_alternatives',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='quantidade de alternativas'),
        ),
    ]
