# Generated by Django 4.0.6 on 2024-07-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0043_alter_inspector_options'),
        ('exams', '0171_merge_20240711_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='review_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo para revisão de questões'),
        ),
        migrations.AddField(
            model_name='examteachersubject',
            name='reviewed_by',
            field=models.ManyToManyField(blank=True, to='inspectors.inspector'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='review_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo para revisão de questões'),
        ),
    ]
