# Generated by Django 4.0.6 on 2024-07-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0165_merge_20240404_2320'),
        ('exams', '0171_merge_20240711_1950'),
    ]

    operations = [
    ]
