# Generated by Django 4.0.6 on 2024-08-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0171_merge_20240711_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusquestion',
            name='question_fragment',
            field=models.TextField(blank=True, default='', verbose_name='Fragmento da questão'),
        ),
    ]
