# Generated by Django 4.0.6 on 2024-08-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0171_merge_20240711_1950'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='statusquestion',
        #     name='annuled_distribute_exam_teacher_subject',
        #     field=models.BooleanField(default=False, verbose_name='Anulada e pontuação distribuída apenas na solicitação'),
        # ),
    ]
