# Generated by Django 4.0.6 on 2024-07-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0171_examteachersubject_has_error_create_exam_question_ia_and_more'),
        ('exams', '0171_merge_20240711_1950'),
    ]

    operations = [
    ]
