# Generated by Django 4.0.6 on 2024-08-06 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0172_statusquestion_question_fragment'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusquestion',
            name='source_status_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.statusquestion', verbose_name='Status fonte'),
        ),
        migrations.AlterField(
            model_name='statusquestion',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aprovada'), (1, 'Reprovada'), (2, 'Em aberto'), (3, 'Aguardando correção'), (4, 'Corrigido'), (5, 'Visto'), (6, 'Anulada'), (7, 'Usar depois'), (8, 'Rascunho'), (9, 'Resposta do professor')], default=2, verbose_name='Situação'),
        ),
    ]
