# Generated by Django 4.0.6 on 2024-08-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0172_exam_review_deadline_examteachersubject_reviewed_by_and_more'),
        ('exams', '0172_merge_20240724_1200'),
    ]

    operations = [
    ]
