# Generated by Django 4.0.6 on 2024-08-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0171_exam_template_quantity_alternatives_and_more'),
        ('exams', '0172_exam_review_deadline_examteachersubject_reviewed_by_and_more'),
    ]

    operations = [
    ]
