# Generated by Django 4.0.6 on 2024-08-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0173_merge_20240816_1432'),
        ('exams', '0173_statusquestion_source_status_question_and_more'),
    ]

    operations = [
    ]
