# Generated by Django 4.0.6 on 2024-08-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0173_merge_20240816_1539'),
        ('exams', '0174_merge_20240816_1542'),
    ]

    operations = [
    ]
