# Generated by Django 4.0.6 on 2024-08-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0173_merge_20240814_1011'),
        ('exams', '0175_merge_20240816_1607'),
    ]

    operations = [
    ]
