# Generated by Django 4.0.6 on 2024-08-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0172_statusquestion_annuled_distribute_exam_teacher_subject'),
        ('exams', '0175_merge_20240816_1607'),
    ]

    operations = [
    ]
