# Generated by Django 4.0.6 on 2024-09-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0176_merge_20240820_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='copy_exam_with_ia_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de copias feitas por IA'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='copy_exam_with_ia_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de copias feitas por IA'),
        ),
    ]
