# Generated by Django 4.0.6 on 2024-09-14 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0176_merge_20240819_1309'),
        ('exams', '0176_merge_20240820_1235'),
    ]

    operations = [
    ]
