# Generated by Django 4.0.6 on 2024-08-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0176_merge_20240820_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='examteachersubject',
            name='question_generation_status_with_ai',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Gerando'), (2, 'Finalizado'), (3, 'Erro')], default=0, verbose_name='Status da geração de questão com ia'),
        ),
        migrations.AddField(
            model_name='historicalexamteachersubject',
            name='question_generation_status_with_ai',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Gerando'), (2, 'Finalizado'), (3, 'Erro')], default=0, verbose_name='Status da geração de questão com ia'),
        ),
    ]
