# Generated by Django 4.0.6 on 2024-09-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0172_merge_20240724_1458'),
        ('exams', '0176_merge_20240820_1235'),
    ]

    operations = [
    ]
