# Generated by Django 4.0.6 on 2024-09-03 01:19

from django.db import migrations, models
import fiscallizeon.core.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0177_examteachersubject_question_generation_status_with_ai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examteachersubject',
            name='support_image_generate_question',
            field=models.ImageField(blank=True, null=True, storage=fiscallizeon.core.storage_backends.PrivateMediaStorage(), upload_to='question/ia/'),
        ),
        migrations.AddField(
            model_name='historicalexamteachersubject',
            name='support_image_generate_question',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examteachersubject',
            name='question_generation_status_with_ai',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inicial'), (1, 'Gerando'), (2, 'Finalizado'), (3, 'Erro')], default=0, verbose_name='Status da geração de questão com ia'),
        ),
        migrations.AlterField(
            model_name='historicalexamteachersubject',
            name='question_generation_status_with_ai',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inicial'), (1, 'Gerando'), (2, 'Finalizado'), (3, 'Erro')], default=0, verbose_name='Status da geração de questão com ia'),
        ),
    ]
