# Generated by Django 4.0.6 on 2024-09-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0177_exam_copy_exam_with_ia_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='copy_exam_with_ia_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Copiando'), (2, 'Finalizado'), (3, 'Erro'), (4, 'Desconhecido')], default=0, verbose_name='Status da copia do caderno com Ia'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='copy_exam_with_ia_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Copiando'), (2, 'Finalizado'), (3, 'Erro'), (4, 'Desconhecido')], default=0, verbose_name='Status da copia do caderno com Ia'),
        ),
    ]
