# Generated by Django 4.0.6 on 2024-09-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0178_exam_copy_exam_with_ia_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_used_for_copying',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Exam usado para realizar a copia'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='exam_used_for_copying',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Exam usado para realizar a copia'),
        ),
    ]
