# Generated by Django 4.0.6 on 2024-09-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0180_alter_exam_exam_used_for_copying_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_used_for_copying',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='Exam usado para realizar a copia'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='exam_used_for_copying',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='Exam usado para realizar a copia'),
        ),
    ]
