# Generated by Django 4.0.6 on 2024-09-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0181_alter_exam_exam_used_for_copying_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_used_for_copying',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Exam usado para realizar a copia'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='exam_used_for_copying',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Exam usado para realizar a copia'),
        ),
    ]
