# Generated by Django 4.0.6 on 2024-09-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0177_merge_20240914_1814'),
        ('exams', '0178_examteachersubject_support_image_generate_question_and_more'),
        ('exams', '0182_alter_exam_exam_used_for_copying_and_more'),
    ]

    operations = [
    ]
