# Generated by Django 4.0.6 on 2024-09-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0183_merge_20240920_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusquestion',
            name='annuled_distribute_exam_teacher_subject',
            field=models.BooleanField(default=False, verbose_name='Anulada e pontuação distribuída apenas na solicitação'),
        ),
    ]
