# Generated by Django 4.0.6 on 2024-09-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0177_merge_20240909_1043'),
        ('exams', '0183_merge_20240920_1240'),
    ]

    operations = [
    ]
