# Generated by Django 4.0.6 on 2024-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0185_merge_20240920_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='copy_exam_with_ia_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Copiando'), (2, 'Finalizado'), (3, 'Erro'), (4, 'Desconhecido')], default=0, verbose_name='Status da cópia do caderno com Ia'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Elaborando'), (1, 'Revisão de itens'), (2, 'Fechada'), (3, 'Diagramação'), (4, 'Revisão de texto'), (5, 'Pronto para impressão'), (6, 'Revisão de PDF')], default=0, verbose_name='Situação do caderno'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='copy_exam_with_ia_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Copiando'), (2, 'Finalizado'), (3, 'Erro'), (4, 'Desconhecido')], default=0, verbose_name='Status da cópia do caderno com Ia'),
        ),
        migrations.AlterField(
            model_name='historicalexam',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Elaborando'), (1, 'Revisão de itens'), (2, 'Fechada'), (3, 'Diagramação'), (4, 'Revisão de texto'), (5, 'Pronto para impressão'), (6, 'Revisão de PDF')], default=0, verbose_name='Situação do caderno'),
        ),
    ]
