# Generated by Django 4.0.6 on 2024-09-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0183_merge_20240918_1722'),
        ('exams', '0185_merge_20240920_1822'),
    ]

    operations = [
    ]
