# Generated by Django 4.0.6 on 2024-10-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0184_statusquestion_annuled_distribute_exam_teacher_subject'),
        ('exams', '0186_alter_exam_copy_exam_with_ia_status_and_more'),
    ]

    operations = [
    ]
