# Generated by Django 4.0.6 on 2024-10-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0186_alter_exam_copy_exam_with_ia_status_and_more'),
        ('exams', '0186_merge_20240921_1157'),
    ]

    operations = [
    ]
