# Generated by Django 4.0.6 on 2024-10-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0187_exam_review_deadline_pdf_and_more'),
        ('exams', '0187_merge_20241025_1223'),
    ]

    operations = [
    ]
