# Generated by Django 4.0.6 on 2024-10-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0187_examteachersubject_distribute_scores_freely_and_more'),
        ('exams', '0187_merge_20241026_1720'),
        ('exams', '0188_merge_20241025_1226'),
    ]

    operations = [
    ]
