# Generated by Django 4.0.6 on 2024-11-04 12:32

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0146_alter_clientquestionsconfiguration_can_add_revision_after_closing_exam'),
        ('exams', '0189_merge_20241029_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBackgroundImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(default='Identificador', max_length=255, verbose_name='Nome da página')),
                ('image', models.ImageField(blank=True, max_length=10000, null=True, upload_to='exams_backgrounds/', verbose_name='Imagem de fundo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_backgrounds', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Imagem de fundo',
                'verbose_name_plural': 'Imagens de fundo',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
