# Generated by Django 4.0.6 on 2024-11-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0190_exambackgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exambackgroundimage',
            name='image',
            field=models.ImageField(default='', max_length=10000, upload_to='exams_backgrounds/', verbose_name='Imagem de fundo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exambackgroundimage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Identificador'),
        ),
    ]
