# Generated by Django 4.0.6 on 2024-12-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0191_alter_exambackgroundimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='enable_discursive_ai_correction',
            field=models.BooleanField(default=False, help_text='Marque esta opção se deseja que esse caderno traga sugestões de correção das questões discursivas', verbose_name='Habilitar correção automática de discursivas'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='enable_discursive_ai_correction',
            field=models.BooleanField(default=False, help_text='Marque esta opção se deseja que esse caderno traga sugestões de correção das questões discursivas', verbose_name='Habilitar correção automática de discursivas'),
        ),
    ]
