# Generated by Django 4.2.18 on 2025-02-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0192_exam_enable_discursive_ai_correction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='last_erp_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da última sincronização com o ERP'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='id_erp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código no ERP'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='last_erp_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da última sincronização com o ERP'),
        ),
        migrations.AddField(
            model_name='historicalexamquestion',
            name='id_erp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código no ERP'),
        ),
    ]
