# Generated by Django 4.0.6 on 2025-02-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0192_exam_enable_discursive_ai_correction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='Marque esta opção se deseja que o caderno seja confidencial', verbose_name='Caderno confidencial'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='Marque esta opção se deseja que o caderno seja confidencial', verbose_name='Caderno confidencial'),
        ),
    ]
