# Generated by Django 4.0.6 on 2025-01-14 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0192_exam_enable_discursive_ai_correction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusquestion',
            name='is_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_checked_by', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AlterField(
            model_name='statusquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
