# Generated by Django 4.2.18 on 2025-02-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0193_exam_last_erp_sync_examquestion_id_erp_and_more'),
        ('exams', '0193_statusquestion_is_checked_by_and_more'),
    ]

    operations = [
    ]
