# Generated by Django 4.2.19 on 2025-02-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0194_alter_exam_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='confidential_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data que passa a ser confidencial'),
        ),
        migrations.AddField(
            model_name='historicalexam',
            name='confidential_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data que passa a ser confidencial'),
        ),
    ]
