# Generated by Django 4.2.18 on 2025-02-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0194_merge_20250226_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='examteachersubject',
            name='id_erp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código no ERP'),
        ),
        migrations.AddField(
            model_name='historicalexamteachersubject',
            name='id_erp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código no ERP'),
        ),
    ]
