# Generated by Django 4.2.19 on 2025-03-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0195_exam_confidential_date_and_more'),
        ('exams', '0195_examteachersubject_id_erp_and_more'),
    ]

    operations = [
    ]
