# Generated by Django 4.2.19 on 2025-05-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0196_merge_20250315_1135"),
    ]

    operations = [
        migrations.AddField(
            model_name="examteachersubject",
            name="reviewer_email_sent",
            field=models.BooleanField(
                default=False, verbose_name="Envio do email de revisão para o revisor"
            ),
        ),
        migrations.AddField(
            model_name="historicalexamteachersubject",
            name="reviewer_email_sent",
            field=models.BooleanField(
                default=False, verbose_name="Envio do email de revisão para o revisor"
            ),
        ),
    ]
